RustboroCity_Flat1_2F_MapScripts::
	.byte 0


RustboroCity_Flat1_2F_EventScript_WorkerLady::
	msgbox RustboroCity_Flat1_2F_EventScript_WorkerLady_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat1_2F_EventScript_Man::
	msgbox RustboroCity_Flat1_2F_EventScript_Man_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat1_2F_EventScript_Woman::
	msgbox RustboroCity_Flat1_2F_EventScript_Woman_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat1_2F_EventScript_WorkerLady_Text_0:
	.string "I'm sorry, but the Johto-Kanto\n"
	.string "Hyperloop is still under construction.\p"
	.string "We are currently working out some\n"
	.string "issues over on the Kanto side.$"

RustboroCity_Flat1_2F_EventScript_Man_Text_0:
	.string "I moved here from Saffron City back\n"
	.string "before they tore down the old Magnet\l"
	.string "Train.\p"
	.string "I hope they complete the Hyperloop\n"
	.string "soon, I would like to visit some old\l"
	.string "friends in Kanto.$"

RustboroCity_Flat1_2F_EventScript_Woman_Text_0:
	.string "A watched pot never boils!\p"
	.string "At least that's what people always say.\p"
	.string "I really want to see this Hyperloop\n"
	.string "completed though!$"
