FortreeCity_DecorationShop_MapScripts::
	.byte 0


FortreeCity_DecorationShop_EventScript_FatMan::
	msgbox FortreeCity_DecorationShop_EventScript_FatMan_Text_0, MSGBOX_NPC
	end


FortreeCity_DecorationShop_EventScript_Girl::
	msgbox FortreeCity_DecorationShop_EventScript_Girl_Text_0, MSGBOX_NPC
	end


FortreeCity_DecorationShop_EventScript_Guy::
	msgbox FortreeCity_DecorationShop_EventScript_Guy_Text_0, MSGBOX_NPC
	end


FortreeCity_DecorationShop_EventScript_Sailor::
	msgbox FortreeCity_DecorationShop_EventScript_Sailor_Text_0, MSGBOX_NPC
	end


FortreeCity_DecorationShop_EventScript_FatMan_Text_0:
	.string "I wanted to visit Vermilion City in\n"
	.string "Kanto, but they said they've had\l"
	.string "trouble accessing the region lately.\p"
	.string "What does that even mean?$"

FortreeCity_DecorationShop_EventScript_Girl_Text_0:
	.string "I'll be taking my little brother to\n"
	.string "Apricotta Beach soon, it's lovely this\l"
	.string "time of year.\p"
	.string "I recommend the trip if you ever get a\n"
	.string "chance.$"

FortreeCity_DecorationShop_EventScript_Guy_Text_0:
	.string "Yay! I can't wait to go to the nice warm\n"
	.string "beach!$"

FortreeCity_DecorationShop_EventScript_Sailor_Text_0:
	.string "I'll take you to Apricotta Beach later.$"
