MossdeepCity_House4_MapScripts::
	.byte 0


MossdeepCity_House4_EventScript_Woman::
	msgbox MossdeepCity_House4_EventScript_Woman_Text_0, MSGBOX_NPC
	end


MossdeepCity_House4_EventScript_NinjaBoy::
	msgbox MossdeepCity_House4_EventScript_NinjaBoy_Text_0, MSGBOX_NPC
	end


MossdeepCity_House4_EventScript_Woman_Text_0:
	.string "I'm glad my husband got an Azurill for\n"
	.string "our daughter.\p"
	.string "They really seem to love each other!$"

MossdeepCity_House4_EventScript_NinjaBoy_Text_0:
	.string "Azurill isn't a WATER-type yet, but he\n"
	.string "still loves to play in the water with me.\p"
	.string "The ball on the end of his tail floats\n"
	.string "like my innertube!$"
