Route104_MrBrineysHouse_MapScripts::
	.byte 0


Route104_MrBrineysHouse_EventScript_Man::
	msgbox Route104_MrBrineysHouse_EventScript_Man_Text_0, MSGBOX_NPC
	end


Route104_MrBrineysHouse_EventScript_Woman::
	msgbox Route104_MrBrineysHouse_EventScript_Woman_Text_0, MSGBOX_NPC
	end


Route104_MrBrineysHouse_EventScript_Man_Text_0:
	.string "Welcome to our farm.\p"
	.string "If you would like to buy some Moomoo\n"
	.string "Milk, then speak to my grandaughter in\l"
	.string "the stable.$"

Route104_MrBrineysHouse_EventScript_Woman_Text_0:
	.string "Life on the farm can feel slow at times,\n"
	.string "but I'm just glad I get to spend so\l"
	.string "much time with my family.$"
