PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to take them.\p"
	.string "But make sure you plant a BERRY in the\n"
	.string "same spot. That's common courtesy.\p"
	.string "Here, I'll share this with you.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "The way you look, you must be a\n"
	.string "TRAINER, no?\p"
	.string "TRAINERS often make POKéMON hold\n"
	.string "BERRIES.\p"
	.string "It's up to you whether to grow BERRIES\n"
	.string "or use them.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I'm going to try really hard and make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Hiya! I'm no TRAINER, but I like helping\n"
	.string "out TRAINERS.\p"
	.string "Here, you can have this!$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Come back tomorrow, and I'll have\n"
	.string "another BERRY for you!$"

Route114_Text_FunToThinkAboutBerries:
	.string "Some BERRIES are pretty rare, you'll\n"
	.string "want to plant those rare ones if you\l"
	.string "ever want any more.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "I've always lived here with my grandma,\n"
	.string "she taught me to help others as much as\l"
	.string "I can.\p"
	.string "Here, you can have this...$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I think that BERRY is pretty rare, I\n"
	.string "hope you put it to good use.\p"
	.string "By the way, if your POKéMON are injured,\n"
	.string "you should see my grandma inside.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "That's all I have for you now, please\n"
	.string "come back tomorrow if you want another\l"
	.string "BERRY.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When it gets right down to it…\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "When it gets right down to it…\p"
	.string "It's because you're a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "When it gets right down to it…\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "I believe nobody can have too many\n"
	.string "berries!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hello!\p"
	.string "This is the PRETTY PETAL flower shop.\n"
	.string "Spreading flowers all over the world!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Your name is?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "That's a nice name.\p"
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRIES grow on trees that thrive\n"
	.string "only in soft, loamy soil.\p"
	.string "If you take some BERRIES, be sure to\n"
	.string "plant one in the loamy soil again.\p"
	.string "A planted BERRY will soon sprout,\n"
	.string "grow into a plant, flower beautifully,\l"
	.string "then grow BERRIES again.\p"
	.string "I want to see the whole wide world\n"
	.string "filled with beautiful flowers.\l"
	.string "That's my dream.\p"
	.string "Please help me, {PLAYER}{KUN}. Plant BERRIES\n"
	.string "and bring more flowers into the world.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Flowers bring so much happiness to\n"
	.string "people, don't they?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hello!\p"
	.string "The more attention you give to flowers,\n"
	.string "the more beautifully they bloom.\p"
	.string "You'll like tending flowers. I'm sure\n"
	.string "of it. You can have this.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "While BERRY plants are growing,\n"
	.string "water them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground.\l"
	.string "But they'll sprout again.\p"
	.string "Isn't that awesome?\n"
	.string "It's like they have the will to live.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "What's with that apathetic look on your\n"
	.string "face?\p"
	.string "Here, maybe this will cheer you up...$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Hmm... It seems the apathy remains...\p"
	.string "Could that be the only face you can\n"
	.string "make?$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "We must always seek to give back to\n"
	.string "mother nature in whatever ways we can.\p"
	.string "One way I like to give back to nature is\n"
	.string "by planting BERRIES.\p"
	.string "Here, you should plant more BERRIES\n"
	.string "too.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "Hmm... Maybe just one more for good\n"
	.string "measure.$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Come back tomorrow, and I should have\n"
	.string "more for you.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Tell me, have you planted the BERRIES I\n"
	.string "gave you?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "How wonderful!\p"
	.string "Mother nature will appreciate your\n"
	.string "kindness, dear child.$"

SootopolisCity_Text_OhDoesntMatter:
	.string "That's a shame.\p"
	.string "There's still plenty of time left in the\n"
	.string "day though.$"
