gText_Birch_Welcome::
	.string "Hello there, welcome back to the world\n"
	.string "of POKéMON!\p"
	.string "My name is Professor Elm, I run a\n"
	.string "POKéMON LAB over in New Bark Town.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "By the way, this is what we call a\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "The Johto region has sure seen a large\n"
	.string "influx of different species in the last\l"
	.string "few years.\p"
	.string "Whether this explosive migration is\n"
	.string "natural or caused by human\l"
	.string "interference has yet to be determined.\p"
	.string "Nevertheless, this occurrence is very\n"
	.string "exciting for POKéMON researchers like\l"
	.string "myself.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, my eyes aren’t as good as they used\n"
	.string "to be.\l"
	.string "So tell me...\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or a girl?$"

gText_Birch_WhatsYourName::
	.string "Of course, it’s so obvious now.\n"
	.string "And what is your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Oh, so you're {PLAYER}!\p"
	.string "I’ve heard plenty about you from your\n"
	.string "parents.\p"
	.string "You live in Cherrygrove City, it’s very\n"
	.string "close to New Bark Town, where I live.\l"
	.string "I’m expecting great things from you.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Now then, are you ready?\n"
	.string "Your very own adventure is about to\l"
	.string "begin!\p"
	.string "This world is filled with many different\n"
	.string "kinds of people and POKéMON. You will\l"
	.string "have to overcome many obstacles, but\l"
	.string "if you put in enough effort, you will be\l"
	.string "able to accomplish anything.\p"
	.string "Stop by my lab later, and I will present\n"
	.string "you with your very first POKéMON.\p"
	.string "Let’s go!\p"
	.string "$"
