MatchCall_WildBattleText1::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I just saw the biggest {STR_VAR_2}\n"
	.string "I've ever seen in my life!\p"
	.string "You wouldn't believe the size of\n"
	.string "this thing!\p"
	.string "It got away from me though, such a\n"
	.string "bummer!\p"
	.string "Well, maybe next time.\p"
	.string "Ok, that's it. See ya!$"

MatchCall_WildBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "This is going to sound weird, but\n"
	.string "a wild {STR_VAR_2} just popped out\l"
	.string "of some grass, gave me a dirty\l"
	.string "look, and then ran off!\p"
	.string "What did I ever do to offend this\n"
	.string "random {STR_VAR_2}?\p"
	.string "That's all, talk to you later.$"

MatchCall_WildBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "So, I just encountered a wild\n"
	.string "{STR_VAR_2}, but it was a different\l"
	.string "color than normal.\p"
	.string "It also had a sort of sparkle look.\p"
	.string "I figured it was diseased or\n"
	.string "something, so I let it go.\p"
	.string "All right, that's all. See you!$"

MatchCall_WildBattleText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Man, this {STR_VAR_2} I was trying\n"
	.string "to catch kept breaking out after\l"
	.string "three POKéBALL shakes.\p"
	.string "I was so heated, that I just went\n"
	.string "and knocked the thing out!\p"
	.string "Maybe I got a little too worked up.\p"
	.string "Has that ever happened to you?$"

MatchCall_WildBattleText5::
	.string "Hello, who is this?\p"
	.string "...\p"
	.string "Oh, {PLAYER}?\p"
	.string "This is {STR_VAR_1}.\p"
	.string "...\p"
	.string "Sorry, I must have butt-dialed you\n"
	.string "or something.\p"
	.string "Well, have a good one!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "So, yesterday I came face-to-face\n"
	.string "with a wild {STR_VAR_2}.\p"
	.string "I was feeling cheeky, so threw a\n"
	.string "POKéBALL without even damaging it\l"
	.string "first.\p"
	.string "Well, one... two... three...\p"
	.string "And I caught it, just like that!\p"
	.string "It must have been my lucky day!\p"
	.string "You take care, {PLAYER}.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "So, I was trying some {STR_VAR_2}\n"
	.string "calls to try and draw one in, but\l"
	.string "I think I was accidentally making\l"
	.string "mating calls...\p"
	.string "That was a close one!\p"
	.string "You do not want to see a wild\n"
	.string "{STR_VAR_2} in heat, trust me!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I tried wearing a {STR_VAR_2}\n"
	.string "costume to see if I could sneak\l"
	.string "into a group of them, but they saw\l"
	.string "right through my disguise!\p"
	.string "I need to try harder next time!\n"
	.string "That's all, take care now!$"

MatchCall_WildBattleText9::
	.string "Yo, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I just threw like thirty\n"
	.string "POKéBALLS at a stupid {STR_VAR_2},\l"
	.string "but still didn't catch it!\p"
	.string "I really have the worst luck, I\n"
	.string "tell you!\p"
	.string "That's it, see ya!$"

MatchCall_WildBattleText10::
	.string "{PLAYER}?, It's {STR_VAR_1}.\p"
	.string "This is bad, I'm being stalked by\n"
	.string "an aggressive {STR_VAR_2}…\p"
	.string "I think I gave it the slip though…\p"
	.string "Oh crap, I think it heard-\n"
	.string "Gahhh!$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to get away\n"
	.string "from me.\p"
	.string "I don't know how I'll ever recover\n"
	.string "from this…$"

MatchCall_WildBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "I was trying to catch a wild\n"
	.string "{STR_VAR_2} earlier, but then I\l"
	.string "accidentally knocked it out!\p"
	.string "I'm so mad at myself right now!\p"
	.string "Has that ever happened to you?$"

MatchCall_WildBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Have you been catching a ton of\n"
	.string "POKéMON?\p"
	.string "I've been catching as many as I\n"
	.string "can, but apparently, it doesn't\l"
	.string "count if they're all the same\l"
	.string "species.\p"
	.string "I guess they have to be different.\p"
	.string "The more you know!$"

MatchCall_WildBattleText14::
	.string "{PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a cute\n"
	.string "{STR_VAR_2}, but it got away.\p"
	.string "I guess it didn't want to be caught\n"
	.string "by me.\p"
	.string "What is it, my breath?\p"
	.string "It's not that...\p"
	.string "Oh...\p"
	.string "Well, nevermind.$"

MatchCall_WildBattleText15::
	.string "Hey, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been trying to catch some\n"
	.string "POKéMON, but can't seem to find\l"
	.string "any.\p"
	.string "Do you have any tips?\p"
	.string "...\p"
	.string "Uh huh...\p"
	.string "Oh, so I shouldn't be spraying\n"
	.string "repels every time I'm in the grass?\p"
	.string "Thanks {PLAYER}, this might work!\p"
	.string "Well, see ya!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I entered as a contestant in\n"
	.string "The Challenge, but lost in the\l"
	.string "qualifying rounds.\p"
	.string "Talk about a humbling experience.\p"
	.string "Well, see you again sometime!$"

MatchCall_NegativeBattleText2::
	.string "Yo, {PLAYER}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "So I challenged some nerd to a\n"
	.string "battle because I thought they\l"
	.string "looked pretty weak, but ended up\l"
	.string "getting my butt handed to me.\p"
	.string "It was pretty humiliating.\p"
	.string "Oh well, I guess you win some, and\n"
	.string "you lose some!$"

MatchCall_NegativeBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got destroyed in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!\p"
	.string "Why am I so bad!?$"

MatchCall_NegativeBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another battle yesterday,\n"
	.string "but I couldn't pull out the win.\p"
	.string "Ugh, I was so close too!\p"
	.string "I guess I need to train more.\p"
	.string "Okay, catch you later.$"

MatchCall_NegativeBattleText5::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "So, I've been on a pretty good\n"
	.string "winning streak lately, but finally\l"
	.string "lost to someone.\p"
	.string "Losing sucks.\p"
	.string "Right, take care!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Well, ever since I lost to you the\n"
	.string "other day, I haven't been able to\l"
	.string "win a single battle.\p"
	.string "I must be cursed now...\p"
	.string "Thanks {PLAYER}...$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going, {PLAYER}?\p"
	.string "I lost a battle yesterday,\n"
	.string "not a fun experience.\p"
	.string "I need to come up with some new\n"
	.string "battling strategies.\p"
	.string "Well, talk to you later.$"

MatchCall_NegativeBattleText8::
	.string "I just don't know how do you do\n"
	.string "it, {PLAYER}.\p"
	.string "It's {STR_VAR_1}, by the way.\p"
	.string "I keep losing battle after battle,\n"
	.string "no matter what I try.\p"
	.string "You must tell me your secrets!\p"
	.string "...\p"
	.string "Uh huh...\p"
	.string "...\p"
	.string "Yeah, that might work!\p"
	.string "Thanks for the help, {PLAYER}!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Listen, listen, you have to hear\n"
	.string "this!\p"
	.string "I had a POKéMON battle earlier,\n"
	.string "but I lost at the last second.\p"
	.string "All of my hopes and dreams,\n"
	.string "shattered in an instant!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A little earlier, I was in a battle.\n"
	.string "I lost, though.\p"
	.string "Am I the worst TRAINER there is,\n"
	.string "or what?\p"
	.string "Maybe I just need to train my\n"
	.string "POKéMON some more.\p"
	.string "Okay, see you around.$"

MatchCall_NegativeBattleText11::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I've just felt so depressed lately\n"
	.string "since I keep losing every battle.\p"
	.string "Maybe I should take up quilting\n"
	.string "instead.\p"
	.string "That wouldn't be so bad, right?\p"
	.string "Well, see you...$"

MatchCall_NegativeBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Are you still battling a lot?\p"
	.string "I lost recently, so I scrapped my\n"
	.string "whole team to start from scratch.\p"
	.string "Let's meet again sometime.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I was in a battle just a little\n"
	.string "while before this, but lost in\l"
	.string "spectacular fashion.\p"
	.string "Don't be like me, {PLAYER}{KUN}.\p"
	.string "Talk to you later!$"

MatchCall_NegativeBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How have you been?\p"
	.string "...\p"
	.string "Well, that's good, but you should\n"
	.string "go home every so often.\p"
	.string "I bet your mom is missing you.\p"
	.string "Ok, later!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another TRAINER earlier,\n"
	.string "and mopped the floor with them!\p"
	.string "My {STR_VAR_2} made some rude\n"
	.string "gestures at them after we won.\p"
	.string "Maybe I shouldn't encourage that\n"
	.string "kind of behavior.\p"
	.string "Oh well, see ya!$"

MatchCall_PositiveBattleText2::
	.string "Hello, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "I had a battle yesterday, and\n"
	.string "I won!\p"
	.string "Man, I'm great!\p"
	.string "You could learn a thing or two from\n"
	.string "me.\p"
	.string "Ok, later {PLAYER}.$"

MatchCall_PositiveBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\p"
	.string "Have any good battles lately?\p"
	.string "Me? Pfft, I had a crazy battle the\n"
	.string "other day.\p"
	.string "My {STR_VAR_2} went wild on some\n"
	.string "unsuspecting nerd!\p"
	.string "The next time I battle you,\n"
	.string "{PLAYER}, it won't be me losing!\p"
	.string "It will be you!$"

MatchCall_PositiveBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I managed to win, but it was close.\p"
	.string "My {STR_VAR_2} really pulled\n"
	.string "through for the team.\p"
	.string "I should buy it some good\n"
	.string "POKéBLOCKS later.$"

MatchCall_PositiveBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Have I told you about my\n"
	.string "{STR_VAR_2} yet today?\p"
	.string "It's pretty much the best\n"
	.string "POKéMON there is.\p"
	.string "It hasn't lost a single battle\n"
	.string "since you.\p"
	.string "Right, take care!$"

MatchCall_PositiveBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been on a winning streak\n"
	.string "lately.\p"
	.string "In fact, I just won a another\n"
	.string "battle today.\p"
	.string "When we have our next battle,\n"
	.string "I know I won't be the loser!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force to be\n"
	.string "reckoned with!\p"
	.string "It won me another battle just now!\p"
	.string "I can't wait to have a rematch\n"
	.string "with you.\p"
	.string "I'll show you what's up!$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you've been well.\p"
	.string "I wanted to tell you I just won\n"
	.string "another battle, and it's all thanks\l"
	.string "to my {STR_VAR_2}!\p"
	.string "It really is the greatest!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText9::
	.string "{PLAYER}{KUN}, how are you?\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've started feeding my {STR_VAR_2}\n"
	.string "some special vitamins that aren't\l"
	.string "even on the market yet.\p"
	.string "I got them from this shady looking\n"
	.string "guy in Kanto.\p"
	.string "I'm not sure what's in them, but\n"
	.string "they've definitely helped me win\l"
	.string "some battles, so I don't care!\p"
	.string "Well, see you again!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "So, this guy was bullying me,\n"
	.string "trying to get me to battle him, and\l"
	.string "I did.\p"
	.string "Well guess what?\p"
	.string "I totally destroyed him!\p"
	.string "It was so one-sided, that I\n"
	.string "actually felt a little bad for him.\p"
	.string "That's all, see you around.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I've had like so many battles, I\l"
	.string "can't even count them all!\p"
	.string "Being a TRAINER sure is wild,\n"
	.string "right?\p"
	.string "Well, see you!$"

MatchCall_PositiveBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I trust you've been well?\n"
	.string "I'm still bursting with life!\p"
	.string "Why, just now, I won another match.\n"
	.string "I'm not stepping aside to you\l"
	.string "youngsters yet!$"

MatchCall_PositiveBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a battle yet again.\n"
	.string "Oh, I won't lose to young people\l"
	.string "quite yet!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it.\p"
	.string "Maybe next time. Later!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Huh? Wait, you're near\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, wow, we have to battle, then!\n"
	.string "I'll be waiting! See you!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, hey, are you near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to battle with\n"
	.string "me right now?\p"
	.string "I'm not losing again!\n"
	.string "I'll be waiting! Catch you soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "You're where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I'll keep an eye out for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your POKéMON keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my POKéMON.\n"
	.string "I'll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I'll wait for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Oh, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "We should have a battle now, then.\p"
	.string "I'm ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a battle, don't you think?\p"
	.string "I'll wait around for you!\n"
	.string "See you real quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That's quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Since that's not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I'll wait for you.\n"
	.string "Bye for now.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You're what? …{STR_VAR_2}?\n"
	.string "That's very close.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle?\p"
	.string "I'll be looking for you!\n"
	.string "Bye-bye!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Kind of random, but would you like\n"
	.string "to have a battle with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Would you like to have a battle\n"
	.string "with me again?\p"
	.string "You can find me around\n"
	.string "{STR_VAR_2}. I'll be waiting!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My POKéMON have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your POKéMON, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My POKéMON have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My POKéMON are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "battle with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "battle with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Are your POKéMON growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My POKéMON are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your POKéMON doing?\p"
	.string "My POKéMON keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My POKéMON have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another battle with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My POKéMON are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your POKéMON, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my POKéMON have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your POKéMON keeping well?\p"
	.string "My POKéMON have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, yes! My POKéMON are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, okay?$"

MatchCall_PersonalizedText1::
	.string "Hey {PLAYER}, it's me, {STR_VAR_1}.\p"
	.string "I'm just letting you know that Dark\n"
	.string "Cave is still pretty dark, just in\l"
	.string "case you were wondering.\p"
	.string "Well, see you around sometime.$"

MatchCall_PersonalizedText2::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I've been in the Ruins of Alph for\n"
	.string "so long now, that I think the Unown\l"
	.string "are attempting to communicate with\l"
	.string "me.\p"
	.string "Just the other day, I saw an H and\n"
	.string "an I Unown next to each other.\p"
	.string "This can't just be a coincidence!$"

MatchCall_PersonalizedText3::
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "This will sound weird, but it keeps\n"
	.string "bugging me.\p"
	.string "Flowers give off a sweet scent in\n"
	.string "order to attract bugs that will\l"
	.string "carry their pollen to another\l"
	.string "flower.\p"
	.string "So, plants are basically tricking\n"
	.string "bugs into joining their weird\l"
	.string "mating rituals!\p"
	.string "Isn't that risqué?$"

MatchCall_PersonalizedText4::
	.string "{PLAYER}, I'm so mad right now!\n"
	.string "It's {STR_VAR_1}, by the way.\p"
	.string "I finally found my hiking boots,\n"
	.string "but there's a big hole in them!\p"
	.string "How am I supposed to climb\n"
	.string "Mt. Tempest like this?$"

MatchCall_PersonalizedText5::
	.string "Howdy {PLAYER}, it's {STR_VAR_1}!\p"
	.string "Just wondering if your POKéMON are\n"
	.string "ready to start working on the farm!\p"
	.string "Hehe, just kidding.\p"
	.string "I reckon we sure could use the help\n"
	.string "though.\p"
	.string "Ok, I'll let you go now.\n"
	.string "Y'all take care now!$"

MatchCall_PersonalizedText6::
	.string "Ahoy! {STR_VAR_1} here.\p"
	.string "All is good here, we haven't set\n"
	.string "sail yet, so I'm a little bored.\p"
	.string "Well, I won't hold you too long.\p"
	.string "Bye!$"

MatchCall_PersonalizedText7::
	.string "Hello, this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole COOLTRAINER thing…\p"
	.string "Everyone thinks I'm a perfect\n"
	.string "TRAINER, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "But I guess that goes with being\n"
	.string "a COOLTRAINER.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don't worry, I won't whine!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my POKéMON with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have TRAINER\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9::
	.string "It's {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn't there something…?\p"
	.string "The Unown here in the ruins, they\n"
	.string "speak to me...\p"
	.string "They tell me about you…\p"
	.string "You should walk away quickly and\n"
	.string "never once look back…\p"
	.string "Hehehe…\n"
	.string "Farewell…$"

MatchCall_PersonalizedText10::
	.string "Hey, it's {STR_VAR_1}.\n"
	.string "I've been so frustrated with my\l"
	.string "boyfriend lately.\p"
	.string "He's a great person, but he sucks\n"
	.string "at POKéMON battling.\p"
	.string "I wish he was a strong TRAINER like\n"
	.string "you are.\p"
	.string "Alright, I'm done venting. Bye!$"

MatchCall_PersonalizedText11::
	.string "Hey, it's {STR_VAR_1}!\n"
	.string "Just so you know, it's still\l"
	.string "raining here on Route D, and this\l"
	.string "bug guy next to me is still creepy!\p"
	.string "I just can't stand this route!\p"
	.string "Ok, that's all. Bye!$"

MatchCall_PersonalizedText12::
	.string "Hello, {STR_VAR_1} here.\n"
	.string "I've tried camping in different\l"
	.string "locations around Johto, but I think\l"
	.string "my favorite spot would have to be\l"
	.string "up on Mt. Rage.\p"
	.string "It's pretty cold this time of year,\n"
	.string "but the view is great!\p"
	.string "Until next time.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Random thought, but when I die, I\n"
	.string "hope I become a wandering spirit.\p"
	.string "It would be so fun to roam around,\n"
	.string "and play tricks on unsuspecting\l"
	.string "people...\p"
	.string "Ufufufufufu…$"

MatchCall_PersonalizedText14::
	.string "Oh, it's {STR_VAR_1}!\p"
	.string "I was just thinking I'm getting\n"
	.string "bored of the ABANDONED SHIP.\p"
	.string "But since I'm already here,\n"
	.string "and I want to beat you once,\l"
	.string "I'll be sticking around a bit more.\p"
	.string "If you feel compelled, why don't\n"
	.string "you come see me?\p"
	.string "I think today will be the day that\n"
	.string "I finally challenge the man next\l"
	.string "door to a match.\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15::
	.string "{STR_VAR_1} here!\n"
	.string "Have you heard of the POKéMON\l"
	.string "Kleavor?\p"
	.string "Rumor has it that you can evolve\n"
	.string "a Scyther into Kleavor by using\l"
	.string "Black Augurite.\p"
	.string "Wild Graveler can carry Black\n"
	.string "Augurite, or so I've heard.\p"
	.string "Well, I have to go now!$"

MatchCall_PersonalizedText16::
	.string "Hiya, it's {STR_VAR_1}!\n"
	.string "Do you know why I like extra tall\l"
	.string "grass?\p"
	.string "It's easier to sneak up on\n"
	.string "unsuspecting POKéMON!\p"
	.string "Wahaha!\p"
	.string "See ya, {PLAYER}.$"

MatchCall_PersonalizedText17::
	.string "Yo, it's {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your episodes.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "Yo, it's {STR_VAR_1}!\n"
	.string "I was writing a song about our\l"
	.string "battle, but it ended up sounding\l"
	.string "depressing since I lost.\p"
	.string "Maybe one day I can sing a song of\n"
	.string "victory!\p"
	.string "I'll let you know when it's done.$"

MatchCall_PersonalizedText19::
	.string "Hey, it's {STR_VAR_1}.\n"
	.string "Just wondering if you've come to\l"
	.string "appreciate the greatness of\l"
	.string "FLYING-type POKéMON yet.\p"
	.string "...\p"
	.string "Hmm... Well, maybe one day.\p"
	.string "I'll call and check again later.$"

MatchCall_PersonalizedText20::
	.string "It's me, {STR_VAR_1}!\p"
	.string "Do you know what the best part of\n"
	.string "winter is?\p"
	.string "All of the snow everywhere!\p"
	.string "It makes my camping trips feel like\n"
	.string "an adventure into the barren\l"
	.string "wilderness!\p"
	.string "Haha, see you around!$"

MatchCall_PersonalizedText21::
	.string "{PLAYER}, it's {STR_VAR_1}.\n"
	.string "Some girl from Goldenrod City told\l"
	.string "me she thinks BUG-type POKéMON are\l"
	.string "creepy.\p"
	.string "That's absurd!\p"
	.string "I'm not-I mean, they're not creepy!\p"
	.string "That's all today…$"

MatchCall_PersonalizedText22::
	.string "Hey {PLAYER}, {STR_VAR_1} here...\n"
	.string "I have a confession...\p"
	.string "I don't really have psychic powers.\p"
	.string "I just pretend I do so I can make\n"
	.string "friends!\p"
	.string "I'm an awful person, aren't I?$"

MatchCall_PersonalizedText23::
	.string "It's {STR_VAR_1}.\p"
	.string "This is terrible, {PLAYER}!\p"
	.string "I've heard there are some people\n"
	.string "pretending to have psychic powers!\p"
	.string "You think you can trust people, and\n"
	.string "then you hear stories like this.\p"
	.string "What are we to do?$"

MatchCall_PersonalizedText24::
	.string "Tell me, {PLAYER}, do you know what\n"
	.string "it takes to be considered a\l"
	.string "gentleman?\p"
	.string "You must put everyone else before\n"
	.string "yourself!\p"
	.string "This is {STR_VAR_1}, by the way.\p"
	.string "Well, you take care now.$"

MatchCall_PersonalizedText25::
	.string "Hey! It's {STR_VAR_1}!\n"
	.string "I wanted to let you in on a little\l"
	.string "secret.\p"
	.string "I heard a rumor that someone\n"
	.string "spotted a wild Lapras right here in\l"
	.string "Union Cave!\p"
	.string "I wonder where it's hiding...\p"
	.string "That's all, see you later!$"

MatchCall_PersonalizedText26::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm still stuck in Union Cave...\p"
	.string "So, how's your day going?\p"
	.string "...\p"
	.string "Oh, I see! That sounds like fun!\p"
	.string "Well, I guess I'll let you go now.\p"
	.string "Talk to you later!$"

MatchCall_PersonalizedText27::
	.string "Hey, it's LYNN.\p"
	.string "I'm here with EVE, and we were\n"
	.string "hearing some pretty strange sounds\l"
	.string "coming from the POKéMON Daycare...\p"
	.string "I think some of the POKéMON are\n"
	.string "having a little too much fun, if\l"
	.string "you know what I mean...\p"
	.string "Ok, gotta go!$"

MatchCall_PersonalizedText28::
	.string "Hey there, it's {STR_VAR_1}!\p"
	.string "I'm just calling to remind you how\n"
	.string "beautiful my Jynx is!\p"
	.string "You should stop by sometime so you\n"
	.string "can gaze upon her beauty some more.\p"
	.string "Ok, see you again!$"

MatchCall_PersonalizedText29::
	.string "{STR_VAR_1} here!\n"
	.string "Say, have you ever gone skiing?\p"
	.string "I wanted to try it out since I'm\n"
	.string "here at the Rage Resort, but I'm a\l"
	.string "little scared that I'll fall and\l"
	.string "make a fool out of myself.\p"
	.string "Ok, bye now!$"

MatchCall_PersonalizedText30::
	.string "Zzz… Oh, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You know, naps are good for your\n"
	.string "health.\p"
	.string "A lack of sleep can really be more\n"
	.string "damaging than you think!\p"
	.string "Well, you take care!$"

MatchCall_PersonalizedText31::
	.string "It's {STR_VAR_1}.\n"
	.string "I'm glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been battling young TRAINERS\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "I imagine you'll become an EXPERT\n"
	.string "in your old age! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Hey! This is {STR_VAR_1}!\n"
	.string "How are you doing, my rival?\p"
	.string "Have you been keeping up with your\n"
	.string "training?\p"
	.string "I know I've been training hard!\p"
	.string "Just you wait, the next time we\n"
	.string "battle, I'll make you run home\l"
	.string "crying!\p"
	.string "Hehe! I look forward to it!$"

MatchCall_PersonalizedText33::
	.string "Yo {PLAYER}!\n"
	.string "{STR_VAR_1} here!\p"
	.string "I just caught the biggest\n"
	.string "Barraskewda you've ever seen!\p"
	.string "It's crazy what you can fish up in\n"
	.string "even the calmest little\l"
	.string "unsuspecting ponds!\p"
	.string "I'll let you go now, later!$"

MatchCall_PersonalizedText34::
	.string "Hey, there! It's {STR_VAR_1}.\n"
	.string "You know, some people think it's\l"
	.string "dangerous to slide around on the\l"
	.string "ice, but since I've been at the\l"
	.string "Rage Resort, I've only seen two\l"
	.string "people fall through the ice!\p"
	.string "That's only two out of who knows\n"
	.string "how many!\p"
	.string "I'll take those chances any day!\p"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I'm still skiing on the Lake of\l"
	.string "Rage.\p"
	.string "Skiing is much more exhausting than\n"
	.string "you would think.\p"
	.string "It takes a lot of work to move\n"
	.string "around like this!\p"
	.string "Well, see you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I'm smack\n"
	.string "in the middle of the Goldenrod\l"
	.string "Marathon!\p"
	.string "I'm really falling behind everyone\n"
	.string "right now!\p"
	.string "All of my training is failing me!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I'm getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37::
	.string "Heya, it's {STR_VAR_1}.\n"
	.string "You know what?\p"
	.string "I used to be really unhealthy\n"
	.string "before I started training, but look\l"
	.string "at me now!\p"
	.string "I'm about to compete in the\n"
	.string "Goldenrod Marathon!\p"
	.string "Who would have thought?\p"
	.string "That's all, see you!$"

MatchCall_PersonalizedText38::
	.string "Lap number... Uh... 112?\p"
	.string "No that isn't right at all!\p"
	.string "{PLAYER}, this is {STR_VAR_1}.\p"
	.string "Aw man, I forgot what I was going\n"
	.string "to tell you.\p"
	.string "Just pretend I had something cool\n"
	.string "to share with you.\p"
	.string "Maybe I'll remember next time!$"

MatchCall_PersonalizedText39::
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Treading water in one place may not\n"
	.string "look like much work, but it's\l"
	.string "actually a pretty good workout!\p"
	.string "Now, battling while treading water\n"
	.string "is an even better workout!\p"
	.string "Talk to you later.$"

MatchCall_PersonalizedText40::
	.string "Hello there, this is {STR_VAR_1}.\p"
	.string "You know, I just can't figure out\n"
	.string "why people live in cold areas.\p"
	.string "I mean, the beach, and this\n"
	.string "tropical water is so lovely!\p"
	.string "I don't think I could ever leave!\p"
	.string "Sorry for the random call, that's\n"
	.string "all I wanted to say. Bye!$"

MatchCall_PersonalizedText41::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know, Master LEE back in\n"
	.string "Cianwood City may be a tough\l"
	.string "sensei, but he really wants us all\l"
	.string "to succeed.\p"
	.string "One day, I will finish my training\n"
	.string "in Mt. Mortar, and return to the\l"
	.string "dojo.\p"
	.string "Until then, I will get stronger.\p"
	.string "Goodbye, {PLAYER}.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here...\p"
	.string "You know, my psychic visions have\n"
	.string "never led me astray, but I'm\l"
	.string "beginning to doubt myself.\p"
	.string "My vision of defeating the POKéMON\n"
	.string "League is still clear in my mind,\l"
	.string "but I just don't see how it's\l"
	.string "possible.\p"
	.string "Do you think I could be having\n"
	.string "visions from someone else's point\l"
	.string "of view?\p"
	.string "I'll stop bugging you now, see ya!$"

MatchCall_PersonalizedText43::
	.string "This is {STR_VAR_1}.\p"
	.string "Striking from behind a tree only\n"
	.string "seems to work if I'm standing on\l"
	.string "the correct side of the tree.\p"
	.string "Too many people have been\n"
	.string "approaching me from behind, and\l"
	.string "scaring me instead.\p"
	.string "I'm supposed to be the ninja!\p"
	.string "I must continue honing my\n"
	.string "concealment techniques...\p"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "{PLAYER}, {PLAYER}!\n"
	.string "It's finally happened!\p"
	.string "This is {STR_VAR_1}, by the way.\p"
	.string "So, I was throwing coins into the\n"
	.string "fountain in the National Park, and\l"
	.string "one of my wishes actually came\l"
	.string "true!\p"
	.string "I wished for ¥5,000, and actually\n"
	.string "found that exact amount right here\l"
	.string "in the fountain!\p"
	.string "Wishes really can come true!\p"
	.string "Bye now!$"

MatchCall_PersonalizedText45::
	.string "Good day, this is {STR_VAR_1}.\p"
	.string "Have you become the POKéMON League\n"
	.string "Champion yet?\p"
	.string "...\p"
	.string "I see...\p"
	.string "From the moment I saw you, I could\n"
	.string "tell there's something special\l"
	.string "about you...\p"
	.string "Keep at it, {PLAYER}!$"

MatchCall_PersonalizedText46::
	.string "Hey, it's {STR_VAR_1}.\p"
	.string "Although it can be pretty dangerous\n"
	.string "here, I love swimming close to the\l"
	.string "whirlpools around the Whirl\l"
	.string "Islands.\p"
	.string "It's just so much fun!\p"
	.string "Ok, I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Hello {PLAYER}, {STR_VAR_1} here.\p"
	.string "I'm still bound and determined to\n"
	.string "have a picnic here on Mt. Rage, but\l"
	.string "some snow just got into my boots!\p"
	.string "It's so cold on my ankles, and now\n"
	.string "my socks are all wet!\p"
	.string "This really is awful!\p"
	.string "Ok, until next time! Bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, this is {STR_VAR_1}!\p"
	.string "I'm raising POKéMON with FAYE!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "Just wanted to share a good\n"
	.string "fishing spot with you.\p"
	.string "Did you know you can find wild\n"
	.string "Staryu by using a Good Rod in\l"
	.string "Cherrygrove City?\p"
	.string "...\p"
	.string "Oh, you're from Cherrygrove?\p"
	.string "Well, you probably already knew\n"
	.string "that, then.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "It's {STR_VAR_1}.\n"
	.string "I'm still stuck out on the frozen\l"
	.string "lake at Rage Resort.\p"
	.string "Have you called for help yet?\p"
	.string "Nobody has shown up to save me yet.\p"
	.string "I'll be waiting here I guess...$"

MatchCall_PersonalizedText51::
	.string "Hey, it's {STR_VAR_1}.\n"
	.string "Have you been raising your POKéMON\l"
	.string "well?\p"
	.string "You know, the daycare will help\n"
	.string "raise up to two of your POKéMON.\p"
	.string "They will continue growing levels,\n"
	.string "but don't have to take up one of\l"
	.string "your party slots.\p"
	.string "That's all, take care now.$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I'm still worried about my\n"
	.string "Azumarill in the daycare.\p"
	.string "It's all by itself, and not\n"
	.string "mingling with the other POKéMON.\p"
	.string "I wonder why it isn't getting along\n"
	.string "well with them...\p"
	.string "I guess I'll let you go now though.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "Humph, {STR_VAR_1} here.\p"
	.string "A group of whippersnappers tried\n"
	.string "taking advantage of this old man,\l"
	.string "but I gave them what for!\p"
	.string "I don't think they'll be causing\n"
	.string "any more problems now!\p"
	.string "We'll talk later. Goodbye for now.$"

MatchCall_PersonalizedText54::
	.string "It's {STR_VAR_1}...\p"
	.string "So, do you believe in curses, and\n"
	.string "evil spirits yet?\p"
	.string "...\p"
	.string "I believe a vengeful spirit still\n"
	.string "haunts the POKéMON League!\p"
	.string "...\p"
	.string "Just watch yourself, {PLAYER}.$"

MatchCall_PersonalizedText55::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of TRAINERS every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "Hey, have you heard of the\n"
	.string "protector of Ilex Forest?\p"
	.string "I hope I get the chance to see this\n"
	.string "mysterious POKéMON someday...\p"
	.string "That would be magical!\p"
	.string "That's all, see you!$"

MatchCall_PersonalizedText57::
	.string "Howdy! It's {STR_VAR_1}!\p"
	.string "Have you changed your mind about\n"
	.string "workin' on the farm?\p"
	.string "...\p"
	.string "No? Well let me know if you ever\n"
	.string "change your mind!\p"
	.string "We could sure use the extra help!\p"
	.string "Haha!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "Kiyah! This is {STR_VAR_1}!\p"
	.string "I'm still training barefoot in the\n"
	.string "snow!\p"
	.string "I wasn't able to feel my feet, but\n"
	.string "now they feel like they're burning!\p"
	.string "This must mean that Master LEE's\n"
	.string "special training techniques are\l"
	.string "working!\p"
	.string "I'll keep you updated, later!$"

MatchCall_PersonalizedText60::
	.string "This is {STR_VAR_1}.\p"
	.string "It's a pleasure to chat with\n"
	.string "a young TRAINER like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy POKéMON whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your POKéMON now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "My little brother sure has been\n"
	.string "getting a lot of experience lately.\p"
	.string "He still has a ways to go before\n"
	.string "he's up to our level though!\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here!\n"
	.string "Just calling to remind you about\l"
	.string "the greatness of hiking!\p"
	.string "Hiking is great exercise, and it's\n"
	.string "a good way to get out and interact\l"
	.string "with nature!\p"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Kiyah! It's {STR_VAR_1}!\p"
	.string "I'm not quite up to meditating\n"
	.string "underneath a waterfall yet, but I\l"
	.string "figure meditating in the rain is\l"
	.string "a good substitute for now.\p"
	.string "I'll get there one day!$"

MatchCall_PersonalizedText64::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five TRAINERS again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my POKéMON more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my POKéMON, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare POKéMON lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my POKéMON like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my POKéMON and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my POKéMON, too!$"

MatchCall_BattlePyramidText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare POKéMON\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "MOM: How are you sweetie?\p"
	.string "That SHANE hasn't been picking on\n"
	.string "you again, has he?\p"
	.string "Azurill and I will have something\n"
	.string "to say about that!\p"
	.string "Right, Azurill!?\p"
	.string "Ok, call me if you ever need\n"
	.string "anything, and don't forget to visit\l"
	.string "every once in a while.$"

MatchCall_Text_Mom2::
	.string "MOM: How are you sweetie?\p"
	.string "...\p"
	.string "What's that?\p"
	.string "...\p"
	.string "Time travel?\p"
	.string "You kids sure do have wild\n"
	.string "imaginations!$"

MatchCall_Text_Mom3::
	.string "MOM: You saw a live Thunderbolts\n"
	.string "concert?\p"
	.string "That sounds like fun!\p"
	.string "I hope SHANE got to watch them too.\p"
	.string "The Thunderbolts are his favorite\n"
	.string "band, you know!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the POKéMON LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the POKéMON LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the POKéMON LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_May9::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a POKéMON move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15::
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, POKéMON can do anything!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "POKéDEX successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1::
	.string "OLIVER: Oh, hey {PLAYER}{KUN}!\p"
	.string "Thanks again for bringing me my\n"
	.string "notebook.\p"
	.string "I still haven't discovered anything\n"
	.string "useful in these catacombs yet, but\l"
	.string "I will keep researching!$"

MatchCall_Text_Scott2::
	.string "OLIVER: Oh, hey {PLAYER}.\p"
	.string "Ack! Sorry!\p"
	.string "This isn't really a good time for\n"
	.string "me.\p"
	.string "Can I call you back later?$"

MatchCall_Text_Scott3::
	.string "OLIVER: Yo, {PLAYER}{KUN}!\p"
	.string "I'm actually in Cianwood City right\n"
	.string "now, trying to get a closer look at\l"
	.string "the Whirl Islands.\p"
	.string "Unfortunately, they don't seem to\n"
	.string "be very accessible.$"

MatchCall_Text_Scott4::
	.string "OLIVER: {PLAYER}! {PLAYER}!\p"
	.string "You should get to Kizu Forest as\n"
	.string "soon as you can!\p"
	.string "This shrine looks exactly like the\n"
	.string "one in Ilex Forest!\p"
	.string "It can't just be a coincidence!$"

MatchCall_Text_Scott5::
	.string "OLIVER: Ack! I'm sorry, {PLAYER}!\p"
	.string "I can't believe PROF. THORNE was\n"
	.string "part of some weird evil group.\p"
	.string "I'm such an idiot!\p"
	.string "I'll make it up to you someday, I\n"
	.string "swear it!$"

MatchCall_Text_Scott6::
	.string "OLIVER: Hey, {PLAYER}!\p"
	.string "I called in some backup to help\n"
	.string "you out.\p"
	.string "Did they get there yet?$"

MatchCall_Text_Scott7::
	.string "OLIVER: {PLAYER}?\p"
	.string "I heard about how you summoned\n"
	.string "Lugia to calm Ho-oh's rampage!\p"
	.string "I'm so jealous of you!\p"
	.string "Those are my two favorite\n"
	.string "legendary POKéMON!$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "DAD must be busy right now…$"

MatchCall_Text_Steven2::
	.string "DAD: Hey, {PLAYER}{KUN}!\p"
	.string "I'm here with SHANE in Lazulan\n"
	.string "City, waiting for the festival.\p"
	.string "You'd better hurry up and get over\n"
	.string "here, they're already setting up.$"

MatchCall_Text_Steven3::
	.string "DAD: Hey, {PLAYER}{KUN}!\p"
	.string "I've just been catching up with\n"
	.string "GOLD before the festival starts.\p"
	.string "Feel free to explore around the\n"
	.string "islands.$"

MatchCall_Text_Steven4::
	.string "DAD: Oh, hey {PLAYER}!\p"
	.string "They sure have some good deals at\n"
	.string "the festival tents.\p"
	.string "You can even buy Rare Candy here!$"

MatchCall_Text_Steven5::
	.string "DAD: {PLAYER}, what's up?\p"
	.string "I've just been at home catching\n"
	.string "up with MOM.\p"
	.string "I think she's a little mad at me\n"
	.string "for being gone so long.\p"
	.string "Good talking to you though, later!$"

MatchCall_Text_Steven6::
	.string "MOM: Oh, {PLAYER}, you say you got\n"
	.string "to see your father?\p"
	.string "That's wonderful!\p"
	.string "I know work always keeps him busy,\n"
	.string "but I really miss having him home.$"

MatchCall_Text_Steven7::
	.string "MOM: It's so nice having your\n"
	.string "father home again after so long!\p"
	.string "I was starting to get lonely at\n"
	.string "home all by myself.$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your POKéNAV's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your POKéDEX even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered PROF. BIRCH\n"
	.string "in the POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the POKéDEX and POKéNAV, studying\l"
	.string "POKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "SHANE: {PLAYER}?\p"
	.string "Why are you calling me?\p"
	.string "What, are you still butthurt about\n"
	.string "my POKéMON stomping yours?\p"
	.string "I was just messing with you, get\n"
	.string "over it nerd!$"

MatchCall_Text_MrStone2::
	.string "SHANE: What do you want now,\n"
	.string "{PLAYER}?\p"
	.string "I'm still mad about you ratting me\n"
	.string "out to MOM, you know!\p"
	.string "You'd better hope I'm in a better\n"
	.string "mood the next time we meet.\p"
	.string "Later, loser!$"

MatchCall_Text_MrStone3::
	.string "SHANE: Oh god, why are you calling\n"
	.string "me {PLAYER}?\p"
	.string "I'm in a good mood right now, don't\n"
	.string "ruin it for me.\p"
	.string "Loser.$"

MatchCall_Text_MrStone4::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SHANE appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_MrStone5::
	.string "SHANE: What, are you calling me\n"
	.string "just to gloat?\p"
	.string "Pfft, I told you I could have\n"
	.string "broken out of that holding cell\l"
	.string "myself.\p"
	.string "Just shut up about it!$"

MatchCall_Text_MrStone6::
	.string "SHANE: Oh, what, are you calling to\n"
	.string "offer me battling tips because you\l"
	.string "think you're so good now?\p"
	.string "Just you wait, I'll beat you, DAD,\n"
	.string "and those Team Chicken jerks!$"

MatchCall_Text_MrStone7::
	.string "SHANE: {PLAYER}?\p"
	.string "Look, you can help DAD with that\n"
	.string "Ho-oh crap.\p"
	.string "I've got better things to do.$"

MatchCall_Text_MrStone8::
	.string "SHANE: What now, {PLAYER}?\p"
	.string "While you were screwing around with\n"
	.string "DAD, I was training!\p"
	.string "I'm almost ready to take on the\n"
	.string "POKéMON League now!$"

MatchCall_Text_MrStone9::
	.string "SHANE: What? About what I said\n"
	.string "before?\p"
	.string "Don't be weird about it, just don't\n"
	.string "lose to DAD.\p"
	.string "Got it?$"

MatchCall_Text_MrStone10::
	.string "SHANE: What now {PLAYER}?\p"
	.string "You think I seem happier now that\n"
	.string "DAD left the POKéMON League?\p"
	.string "Well, maybe I am...\n"
	.string "Just shut up about it!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"
