MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "If you become round enough, you'll able\n"
	.string "to get around by simply rolling.\p"
	.string "It totally beats walking!\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Yo! Have you heard of the move Fury\n"
	.string "Cutter?\p"
	.string "It starts off pretty weak, but gains\n"
	.string "power when used consecutively!\p"
	.string "It's an awesome BUG-type move!\p"
	.string "Don't believe me?\p"
	.string "Here, I'll teach it to one of your\n"
	.string "POKéMON for free!\p"
	.string "So how about it?\p"
	.string "Want me to teach one of your POKéMON\n"
	.string "the move Fury Cutter?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "That's fine.\p"
	.string "Well, you know where to find me if you\n"
	.string "ever change your mind.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Awesome!\n"
	.string "So, which POKéMON I should teach?$"

MoveTutor_Text_FuryCutterTaught:
	.string "I bet you're catching the BUG-type bug\n"
	.string "now.\p"
	.string "Soon, you'll be wearing a straw hat like\n"
	.string "mine!$"

MoveTutor_MimicTeach:
	.string "What am I doing you ask?\p"
	.string "I'm mimicking you, of course\p"
	.string "It's pretty fun, would you like me to\n"
	.string "teach it to one of your POKéMON?$"

MoveTutor_MimicDeclined:
	.string "Aw, you're no fun!$"

MoveTutor_Text_MimicWhichMon:
	.string "I knew you were fun!\p"
	.string "So, which POKéMON should I teach the\n"
	.string "move Mimic to?$"

MoveTutor_Text_MimicTaught:
	.string "You know which POKéMON is the best at\n"
	.string "mimicry?\p"
	.string "That's right, Ditto!\p"
	.string "Ditto is my favorite POKéMON!$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "...\p"
	.string "...No, I don't want anymore...\p"
	.string "...I've had enough!\p"
	.string "...Khuh!\p"
	.string "Ah! Sorry, I must have been talking in\n"
	.string "my sleep.\p"
	.string "If you want, I can teach one of your\n"
	.string "POKéMON how to do the same.\p"
	.string "Are you interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Well, if you ever change your mind, I'll\n"
	.string "be here napping...$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an avid napper!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "...\p"
	.string "...Huh, no...I...\p"
	.string "...Yeah...$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Yo kid, do you want me to teach one of\n"
	.string "your POKéMON the move Double-Edge?\l"
	.string "I'm too lazy to make a pun about it.$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Nah, that's cool.\p"
	.string "Teaching moves is a lot of work anyway.$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Sweet! And which POKéMON should I\n"
	.string "teach Double-Edge to?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Double-Edge deals a lot of damage, but\n"
	.string "also hits with a recoil.\p"
	.string "You'll have to keep an eye on your own\n"
	.string "POKéMON's health.$"

MoveTutor_Text_ExplosionTeach:
	.string "The art of POKéMON battling is an\n"
	.string "Explosion!\p"
	.string "Wouldn't you agree?\p"
	.string "Say, if you want, I can teach one of\n"
	.string "your POKéMON the move Explosion!\p"
	.string "Free of charge!\p"
	.string "What do you say?$"

MoveTutor_Text_ExplosionDeclined:
	.string "Some people just don't appreciate the\n"
	.string "absolute perfection that is Explosion.$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Yes! I could tell you are someone who\n"
	.string "appreciates the absolute perfection\l"
	.string "that is Explosion!\p"
	.string "So, which POKéMON shall I teach?$"

MoveTutor_Text_ExplosionTaught:
	.string "This world would be a much better place\n"
	.string "if more people were Explosion\l"
	.string "connoisseurs such as us!$"
