MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "If you become round enough, you'll able\n"
	.string "to get around by simply rolling.\p"
	.string "It totally beats walking!\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Yo! Have you heard of the move Fury\n"
	.string "Cutter?\p"
	.string "It starts off pretty weak, but gains\n"
	.string "power when used consecutively!\p"
	.string "It's an awesome BUG-type move!\p"
	.string "Don't believe me?\p"
	.string "Here, I'll teach it to one of your\n"
	.string "POKéMON for free!\p"
	.string "So how about it?\p"
	.string "Want me to teach one of your POKéMON\n"
	.string "the move Fury Cutter?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "That's fine.\p"
	.string "Well, you know where to find me if you\n"
	.string "ever change your mind.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Awesome!\n"
	.string "So, which POKéMON I should teach?$"

MoveTutor_Text_FuryCutterTaught:
	.string "I bet you're catching the BUG-type bug\n"
	.string "now.\p"
	.string "Soon, you'll be wearing a straw hat like\n"
	.string "mine!$"

MoveTutor_MimicTeach:
	.string "What am I doing you ask?\p"
	.string "I'm mimicking you, of course\p"
	.string "It's pretty fun, would you like me to\n"
	.string "teach it to one of your POKéMON?$"

MoveTutor_MimicDeclined:
	.string "Aw, you're no fun!$"

MoveTutor_Text_MimicWhichMon:
	.string "I knew you were fun!\p"
	.string "So, which POKéMON should I teach the\n"
	.string "move Mimic to?$"

MoveTutor_Text_MimicTaught:
	.string "You know which POKéMON is the best at\n"
	.string "mimicry?\p"
	.string "That's right, Ditto!\p"
	.string "Ditto is my favorite POKéMON!$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "...\p"
	.string "...No, I don't want anymore...\p"
	.string "...I've had enough!\p"
	.string "...Khuh!\p"
	.string "Ah! Sorry, I must have been talking in\n"
	.string "my sleep.\p"
	.string "If you want, I can teach one of your\n"
	.string "POKéMON how to do the same.\p"
	.string "Are you interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Well, if you ever change your mind, I'll\n"
	.string "be here napping...$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an avid napper!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "...\p"
	.string "...Huh, no...I...\p"
	.string "...Yeah...$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
