Route102_Text_CalvinIntro:
	.string "Stop right there!\p"
	.string "I've locked eyes with you, that means\n"
	.string "we must have a POKéMON battle, there is\l"
	.string "no way around it!$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, I lost…\n"
	.string "I should have trained mine more…$"

Route102_Text_CalvinPostBattle:
	.string "Yes, you do seem strong. You may be\n"
	.string "worthy enough to be my rival.$"

Route102_Text_CalvinRegister:
	.string "I've been working hard at this since\n"
	.string "I saw you before, my rival.\p"
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, I lost…\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you're going to get stronger,\n"
	.string "I'll get stronger too, my rival.$"

Route102_Text_AllenIntro:
	.string "Did you just become a TRAINER?\n"
	.string "I can totally beat a kid like you!$"

Route102_Text_AllenDefeated:
	.string "I called you out because I thought\n"
	.string "I could beat you…$"

Route102_Text_AllenPostBattle:
	.string "I haven't won once yet…\n"
	.string "I wish I would win soon…$"

Route102_Text_RickIntro:
	.string "You don't like bugs?\n"
	.string "Well that's too bad, because I love\l"
	.string "bugs!$"

Route102_Text_RickDefeated:
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:
	.string "You should have known better than to\n"
	.string "walk in front of me, I will defeat you\l"
	.string "now!$"

Route102_Text_TianaDefeated:
	.string "How could I lose…$"

Route102_Text_TianaPostBattle:
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Were you drawn in by my sweet aroma?$"

Route103_Text_DaisyDefeated:
	.string "I should've tried a different\n"
	.string "fragrance.$"

Route103_Text_DaisyPostBattle:
	.string "Different aromas can affect your\n"
	.string "mental state, some can put your mind at\l"
	.string "ease.$"

Route103_Text_AmyIntro:
	.string "MAY: FAYE, FAYE, this TRAINER looks\n"
	.string "strong!$"

Route103_Text_AmyDefeated:
	.string "MAY: Oh no, FAYE, we lost!$"

Route103_Text_AmyPostBattle:
	.string "MAY: FAYE and I do everything together,\n"
	.string "we are inseparable!$"

Route103_Text_AmyNotEnoughPokemon:
	.string "MAY: FAYE, FAYE, this TRAINER doesn't\n"
	.string "have enough POKéMON to battle us.\p"
	.string "How unfortunate.$"

Route103_Text_LivIntro:
	.string "FAYE: MAY, MAY, this TRAINER looks\n"
	.string "strong!$"

Route103_Text_LivDefeated:
	.string "FAYE: Oh no, MAY, we lost!$"

Route103_Text_LivPostBattle:
	.string "FAYE: MAY and I do everything together,\n"
	.string "we are inseparable!$"

Route103_Text_AmyLivRegister:
	.string "MAY: FAYE, FAYE, let's register this\n"
	.string "TRAINER...$"

Route103_Text_LivNotEnoughPokemon:
	.string "FAYE: MAY, MAY, this TRAINER doesn't\n"
	.string "have enough POKéMON to battle us.\p"
	.string "How unfortunate.$"

Route103_Text_AmyRematchIntro:
	.string "MAY: FAYE, FAYE, this TRAINER came back\n"
	.string "for a rematch!$"

Route103_Text_AmyRematchDefeated:
	.string "MAY: Oh no, FAYE, we lost again!$"

Route103_Text_AmyRematchPostBattle:
	.string "MAY: FAYE and I do everything together,\n"
	.string "we are inseparable!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "MAY: FAYE, FAYE, this TRAINER doesn't\n"
	.string "have enough POKéMON to battle us.\p"
	.string "How unfortunate.$"

Route103_Text_LivRematchIntro:
	.string "FAYE: MAY, MAY, this TRAINER came back\n"
	.string "for a rematch!$"

Route103_Text_LivRematchDefeated:
	.string "FAYE: Oh no, MAY, we lost again!$"

Route103_Text_LivRematchPostBattle:
	.string "FAYE: MAY and I do everything together,\n"
	.string "we are inseparable!$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "FAYE: MAY, MAY, this TRAINER doesn't\n"
	.string "have enough POKéMON to battle us.\p"
	.string "How unfortunate.$"

Route103_Text_AndrewIntro:
	.string "Do you know where the secret fishing\n"
	.string "spot is...?$"

Route103_Text_AndrewDefeated:
	.string "If you didn't know, just say so!$"

Route103_Text_AndrewPostBattle:
	.string "I heard about a secret fishing spot\n"
	.string "somewhere around here that has\l"
	.string "DRAGONS, where could it be?$"

Route103_Text_MiguelIntro:
	.string "Go, my beautiful POKéMON!$"

Route103_Text_MiguelDefeated:
	.string "You didn't have to be so mean to her...$"

Route103_Text_MiguelPostBattle:
	.string "My Jynx is the most beautiful POKéMON\n"
	.string "around, and you won't convince me\l"
	.string "otherwise!$"

Route103_Text_MiguelRegister:
	.string "I'll get you to come out and look in\n"
	.string "on my delightful POKéMON again!$"

Route103_Text_MiguelRematchIntro:
	.string "Let me show you how much more beautiful\n"
	.string "my Jynx has become!$"

Route103_Text_MiguelRematchDefeated:
	.string "You're still so mean to her.\n"
	.string "Just let her have this win.$"

Route103_Text_MiguelRematchPostBattle:
	.string "My Jynx is the most beautiful POKéMON\n"
	.string "around, and you won't convince me\l"
	.string "otherwise!$"

Route103_Text_PeteIntro:
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_PeteDefeated:
	.string "Oh, that's good going!$"

Route103_Text_PetePostBattle:
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I'd want to SURF on it, too!$"

Route103_Text_IsabelleIntro:
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_IsabelleDefeated:
	.string "Groan…$"

Route103_Text_IsabellePostBattle:
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro:
	.string "Kiyah!$"

Route103_Text_RhettDefeated:
	.string "Sorry, I thought you were someone\n"
	.string "else...$"

Route103_Text_RhettPostBattle:
	.string "You should be more careful, I almost\n"
	.string "kicked you in the neck when you walked\l"
	.string "around that tree.$"

Route103_Text_MarcosIntro:
	.string "Let me play you the songs of my people!$"

Route103_Text_MarcosDefeated:
	.string "You have offended my people!$"

Route103_Text_MarcosPostBattle:
	.string "My people only know one sound, and that\n"
	.string "is rock!$"

Route104_Text_GinaIntro:
	.string "TINA: Are you prepared for a double\n"
	.string "battle?$"

Route104_Text_GinaDefeat:
	.string "TINA: Losing upsets me!$"

Route104_Text_GinaPostBattle:
	.string "TINA: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_GinaNotEnoughMons:
	.string "TINA: Oh, it looks like you aren't\n"
	.string "prepared for a double battle.\p"
	.string "You will need more than one POKéMON.$"

Route104_Text_MiaIntro:
	.string "MAI: Us twins do everything\n"
	.string "together, even POKéMON battles!$"

Route104_Text_MiaDefeat:
	.string "MAI: We battled together, but we\n"
	.string "both lost…$"

Route104_Text_MiaPostBattle:
	.string "MAI: We will train our POKéMON more\n"
	.string "and be strong like you.$"

Route104_Text_MiaNotEnoughMons:
	.string "MAI: Sorry, but you will have to bring\n"
	.string "more POKéMON if you want to battle us.$"

Route104_Text_IvanIntro:
	.string "I'm one of the best fishermen around.\p"
	.string "What?\p"
	.string "You don't believe me?$"

Route104_Text_IvanDefeat:
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON…$"

Route104_Text_BillyIntro:
	.string "Hey, you look like a weakling!\p"
	.string "This will be easy.$"

Route104_Text_BillyDefeat:
	.string "You should have told me you weren't a\n"
	.string "weakling.$"

Route104_Text_BillyPostBattle:
	.string "I'm looking for weak TRAINERS to battle\n"
	.string "to practice on.$"

Route104_Text_HaleyIntro:
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will battle!$"

Route104_Text_HaleyDefeat:
	.string "I shouldn't have battled…$"

Route104_Text_HaleyPostBattle:
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for you,\l"
	.string "you will regret it, however things\l"
	.string "turn out.$"

Route104_Text_HaleyRegister1:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRegister2:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_HaleyPostRematch:
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro:
	.string "Oh, sure, I'll accept your challenge.\n"
	.string "You don't look very tough to me.$"

Route104_Text_WinstonDefeat:
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostBattle:
	.string "You're tougher than you look, but can\n"
	.string "you survive camping in Mt. Mortar?$"

Route104_Text_WinstonRegister1:
	.string "...\p"
	.string "What's that?\p"
	.string "You want to register me in your\n"
	.string "POKéNAV?$"

Route104_Text_WinstonRegister2:
	.string "...\p"
	.string "What's that?\p"
	.string "You want to register me in your\n"
	.string "POKéNAV?$"

Route104_Text_WinstonRematchIntro:
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch:
	.string "You're tougher than you look, but can\n"
	.string "you survive camping in Mt. Silver?$"

Route104_Text_CindyIntro:
	.string "Maybe you can satisfy my need for a\n"
	.string "strong opponent, my boyfriend never\l"
	.string "puts up much of a challenge.$"

Route104_Text_CindyDefeat:
	.string "Oh, my!$"

Route104_Text_CindyPostBattle:
	.string "You sure know how to please a woman.$"

Route104_Text_CindyRegister1:
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "That was so much fun!\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hello, we meet again.\n"
	.string "Will you satisfy my needs this time?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, my…\n"
	.string "Consider me satisfied…$"

Route104_Text_CindyPostRematch:
	.string "That was fun, we should do this again\n"
	.string "sometime.$"

Route104_Text_DarianIntro:
	.string "You can fish up better POKéMON with\n"
	.string "better rods.\p"
	.string "Let me show you!$"

Route104_Text_DarianDefeat:
	.string "What the…$"

Route104_Text_DarianPostBattle:
	.string "I guess you had the better POKéMON.$"

Route105_Text_FosterIntro:
	.string "Are you headed to Mt. Mortar?\p"
	.string "It's my favorite mountain by far!$"

Route105_Text_FosterDefeated:
	.string "I should have concentrated more on our\n"
	.string "battle.$"

Route105_Text_FosterPostBattle:
	.string "I've heard Mt. Silver is also a nice\n"
	.string "mountain, but very few are allowed\l"
	.string "there.$"

Route105_Text_LuisIntro:
	.string "Hmph, I say, you look like you're\n"
	.string "prepared for a battle!$"

Route105_Text_LuisDefeated:
	.string "Quite prepared indeed...$"

Route105_Text_LuisPostBattle:
	.string "A gentleman such as myself only battles\n"
	.string "TRAINERS who appear well learned in\l"
	.string "the art of POKéMON battles.$"

Route105_Text_DominikIntro:
	.string "I'll show you the best POKéMON money\n"
	.string "can buy!$"

Route105_Text_DominikDefeated:
	.string "No, I paid so much for that Porygon!\n"
	.string "I want a refund.$"

Route105_Text_DominikPostBattle:
	.string "I tried to purchase the Dance Theater in\n"
	.string "Ecruteak, but they told me it's not for\l"
	.string "sale.\p"
	.string "The nerve of those people!$"

Route105_Text_BeverlyIntro:
	.string "Go, my adorable POKéMON!$"

Route105_Text_BeverlyDefeated:
	.string "I guess cuteness doesn't win POKéMON\n"
	.string "battles...$"

Route105_Text_PostBattle:
	.string "I was training up my cute little\n"
	.string "ELECTRIC-type POKéMON to take on\l"
	.string "WATARU, but it seems they aren't ready\l"
	.string "yet.$"

Route105_Text_ImaniIntro:
	.string "I was just out for a stroll, but I\n"
	.string "suppose I have time for a quick battle!$"

Route105_Text_ImaniDefeated:
	.string "Perhaps I should have chosen an easier\n"
	.string "opponent...$"

Route105_Text_ImaniPostBattle:
	.string "Have you been to the Dance Theater in\n"
	.string "Ecruteak?\p"
	.string "I wish I could be like those girls.$"

Route105_Text_AndresIntro:
	.string "Fwahahaha! Hiking is the best!$"

Route105_Text_AndresDefeated:
	.string "I'm a better hiker than a battler,\n"
	.string "trust me.$"

Route105_Text_AndresPostBattle:
	.string "I've hiked every mountain in Johto, now\n"
	.string "I have my sights set on Mt. Tempest in\l"
	.string "the Golden Islands...$"

Route105_Text_AndresRegister:
	.string "Register me in your POKéNAV so I can\n"
	.string "tell you all about the greatness of\l"
	.string "hiking later!$"

Route105_Text_AndresRematchIntro:
	.string "Have you found an appreciation for\n"
	.string "hiking yet?$"

Route105_Text_AndresRematchDefeated:
	.string "You're still a good battler I see.$"

Route105_Text_AndresRematchPostBattle:
	.string "Have you been to Mt. Tempest?\p"
	.string "I've heard very strong TRAINERS visit\n"
	.string "there.$"

Route105_Text_JosueIntro:
	.string "Birds are real, and I will prove it to\n"
	.string "you!$"

Route105_Text_JosueDefeated:
	.string "Are any of us real...?$"

Route105_Text_JosuePostBattle:
	.string "This could all be a simulation!\p"
	.string "Just look at that hiker, I haven't seen\n"
	.string "him blink once!$"

Route106_Text_ElliotIntro:
	.string "Which do you prefer, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_ElliotDefeated:
	.string "Like in deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_ElliotRegister:
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro:
	.string "I caught a bunch of POKéMON fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated:
	.string "I lost again spectacularly!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Win or lose, POKéMON are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro:
	.string "That guy over there is hogging the best\n"
	.string "fishing spot!$"

Route106_Text_NedDefeated:
	.string "I lost out on the good fishing spot and\n"
	.string "this battle.$"

Route106_Text_NedPostBattle:
	.string "Maybe that other fisherman will leave\n"
	.string "soon, and I can have my spot back.$"

Route106_Text_DouglasIntro:
	.string "My super BUG POKéMON will have you\n"
	.string "begging for mercy!$"

Route106_Text_DouglasDefeated:
	.string "I give up!$"

Route106_Text_DouglasPostBattle:
	.string "I wouldn't lose in a bug catching\n"
	.string "contest.$"

Route106_Text_KylaIntro:
	.string "Ick! I hate bugs!\p"
	.string "That's almost all that's in this grass.$"

Route106_Text_KylaDefeated:
	.string "Squashed, like a bug.$"

Route106_Text_KylaPostBattle:
	.string "There's a bug catcher over by the DARK\n"
	.string "CAVE entrance, bug catchers give me\l"
	.string "the creeps.$"

Route107_Text_DarrinIntro:
	.string "Did you come here from Goldenrod City?\p"
	.string "I will show you the power of a true\n"
	.string "POKéMON fan!$"

Route107_Text_DarrinDefeated:
	.string "Oh, you must be a bigger POKéMON fan\n"
	.string "than I am.$"

Route107_Text_DarrinPostBattle:
	.string "Have you been to the POKéMON Fan Club\n"
	.string "in Goldenrod City?$"

Route107_Text_TonyIntro:
	.string "I'll show you the awesome BUG-type\n"
	.string "POKéMON I just caught!$"

Route107_Text_TonyDefeated:
	.string "Maybe I should train my Pinsir before\n"
	.string "battling with it.$"

Route107_Text_TonyPostBattle:
	.string "Have you been into the National Park\n"
	.string "yet?\p"
	.string "They have all kinds of awesome\n"
	.string "BUG-type POKéMON!$"

Route107_Text_TonyRegister:
	.string "Here, register me in your POKéNAV so I\n"
	.string "can tell you more about what makes\l"
	.string "BUGS awesome!$"

Route107_Text_TonyRematchIntro:
	.string "Let me show you how much my Pinsir has\n"
	.string "grown!$"

Route107_Text_TonyRematchDefeated:
	.string "I guess I haven't grown my Pinsir\n"
	.string "enough yet...$"

Route107_Text_TonyRematchPostBattle:
	.string "Have you been into the National Park\n"
	.string "yet?\p"
	.string "They have all kinds of awesome\n"
	.string "BUG-type POKéMON!$"

Route107_Text_DeniseIntro:
	.string "Go! All of my cute babies!$"

Route107_Text_DeniseDefeated:
	.string "No! My babies!$"

Route107_Text_DenisePostBattle:
	.string "My babies like to come here and check\n"
	.string "out the weird tree.$"

Route107_Text_BethIntro:
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_BethDefeated:
	.string "I wasn't good enough for you.$"

Route107_Text_BethPostBattle:
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_LisaIntro:
	.string "LISA: Hey! You found our secret\n"
	.string "make-out spot!$"

Route107_Text_LisaDefeated:
	.string "LISA: Way to ruin the mood...$"

Route107_Text_LisaPostBattle:
	.string "LISA: Go find your own make-out spot.\p"
	.string "This one is taken.$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Only one POKéMON?\p"
	.string "That's pretty ballsy, but we always\n"
	.string "battle as a team.$"

Route107_Text_RayIntro:
	.string "RAY: Oh come on, read the room kid!$"

Route107_Text_RayDefeated:
	.string "RAY: My disappointment is immeasurable,\n"
	.string "and my day is ruined.$"

Route107_Text_RayPostBattle:
	.string "RAY: I found this nice secluded area to\n"
	.string "make-out with my girlfriend, but you\l"
	.string "just had to come along and ruin it.$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Just one POKéMON?\p"
	.string "You've got guts kid, now get out of\n"
	.string "here.$"

Route107_Text_CamronIntro:
	.string "I'm training for a huge triathlon, help\n"
	.string "me train my POKéMON too!$"

Route107_Text_CamronDefeated:
	.string "That exhausted me…$"

Route107_Text_CamronPostBattle:
	.string "My POKéMON might not be ready, but I\n"
	.string "think I am.$"

Route108_Text_JeromeIntro:
	.string "You didn't buy anything from that shady\n"
	.string "looking guy, did you?$"

Route108_Text_JeromeDefeated:
	.string "You rocked my world...$"

Route108_Text_JeromePostBattle:
	.string "I thought you would be an easy win\n"
	.string "since you fell for that shady guys\l"
	.string "sales pitch.$"

Route108_Text_MatthewIntro:
	.string "Take flight, my bird POKéMON!$"

Route108_Text_MatthewDefeated:
	.string "No!\n"
	.string "Knocked back down to earth!$"

Route108_Text_MatthewPostBattle:
	.string "Flight allows birds to experience\n"
	.string "freedom like no human can.$"

Route108_Text_TaraIntro:
	.string "It never stops raining on this route,\n"
	.string "it's so much fun!$"

Route108_Text_TaraDefeated:
	.string "Oh, boo!$"

Route108_Text_TaraPostBattle:
	.string "Have you been down into the Slowpoke\n"
	.string "Well?\p"
	.string "It's so damp and cozy.$"

Route108_Text_MissyIntro:
	.string "I'm out here training to reduce my\n"
	.string "stress!$"

Route108_Text_MissyDefeated:
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_MissyPostBattle:
	.string "Work off your stress by exercising!\n"
	.string "It's so healthy!$"

Route108_Text_CoryIntro:
	.string "Hiyah!\p"
	.string "I will show you the result of years of\n"
	.string "training!$"

Route108_Text_CoryDefeated:
	.string "Maybe the quality of one's training\n"
	.string "matters as well...$"

Route108_Text_CoryPostBattle:
	.string "It seems I need more quality training.$"

Route108_Text_CoryRegister:
	.string "I love tough TRAINERS,\n"
	.string "Register me in your POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Win or lose, I love battling!$"

Route108_Text_CoryRematchDefeated:
	.string "Defeated yet again...$"

Route108_Text_CoryRematchPostBattle:
	.string "It seems I need more quality training.$"

Route108_Text_CarolinaIntro:
	.string "I take huge pride in my cute POKéMON.\n"
	.string "We'll show you an adorable battle!$"

Route108_Text_CarolinaDefeated:
	.string "That wasn't cute at all.$"

Route108_Text_CarolinaPostBattle:
	.string "Cute POKéMON are my favorite, what kind\n"
	.string "is your favorite?$"

Route109_Text_DavidIntro:
	.string "I knew I heard someone sneaking around\n"
	.string "the corner!$"

Route109_Text_DavidDefeated:
	.string "I say, you certainly are a tough one.$"

Route109_Text_DavidPostBattle:
	.string "You can drop through the floor to\n"
	.string "descend the lighthouse faster, if your\l"
	.string "legs can handle the landing, that is.$"

Route109_Text_AliceIntro:
	.string "Yeehaw! Show me what you've got!$"

Route109_Text_AliceDefeated:
	.string "You're not too bad for a city slicker!$"

Route109_Text_AlicePostBattle:
	.string "Life on the farm can be more\n"
	.string "entertaining than you think!$"

Route109_Text_HueyIntro:
	.string "Me crewmates sailed off without me, now\n"
	.string "I'm mad!$"

Route109_Text_HueyDefeated:
	.string "That didn't help, now I'm even more\n"
	.string "angry!$"

Route109_Text_HueyPostBattle:
	.string "Maybe I'll go to the sweet shop in\n"
	.string "Olivine and cool my head.$"

Route109_Text_EdmondIntro:
	.string "I made it up one flight of stairs, but\n"
	.string "now I'm worn out!$"

Route109_Text_EdmondDefeated:
	.string "Wow, so rude.$"

Route109_Text_EdmondPostBattle:
	.string "I swear the brochure said this place\n"
	.string "had an elevator, what a ripoff!$"

Route109_Text_RickyIntro:
	.string "Headed to Olivine, are you?$"

Route109_Text_RickyDefeated:
	.string "Say, you're not half bad!$"

Route109_Text_RickyPostBattle:
	.string "Olivine has to be one of my favorite\n"
	.string "port towns, for sure.$"

Route109_Text_RickyRegister:
	.string "How about another match sometime?$"

Route109_Text_RickyRematchIntro:
	.string "You showed up at the perfect time, I\n"
	.string "was itching for another match!$"

Route109_Text_RickyRematchDefeated:
	.string "Good match, good match.$"

Route109_Text_RickyRematchPostBattle:
	.string "Olivine has to be one of my favorite\n"
	.string "port towns, by a long shot!$"

Route109_Text_LolaIntro:
	.string "Your hands aren't calloused at all!\p"
	.string "You wouldn't last 2 seconds on the\n"
	.string "farm!$"

Route109_Text_LolaDefeated:
	.string "No fair, your POKéMON did all the work\n"
	.string "for you!$"

Route109_Text_LolaPostBattle:
	.string "Farm life is tough, but I wouldn't trade\n"
	.string "it for the world!$"

Route109_Text_LolaRegister:
	.string "You may not be rugged, but your POKéMON\n"
	.string "sure are.\p"
	.string "I wouldn't mind battling you again\n"
	.string "sometime...$"

Route109_Text_LolaRematchIntro:
	.string "Hey! I think I'm starting to see little\n"
	.string "callouses forming on your hands!$"

Route109_Text_LolaRematchDefeated:
	.string "Your POKéMON sure are tough!$"

Route109_Text_LolaRematchPostBattle:
	.string "I'm going to put your POKéMON to work\n"
	.string "on the farm!$"

Route109_Text_AustinaIntro:
	.string "Saddle up partner!$"

Route109_Text_AustinaDefeated:
	.string "No! I fell off!$"

Route109_Text_AustinaPostBattle:
	.string "You know what they say, if you fall off\n"
	.string "your Ponyta, you've gotta get back on!$"

Route109_Text_GwenIntro:
	.string "A battle? Of course!\p"
	.string "Allow me to show off my lovely POKéMON!$"

Route109_Text_GwenDefeated:
	.string "I may have lost, but I would say my\n"
	.string "POKéMON won on cuteness.$"

Route109_Text_GwenPostBattle:
	.string "How do you choose your POKéMON?\p"
	.string "Cuteness is the most important factor\n"
	.string "for me.$"

Route109_Text_CarterIntro:
	.string "Aah! I broke my rod reeling in a big one!\p"
	.string "Now I'm going to take my anger out on\n"
	.string "you!$"

Route109_Text_CarterDefeated:
	.string "Broke my rod, and now my spirit...$"

Route109_Text_CarterPostBattle:
	.string "What do you want now?\p"
	.string "What else will you take from me?$"

Route109_Text_PaulIntro:
	.string "PAUL: Really kid? You want a battle now\n"
	.string "of all times?$"

Route109_Text_PaulDefeated:
	.string "PAUL: Well that's just great!$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Hey, uh, could you leave us alone\n"
	.string "now?$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Really kid? You want a battle now\n"
	.string "of all times?\p"
	.string "...\p"
	.string "You don't even have two POKéMON!\p"
	.string "Get lost!$"

Route109_Text_MelIntro:
	.string "MEL: I'll show you what true love is\n"
	.string "capable of!$"

Route109_Text_MelDefeated:
	.string "MEL: Oh no... Is our love not true?$"

Route109_Text_MelPostBattle:
	.string "MEL: PAUL is so possessive, but I love\n"
	.string "it!$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: I'll show you what true love is\n"
	.string "capable of!\p"
	.string "...\p"
	.string "When you bring more POKéMON that is...$"

Route109_Text_ChandlerIntro:
	.string "What's this behind your ear?\p"
	.string "A POKéBALL!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, ho!\n"
	.string "Too bad!$"

Route109_Text_ChandlerPostBattle:
	.string "Some people just don't appreciate the\n"
	.string "wonders of magic.$"

Route109_Text_HaileyIntro:
	.string "I'll show you what it means to be farm\n"
	.string "tough!$"

Route109_Text_HaileyDefeated:
	.string "How could this happen?$"

Route109_Text_HaileyPostBattle:
	.string "Farm life toughens a person up, y'all\n"
	.string "city folk just don't get it.$"

Route109_Text_ElijahIntro:
	.string "Let me show you what it means to rock!$"

Route109_Text_ElijahDefeated:
	.string "I got rolled!$"

Route109_Text_ElijahPostBattle:
	.string "One day, I hope to join The\n"
	.string "Thunderbolts, and play around the\l"
	.string "world!$"

Route110_Text_JacobIntro:
	.string "If you don't watch out for thin ice,\n"
	.string "you'll be in trouble!$"

Route110_Text_JacobDefeated:
	.string "You shattered my dreams just like thin\n"
	.string "ice!$"

Route110_Text_JacobPostBattle:
	.string "You know, I really haven't seen thin ice\n"
	.string "around here.\p"
	.string "Just patches of water.$"

Route110_Text_AnthonyIntro:
	.string "How are we snowboarding on the ice?\p"
	.string "Don't worry about it!$"

Route110_Text_AnthonyDefeated:
	.string "Spun out!$"

Route110_Text_AnthonyPostBattle:
	.string "I think somebody was just being lazy\n"
	.string "and didn't give us ice skates.$"

Route110_Text_BenjaminIntro:
	.string "You slid all the way out here?\p"
	.string "You must really want to battle me!$"

Route110_Text_BenjaminDefeated:
	.string "I see now why you wanted a battle,\n"
	.string "you're good.$"

Route110_Text_BenjaminPostBattle:
	.string "Although this lake is pretty big, you\n"
	.string "can't slide all the way across it in one\l"
	.string "go, unfortunately.$"

Route110_Text_BenjaminRegister:
	.string "Slide out here again sometime if you're\n"
	.string "ever really bored...$"

Route110_Text_BenjaminRematchIntro:
	.string "Hey! You caught me!\p"
	.string "Let's battle!$"

Route110_Text_BenjaminRematchDefeated:
	.string "I think you're even better than last\n"
	.string "time!$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Although this lake is pretty big, you\n"
	.string "can't slide all the way across it in one\l"
	.string "go, unfortunately.$"

Route110_Text_AbigailIntro:
	.string "The way we can stop you on the ice, you\n"
	.string "would think we have psychic powers!$"

Route110_Text_AbigailDefeated:
	.string "Too bad, I could have used some psychic\n"
	.string "powers for that battle.$"

Route110_Text_AbigailPostBattle:
	.string "What would you do if you had psychic\n"
	.string "powers?\p"
	.string "I would probably just use them to push\n"
	.string "myself around while skiing.$"

Route110_Text_AbigailRegister:
	.string "Let's have a rematch sometime, but next\n"
	.string "time, you stop me on the ice.$"

Route110_Text_AbigailRematchIntro:
	.string "Hey, you stopped me this time!$"

Route110_Text_AbigailRematchDefeated:
	.string "Maybe I should spend more time\n"
	.string "training, and less time skiing...$"

Route110_Text_AbigailRematchPostBattle:
	.string "What would you do if you had psychic\n"
	.string "powers?\p"
	.string "I would probably just use them to push\n"
	.string "myself around while skiing.$"

Route110_Text_JasmineIntro:
	.string "Thought you could just slide on past\n"
	.string "me?$"

Route110_Text_JasmineDefeated:
	.string "I should have just let you slide on by.$"

Route110_Text_JasminePostBattle:
	.string "Is it fun to slide across the lake like\n"
	.string "that?$"

Route110_Text_EdwardIntro:
	.string "Do you really have a membership here,\n"
	.string "you don't look like you could afford it!$"

Route110_Text_EdwardDefeated:
	.string "I didn't mean it!\n"
	.string "Please don't take my money!$"

Route110_Text_EdwardPostBattle:
	.string "I see, you must have built a fortune\n"
	.string "from defeating TRAINERS like myself.$"

Route110_Text_JaclynIntro:
	.string "Hmm... You look like fun!$"

Route110_Text_JaclynDefeated:
	.string "I was right!\n"
	.string "You're a pretty good TRAINER.$"

Route110_Text_JaclynPostBattle:
	.string "The resort is beautiful this time of\n"
	.string "year!\p"
	.string "I just had to take a stroll around the\n"
	.string "frozen lake.$"

Route110_Text_EdwinIntro:
	.string "Hey, don't stop me!\p"
	.string "I'm almost to the edge!$"

Route110_Text_EdwinDefeated:
	.string "I think I'm further out on the ice now!$"

Route110_Text_EdwinPostBattle:
	.string "Don't just stand there and stare at me,\n"
	.string "help!$"

Route110_Text_EdwinRegister:
	.string "Here's my number, please, just call for\n"
	.string "help!$"

Route110_Text_EdwinRematchIntro:
	.string "I think I'm almost back to the edge now!\p"
	.string "Don't stop me!$"

Route110_Text_EdwinRematchDefeated:
	.string "I think I'm further out on the ice now!$"

Route110_Text_EdwinRematchPostBattle:
	.string "Don't just stand there and stare at me,\n"
	.string "help!$"

Route110_Text_DaleIntro:
	.string "You here for some ice fishing too?$"

Route110_Text_DaleDefeated:
	.string "Hook, line, and sinker!$"

Route110_Text_DalePostBattle:
	.string "If you're serious about fishing, you\n"
	.string "should talk to my buddy.\p"
	.string "He's staying in one of the cabins.$"

Route110_Text_IsabelIntro:
	.string "I got bored of sitting in my cabin, let's\n"
	.string "battle!$"

Route110_Text_IsabelDefeated:
	.string "Defeat is better than cabin fever, I\n"
	.string "suppose.$"

Route110_Text_IsabelPostBattle:
	.string "Sitting in the cabin is boring, but it's\n"
	.string "too cold out here.\p"
	.string "I'm just not sure what to do!$"

Route110_Text_IsabelRegister:
	.string "If you're ever bored yourself, we could\n"
	.string "have another battle...$"

Route110_Text_IsabelRematchIntro:
	.string "I'm glad you showed up, I was starting\n"
	.string "to get bored again!$"

Route110_Text_IsabelRematchDefeated:
	.string "I really don't like to lose, but at least\n"
	.string "I'm not bored.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Sitting in the cabin is boring, but it's\n"
	.string "too cold out here.\p"
	.string "I'm just not sure what to do!$"

Route110_Text_TimmyIntro:
	.string "Care for a battle on the way to the ski\n"
	.string "lift?$"

Route110_Text_TimmyDefeated:
	.string "I was hoping to be uplifted, but was let\n"
	.string "down instead.$"

Route110_Text_TimmyPostBattle:
	.string "The ski lift will take you to the peak of\n"
	.string "Mt. Rage, certainly easier than climbing\l"
	.string "up!$"

Route110_Text_AlyssaIntro:
	.string "Sure, I always have time for a POKéMON\n"
	.string "battle!$"

Route110_Text_AlyssaDefeated:
	.string "Hmm... I don't have time for losing\n"
	.string "though...$"

Route110_Text_AlyssaPostBattle:
	.string "POKéMON battling on ice...\p"
	.string "Sounds like some weird theatre show.$"

Route110_Text_JosephIntro:
	.string "They need to put up warning signs, this\n"
	.string "ice is way too slippery!$"

Route110_Text_JosephDefeated:
	.string "My POKéMON aren't built for this cold\n"
	.string "weather.$"

Route110_Text_JosephPostBattle:
	.string "Would it kill them to put railing up\n"
	.string "around the edge of the lake too?$"

Route110_Text_KalebIntro:
	.string "Which do you like more, snow or POKéMON?$"

Route110_Text_KalebDefeated:
	.string "It seems you really like POKéMON.$"

Route110_Text_KalebPostBattle:
	.string "I would say I like POKéMON more than\n"
	.string "snow.\p"
	.string "Snow is overrated.$"

Route111_Text_DrewIntro:
	.string "Did you take a wrong turn?$"

Route111_Text_DrewDefeat:
	.string "Alrighty then, you just go wherever you\n"
	.string "want to, ok?$"

Route111_Text_DrewPostBattle:
	.string "I became a ranger because I love\n"
	.string "nature, but this is a little too much for\l"
	.string "me.$"

Route111_Text_HeidiIntro:
	.string "A group of hooded hoodlums are\n"
	.string "wandering around on this mountain.\p"
	.string "You're not with them, are you?$"

Route111_Text_HeidiDefeat:
	.string "Ok, I guess you're clear...$"

Route111_Text_HeidiPostBattle:
	.string "Hmm... You've met those hooded hoodlums\n"
	.string "before?\p"
	.string "I knew they were trouble.$"

Route111_Text_BeauIntro:
	.string "A dangerous mountain like this is no\n"
	.string "place for children!$"

Route111_Text_BeauDefeat:
	.string "Perhaps you are no ordinary child...$"

Route111_Text_BeauPostBattle:
	.string "I saw someone out here with an umbrella.\p"
	.string "Don't they know that could act as a\n"
	.string "lightning rod?$"

Route111_Text_BeckyIntro:
	.string "I think I went the wrong way...$"

Route111_Text_BeckyDefeat:
	.string "I'm really lost if I'm running across\n"
	.string "strong TRAINERS like you here.$"

Route111_Text_BeckyPostBattle:
	.string "I may be lost, but at least I know I can\n"
	.string "get back to Darkoal Town by just\l"
	.string "descending the mountain.$"

Route111_Text_DustyIntro:
	.string "Urwrah!\p"
	.string "I'm just too angry!$"

Route111_Text_DustyDefeat:
	.string "Ok, I've calmed down a little bit.$"

Route111_Text_DustyPostBattle:
	.string "I've calmed down now, but I still don't\n"
	.string "have my hiking stick.\p"
	.string "Why bother hiking this mountain without\n"
	.string "my stick?$"

Route111_Text_DustyRegister:
	.string "I came all the way to this mountain, but\n"
	.string "forgot my favorite hiking boots at\l"
	.string "home.\p"
	.string "I was just so upset with myself, but you\n"
	.string "calmed me down.\p"
	.string "Say why don't you register me in your\n"
	.string "POKéNAV in case I lose it again.$"

Route111_Text_DustyRematchIntro:
	.string "Graah! I'm mad again!$"

Route111_Text_DustyRematchDefeat:
	.string "Oh, thanks for calming me down.\p"
	.string "I don't know what I would do without\n"
	.string "you.$"

Route111_Text_DustyPostRematch:
	.string "You'll never believe it, but I forgot my\n"
	.string "hiking compass this time.\p"
	.string "I don't know what I was thinking.$"

Route111_Text_TravisIntro:
	.string "Ah, hiking doesn't get much better than\n"
	.string "this!$"

Route111_Text_TravisDefeat:
	.string "A challenging hike, and a challenging\n"
	.string "battle.\p"
	.string "What more could I ask for?$"

Route111_Text_TravisPostBattle:
	.string "I do enjoy a good challenge, but I'm\n"
	.string "afraid to say that you were a bit too\l"
	.string "much of a challenge for me.$"

Route111_Text_IreneIntro:
	.string "Stop right there!\p"
	.string "We're not supposed to let anyone\n"
	.string "through.$"

Route111_Text_IreneDefeat:
	.string "Crap, you're actually strong!$"

Route111_Text_IrenePostBattle:
	.string "You think you can just do whatever you\n"
	.string "want because you're strong? Huh?\p"
	.string "Well, I guess you're not wrong.$"

Route111_Text_DaisukeIntro:
	.string "I've trained in tough conditions all of\n"
	.string "my life, do you think you can keep up!?$"

Route111_Text_DaisukeDefeat:
	.string "Finally! A worthy opponent!$"

Route111_Text_DaisukePostBattle:
	.string "You were the first opponent I lost to in\n"
	.string "years.\p"
	.string "I'm grateful, believe it or not.\p"
	.string "It gets boring to never face a real\n"
	.string "challenge.$"

Route111_Text_WiltonIntro:
	.string "Hey, you look familiar...$"

Route111_Text_WiltonDefeat:
	.string "Ah, crap!\n"
	.string "You're THAT kid!$"

Route111_Text_WiltonPostBattle:
	.string "Well, at least you got here pretty late.\p"
	.string "You shouldn't be able to stop us now.$"

Route111_Text_WiltonRegister:
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_WiltonRematchIntro:
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:
	.string "Since you're that strong, you should\n"
	.string "aim for the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "We heard rumors of a legendary POKéMON\n"
	.string "somewhere on this mountain!$"

Route111_Text_BrookeDefeat:
	.string "Wow, you're a legend yourself!$"

Route111_Text_BrookePostBattle:
	.string "I only joined Team Phoenix because I\n"
	.string "heard they were searching for a\l"
	.string "legendary POKéMON.\p"
	.string "Who wouldn't want to see a cool POKéMON\n"
	.string "like that?$"

Route111_Text_BrookeRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "You can make POKéMON stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your POKéMON\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat:
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should have stopped my\n"
	.string "POKéMON from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_CeliaIntro:
	.string "No umbrella?\p"
	.string "You'll get soaking wet!$"

Route111_Text_CeliaDefeat:
	.string "Somehow I was the one who got wet!$"

Route111_Text_CeliaPostBattle:
	.string "I don't understand how you people can\n"
	.string "stand to be out in this much rain\l"
	.string "without an umbrella.$"

Route111_Text_BryanIntro:
	.string "Whoa! What's the rush, kid?$"

Route111_Text_BryanDefeat:
	.string "Hey, you're pretty tough.\p"
	.string "You must be the kid from Johto that\n"
	.string "I've heard about.$"

Route111_Text_BryanPostBattle:
	.string "You know, there are a lot of rumors\n"
	.string "about you that they tell the new\l"
	.string "grunts.\p"
	.string "I guess some of those rumors are true.$"

Route111_Text_BrandenIntro:
	.string "Hold up, I've let enough people slip by\n"
	.string "me for one day!$"

Route111_Text_BrandenDefeat:
	.string "Fine then, make it one more person!$"

Route111_Text_BrandenPostBattle:
	.string "I'm sure to lose my job as a ranger at\n"
	.string "this rate...$"

Route111_Text_TyronIntro:
	.string "How did I get stuck with this job?\p"
	.string "I hate the rain!$"

Route111_Text_TyronDefeat:
	.string "Yeah, well, you're just lucky we're not in\n"
	.string "strong sunlight!$"

Route111_Text_TyronPostBattle:
	.string "I guess I could have used the move\n"
	.string "Sunny Day to get rid of the rain.\p"
	.string "Crap, why didn't I think of that before\n"
	.string "I battled you?$"

Route111_Text_CelinaIntro:
	.string "I remember you from the Ecruteak base!\p"
	.string "I can finally get my revenge!$"

Route111_Text_CelinaDefeat:
	.string "Wait, how did you get this much\n"
	.string "stronger?\p"
	.string "That's just unnatural!$"

Route111_Text_CelinaPostBattle:
	.string "Now I'll have to get twice the revenge...\n"
	.string "If we ever meet again, that is...$"

Route111_Text_HaydenIntro:
	.string "Hey! Didn't we have you locked up in\n"
	.string "Goldenrod long ago?$"

Route111_Text_HaydenDefeat:
	.string "This just isn't my day...$"

Route111_Text_HaydenPostBattle:
	.string "Now I see how you managed to break\n"
	.string "yourself out of our cells...$"

Route111_Text_BiancaIntro:
	.string "Just turn back now, kid.\p"
	.string "This is none of your business!$"

Route111_Text_BiancaDefeat:
	.string "Oh...\n"
	.string "Well, when you put it that way...$"

Route111_Text_BiancaPostBattle:
	.string "Really though, you should just mind\n"
	.string "your own business!$"

Route112_Text_BriceIntro:
	.string "Y'all city folk wouldn't last a day out\n"
	.string "on the farm!$"

Route112_Text_BriceDefeat:
	.string "Ok, yer tougher than you look.$"

Route112_Text_BricePostBattle:
	.string "Farm life is tough, but you might have\n"
	.string "what it takes.$"

Route112_Text_TrentIntro:
	.string "Howdy!\n"
	.string "Are you headed to Moomoo Farm?$"

Route112_Text_TrentDefeat:
	.string "I reckon you'd make a good farmhand.$"

Route112_Text_TrentPostBattle:
	.string "Ma and Pa own Moomoo Farm, I always had\n"
	.string "fun playin' with the Miltank when I was\l"
	.string "younger.$"

Route112_Text_TrentRegister:
	.string "If you're ever interested in workin' on\n"
	.string "the farm, or if you just want another\l"
	.string "battle sometime...$"

Route112_Text_TrentRematchIntro:
	.string "I knew you'd be back, let's battle!$"

Route112_Text_TrentRematchDefeat:
	.string "I reckon you're even stronger than last\n"
	.string "time!$"

Route112_Text_TrentRematchPostBattle:
	.string "Ma and Pa own Moomoo Farm, I always had\n"
	.string "fun playin' with the Miltank when I was\l"
	.string "younger.$"

Route112_Text_LarryIntro:
	.string "Three years ago I had a vision...\p"
	.string "I forsaw us having a battle!$"

Route112_Text_LarryDefeat:
	.string "Unfortunately, this is the same\n"
	.string "outcome I saw in my vision.$"

Route112_Text_LarryPostBattle:
	.string "Knowing the future isn't as fun when I\n"
	.string "can't change it.$"

Route112_Text_CarolIntro:
	.string "Would you like me to read your fortune?\p"
	.string "It ends in your defeat!$"

Route112_Text_CarolDefeat:
	.string "No, my predictions have never been\n"
	.string "wrong before...$"

Route112_Text_CarolPostBattle:
	.string "There's something special about you...\p"
	.string "I just can't place my finger on what it\n"
	.string "is exactly...$"

Route112_Text_BryantIntro:
	.string "Fly! My fools!$"

Route112_Text_BryantDefeat:
	.string "What a bumpy flight that was!$"

Route112_Text_BryantPostBattle:
	.string "I didn't expect to lose to a ground\n"
	.string "dweller such as yourself.$"

Route112_Text_ShaylaIntro:
	.string "My my, what an adorable TRAINER.\n"
	.string "Care for a battle?$"

Route112_Text_ShaylaDefeat:
	.string "Adorable and strong!\n"
	.string "Two great qualities.$"

Route112_Text_ShaylaPostBattle:
	.string "This is my favorite route to take walks\n"
	.string "on, there's just something about it\l"
	.string "that put's me at peace.$"

Route113_Text_JaylenIntro:
	.string "This place stinks, and I almost fell\n"
	.string "through the floor!$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_JaylenPostBattle:
	.string "I'm giving this place the worst rating I\n"
	.string "can, nobody should come here.$"

Route113_Text_DillonIntro:
	.string "It's pretty cold out here, but don't\n"
	.string "worry, my POKéMON will be sure to warm\l"
	.string "you up!$"

Route113_Text_DillonDefeat:
	.string "Wow, that battle got heated!$"

Route113_Text_DillonPostBattle:
	.string "This snow can be a pain, but my Camerupt\n"
	.string "keeps me warm.$"

Route113_Text_MadelineIntro:
	.string "Oh... This will not be an easy battle for\n"
	.string "me...\p"
	.string "I can feel it...$"

Route113_Text_MadelineDefeat:
	.string "My intuition is never wrong...\n"
	.string "I knew you would be strong.$"

Route113_Text_MadelinePostBattle:
	.string "You will become one of the strongest\n"
	.string "TRAINERS in this region...\p"
	.string "I can feel it...$"

Route113_Text_MadelineRegister:
	.string "...\p"
	.string "Check your POKéNAV...$"

Route113_Text_MadelineRematchIntro:
	.string "Let's see if you've improved as much as\n"
	.string "I expect you have...$"

Route113_Text_MadelineRematchDefeat:
	.string "Indeed. You're even stronger than I\n"
	.string "expected.$"

Route113_Text_MadelinePostRematch:
	.string "You will become one of the strongest\n"
	.string "TRAINERS in this region...\p"
	.string "I can feel it...$"

Route113_Text_LaoIntro:
	.string "From behind a tree I strike!$"

Route113_Text_LaoDefeat:
	.string "My sneak attack wasn't sneaky enough!$"

Route113_Text_LaoPostBattle:
	.string "I must refine the art of concealment.\n"
	.string "I bid thee farewell.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of POKéNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "From behind a tree I strike!$"

Route113_Text_LaoRematchDefeat:
	.string "My sneak attack still isn't sneaky\n"
	.string "enough!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Ninjas strike from the shadows!\p"
	.string "...Or the snow!$"

Route113_Text_LungDefeat:
	.string "This snow isn't deep enough for a\n"
	.string "proper sneak attack...$"

Route113_Text_LungPostBattle:
	.string "How much longer until the snow is deep\n"
	.string "enough to bury myself...$"

Route113_Text_ToriIntro:
	.string "TORI: You're no match for my sister!\p"
	.string "She's the best!$"

Route113_Text_ToriDefeat:
	.string "TORI: I've never seen my sister lose\n"
	.string "before, this can't be happening.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Do you like the snow?\p"
	.string "My sister and I love the snow!$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_TiaIntro:
	.string "TIA: You're no match for my sister!\p"
	.string "She's the best!$"

Route113_Text_TiaDefeat:
	.string "TIA: I've never seen my sister lose\n"
	.string "before, this can't be happening.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Do you like the snow?\p"
	.string "My sister and I love the snow!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "I'm getting ready for a big hiking trip!$"

Route113_Text_CobyDefeat:
	.string "Wait… What happened?$"

Route113_Text_CobyPostBattle:
	.string "This area has some of the best hiking\n"
	.string "trails around!$"

Route113_Text_SophieIntro:
	.string "I got separated from my tour group,\n"
	.string "maybe a loud battle will alert them to\l"
	.string "my location!$"

Route113_Text_SophieDefeat:
	.string "That battle got way too intense!$"

Route113_Text_SophiePostBattle:
	.string "They really need to put up some signs in\n"
	.string "this place, it's too easy to get lost.$"

Route113_Text_LawrenceIntro:
	.string "I read some great reviews about this\n"
	.string "place, but it's a pile of trash!$"

Route113_Text_LawrenceDefeat:
	.string "No need to be so hostile!$"

Route113_Text_LawrencePostBattle:
	.string "I wanted to go to the Bell Tower\n"
	.string "instead, but they wouldn't let me in.\p"
	.string "This town is the worst!$"

Route113_Text_WyattIntro:
	.string "Excuse me, do you work here?\p"
	.string "I just saw a huge rat!$"

Route113_Text_WyattDefeat:
	.string "So, you don't work here?$"

Route113_Text_WyattPostBattle:
	.string "Whoever runs this place really needs to\n"
	.string "do something about the rat problem!$"

Route114_Text_LennyIntro:
	.string "Ah, this fresh mountainous air really\n"
	.string "soothes my soul!\p"
	.string "It really hypes me up!$"

Route114_Text_LennyDefeat:
	.string "You must be hyped up as well!$"

Route114_Text_LennyPostBattle:
	.string "Route 45 is such a hilly region, it's\n"
	.string "probably my favorite area in all of\l"
	.string "Johto!$"

Route114_Text_LucasIntro:
	.string "There are so many paths to choose from,\n"
	.string "I don't know which way to go!$"

Route114_Text_LucasDefeat:
	.string "I must have gone the wrong way since I\n"
	.string "ran into you...$"

Route114_Text_LucasPostBattle:
	.string "It's a long way back to Blackthorn when\n"
	.string "you don't have a flying POKéMON with\l"
	.string "you.$"

Route114_Text_ShaneIntro:
	.string "Plenty of grass, a small waterfall, and\n"
	.string "the cool mountainous air!\p"
	.string "This is the perfect camping spot, but\n"
	.string "you've just distrupted me!$"

Route114_Text_ShaneDefeat:
	.string "Whoa! You're way too strong!$"

Route114_Text_ShanePostBattle:
	.string "I still say this is the perfect camping\n"
	.string "spot, even if you did distrupt me.$"

Route114_Text_NancyIntro:
	.string "I was going to have a picnic with my\n"
	.string "friend, but I think I jumped down the\l"
	.string "wrong ledge!$"

Route114_Text_NancyDefeat:
	.string "Oh, this is no good!$"

Route114_Text_NancyPostBattle:
	.string "I'll have to go all the way back up to\n"
	.string "Blackthorn City to try a different\l"
	.string "path...$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "My bait worked!$"

Route114_Text_SteveDefeat:
	.string "M-My POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Have you heard of AGATHA?\p"
	.string "She was probably the best GHOST-type\n"
	.string "TRAINER there ever was.\p"
	.string "Some say she still haunts the POKéMON\n"
	.string "League!$"

Route114_Text_SteveRegister:
	.string "Ufufufufufu…\n"
	.string "You're a pretty good TRAINER...\p"
	.string "Let's battle again sometime...$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, let's have another battle…$"

Route114_Text_SteveRematchDefeat:
	.string "Ufufufufufu…\n"
	.string "Still no match for you, it seems...$"

Route114_Text_StevePostRematch:
	.string "Have you heard of AGATHA?\p"
	.string "She was probably the best GHOST-type\n"
	.string "TRAINER there ever was.\p"
	.string "Some say she still haunts the POKéMON\n"
	.string "League!$"

Route114_Text_BernieIntro:
	.string "Everyone always underestimates the\n"
	.string "power of FLYING-type POKéMON.\p"
	.string "I'll show you what they can really do!$"

Route114_Text_BernieDefeat:
	.string "...$"

Route114_Text_BerniePostBattle:
	.string "One day, I will show you the true power\n"
	.string "of FLYING-type POKéMON!\p"
	.string "Just you wait!$"

Route114_Text_BernieRegister:
	.string "Ok, ok.\p"
	.string "Give me another chance!\p"
	.string "I'll train up, and we can battle again.\p"
	.string "Then you will see the true power of\n"
	.string "FLYING-type POKéMON!$"

Route114_Text_BernieRematchIntro:
	.string "I've been training up!\p"
	.string "Get ready to experience the ferocity\n"
	.string "of my FLYING-type POKéMON!$"

Route114_Text_BernieRematchDefeat:
	.string "...$"

Route114_Text_BerniePostRematch:
	.string "One day, I will show you the true power\n"
	.string "of FLYING-type POKéMON!\p"
	.string "Just you wait!$"

Route114_Text_ClaudeIntro:
	.string "Hmm... The fish aren't biting much today!$"

Route114_Text_ClaudeDefeat:
	.string "My luck at battling is just as bad as my\n"
	.string "luck at fishing today it seems...$"

Route114_Text_ClaudePostBattle:
	.string "I think the water is moving too fast for\n"
	.string "anything to bite.$"

Route114_Text_NolanIntro:
	.string "A battle on the bridge?\p"
	.string "Sure, I'm game!$"

Route114_Text_NolanDefeat:
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_NolanPostBattle:
	.string "I was having pretty good luck fishing,\n"
	.string "so I thought that luck would carry over\l"
	.string "to POKéMON battles.\p"
	.string "I guess I was wrong.$"

Route114_Text_TyraIntro:
	.string "LYRA: You must really feel confident in\n"
	.string "your POKéMON battling ability since you\l"
	.string "stopped to talk to us.\p"
	.string "Come on, LIV, let's show this kid what I\n"
	.string "taught you!$"

Route114_Text_TyraDefeat:
	.string "LYRA: I see why you were so confident\n"
	.string "now.\l"
	.string "You're great!$"

Route114_Text_TyraPostBattle:
	.string "LYRA: Maybe you should be the one\n"
	.string "teaching LIV about battling instead.$"

Route114_Text_TyraNotEnoughMons:
	.string "LYRA: Really? You only brought one\n"
	.string "POKéMON to a double battle?\p"
	.string "What is wrong with you?$"

Route114_Text_IvyIntro:
	.string "LIV: I'll show you what LYRA taught me\n"
	.string "about POKéMON battling!$"

Route114_Text_IvyDefeat:
	.string "LIV: Maybe you should be teaching me\n"
	.string "instead of LYRA...$"

Route114_Text_IvyPostBattle:
	.string "LIV: LYRA can be a little eccentric, but\n"
	.string "I think she's still a good teacher.$"

Route114_Text_IvyNotEnoughMons:
	.string "LIV: You only have one POKéMON with\n"
	.string "you?\p"
	.string "I'm sorry, but we only battle as a team.$"

Route114_Text_KaiIntro:
	.string "Fishing isn't always about who can\n"
	.string "catch the biggest fish.\p"
	.string "It can also just be about relaxing.\p"
	.string "POKéMON battling, on the other hand, is\n"
	.string "about who is the winner!$"

Route114_Text_KaiDefeat:
	.string "Oh, I guess that makes me the loser...$"

Route114_Text_KaiPostBattle:
	.string "Well, at least I can go back to my\n"
	.string "relaxing fishing spot.$"

Route114_Text_CharlotteIntro:
	.string "I was waiting for my friend, but she\n"
	.string "never showed up.\p"
	.string "I wonder if she took the wrong path...$"

Route114_Text_CharlotteDefeat:
	.string "Now I feel like I'm the one who's lost!$"

Route114_Text_CharlottePostBattle:
	.string "Maybe I should try another path and\n"
	.string "see if I can find my friend...$"

Route114_Text_AngelinaIntro:
	.string "Isn't this rocky terrain great!?$"

Route114_Text_AngelinaDefeat:
	.string "Hmph, some people just don't appreciate\n"
	.string "good rocks.$"

Route114_Text_AngelinaPostBattle:
	.string "Hiking isn't fun for me unless it's a\n"
	.string "challenging trail.$"

Route115_Text_TimothyIntro:
	.string "Oh ho, thought you could sneak past a\n"
	.string "sleepy old man, did you?$"

Route115_Text_TimothyDefeat:
	.string "Now I really need a nap...$"

Route115_Text_TimothyPostBattle:
	.string "Zzz...\p"
	.string "Huh!?$"

Route115_Text_TimothyRegister:
	.string "You're not too bad...\p"
	.string "Maybe we can battle again between my\n"
	.string "nap times.$"

Route115_Text_TimothyRematchIntro:
	.string "You caught me in between naps, let's go!$"

Route115_Text_TimothyRematchDefeat:
	.string "Zzz...$"

Route115_Text_TimothyPostRematch:
	.string "Zzz...\p"
	.string "Huh!?$"

Route115_Text_KoichiIntro:
	.string "I could stay in this park forever, there\n"
	.string "are so many great BUGS!$"

Route115_Text_KoichiDefeat:
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:
	.string "Must be careful, BUGS are known to\n"
	.string "sting!$"

Route115_Text_NobIntro:
	.string "You caught me!$"

Route115_Text_NobDefeat:
	.string "Couldn't catch a break...$"

Route115_Text_NobPostBattle:
	.string "I was trying to throw you off, but you\n"
	.string "caught me anyway.\p"
	.string "You would make a good bug catcher!$"

Route115_Text_NobRegister:
	.string "You would make a good bug catcher.\p"
	.string "Register me, so you can teach me your\n"
	.string "catching ways.$"

Route115_Text_NobRematchIntro:
	.string "You caught me again!$"

Route115_Text_NobRematchDefeat:
	.string "I still can't catch a break...$"

Route115_Text_NobPostRematch:
	.string "I was trying to throw you off, but you\n"
	.string "caught me anyway.\p"
	.string "You would make a good bug catcher!$"

Route115_Text_CyndyIntro:
	.string "I was throwing coins into the fountain,\n"
	.string "but got bored.\p"
	.string "You! Battle with me!$"

Route115_Text_CyndyDefeat:
	.string "You're tougher than I expected.$"

Route115_Text_CyndyPostBattle:
	.string "Throwing coins into the fountain is fun,\n"
	.string "but my wishes never come true.$"

Route115_Text_CyndyRegister:
	.string "I wish to battle with you again.\p"
	.string "Give me your POKéNAV...$"

Route115_Text_CyndyRematchIntro:
	.string "I made a wish that you would return, and\n"
	.string "here you are!$"

Route115_Text_CyndyRematchDefeat:
	.string "You're still as tough as ever…$"

Route115_Text_CyndyPostRematch:
	.string "Throwing coins into the fountain is fun,\n"
	.string "but my wishes never come true.$"

Route115_Text_HectorIntro:
	.string "Am I bugging you?\p"
	.string "Hey, hey!\p"
	.string "Hey!$"

Route115_Text_HectorDefeat:
	.string "I should have left you alone.$"

Route115_Text_HectorPostBattle:
	.string "Does our copying bug you?$"

Route115_Text_KyraIntro:
	.string "I got you!\p"
	.string "Wait, you're no bug!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp…$"

Route115_Text_KyraPostBattle:
	.string "I've been catching too many bugs,\n"
	.string "they're all I see now.$"

Route115_Text_JaidenIntro:
	.string "Take that!\n"
	.string "Super POKéMON ninja attack!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_JaidenPostBattle:
	.string "But my POKéMON were strong,\n"
	.string "weren't they?$"

Route115_Text_HeleneIntro:
	.string "Do you know what goes best with a\n"
	.string "picnic?\p"
	.string "That's right, a battle!$"

Route115_Text_HeleneDefeat:
	.string "Ok, maybe I was wrong.$"

Route115_Text_HelenePostBattle:
	.string "A battle only goes well with a picnic if\n"
	.string "I win...$"

Route115_Text_AlixIntro:
	.string "Pick up that trash!$"

Route115_Text_AlixDefeat:
	.string "Sorry, I was mistaken...$"

Route115_Text_AlixPostBattle:
	.string "I thought I saw you littering, but I was\n"
	.string "mistaken.\p"
	.string "I almost wrote you a citation.\p"
	.string "...\p"
	.string "Hey, that rhymed!$"

Route115_Text_MarleneIntro:
	.string "The tall grass, or the short grass?\p"
	.string "Which has the better POKéMON?$"

Route115_Text_MarleneDefeat:
	.string "Maybe the same POKéMON are in both\n"
	.string "grass patches?$"

Route115_Text_MarlenePostBattle:
	.string "I still can't figure out if the tall\n"
	.string "grass is any better than the short\l"
	.string "grass...$"

Route116_Text_ClarkIntro:
	.string "You're no match for my super rare\n"
	.string "POKéMON!$"

Route116_Text_ClarkDefeat:
	.string "Perhaps I was wrong about you…$"

Route116_Text_ClarkPostBattle:
	.string "Have you found any rare POKéMON in this\n"
	.string "cave yet?$"

Route116_Text_JoeyIntro:
	.string "Rocky caves like this are great!\p"
	.string "What's not to love?$"

Route116_Text_JoeyDefeat:
	.string "Ouch, I got rocked.$"

Route116_Text_JoeyPostBattle:
	.string "Have you been to the mountains up\n"
	.string "north?\p"
	.string "They have plenty of great caves to\n"
	.string "explore.$"

Route116_Text_JoseIntro:
	.string "My POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_JosePostBattle:
	.string "ROCK and GROUND-type POKéMON are the\n"
	.string "best, wouldn't you agree?$"

Route116_Text_JaniceIntro:
	.string "Don't play with fire unless you're\n"
	.string "prepared to get burned!$"

Route116_Text_JaniceDefeat:
	.string "You're a notch above me…$"

Route116_Text_JanicePostBattle:
	.string "I came into Union Cave to hide from the\n"
	.string "rain on Route 33, it's too wet out there\l"
	.string "for my POKéMON.$"

Route116_Text_JerryIntro:
	.string "A hiker must know when he's reached his\n"
	.string "limit.$"

Route116_Text_JerryDefeat:
	.string "I guess you were above my limit.$"

Route116_Text_JerryPostBattle:
	.string "I'll have to train myself to overcome my\n"
	.string "limits.$"

Route116_Text_JerryRegister1:
	.string "You're not half bad.\p"
	.string "Maybe we can battle again sometime...$"

Route116_Text_JerryRegister2:
	.string "You're not half bad.\p"
	.string "Maybe we can battle again sometime...$"

Route116_Text_JerryRematchIntro:
	.string "I've been in training all this time.\p"
	.string "I've pushed well past my old limits,\n"
	.string "allow me to show you!$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "I trained so hard though.$"

Route116_Text_JerryPostRematch:
	.string "It seems my training is not yet\n"
	.string "complete.$"

Route116_Text_KarenIntro:
	.string "I got lost in this cave, and can't find\n"
	.string "my way out!$"

Route116_Text_KarenDefeat:
	.string "Now I've lost in more ways than one.$"

Route116_Text_KarenPostBattle:
	.string "You know what, it's ok, I'm starting to\n"
	.string "like this cave.$"

Route116_Text_KarenRegister1:
	.string "Hey, is that a POKéNAV?\p"
	.string "Register me, at least then I won't get\n"
	.string "too lonely.$"

Route116_Text_KarenRegister2:
	.string "Hey, is that a POKéNAV?\p"
	.string "Register me, at least then I won't get\n"
	.string "too lonely.$"

Route116_Text_KarenRematchIntro:
	.string "Remember me?\p"
	.string "Yep, I'm still in this same cave.\p"
	.string "It's really not bad once you get used to\n"
	.string "it.\p"
	.string "I'm bored though, let's battle!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch:
	.string "This cave really isn't that bad once you\n"
	.string "get used to it.$"

Route116_Text_SarahIntro:
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at anything.$"

Route116_Text_SarahDefeat:
	.string "Oh, wow.\n"
	.string "This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "I guess there's a first time for\n"
	.string "everything.\p"
	.string "Even losing.$"

Route116_Text_DawsonIntro:
	.string "Are you here looking for the rare\n"
	.string "POKéMON too?$"

Route116_Text_DawsonDefeat:
	.string "Oh no, say it isn't so!$"

Route116_Text_DawsonPostBattle:
	.string "I heard rumors there's a very rare\n"
	.string "POKéMON here.$"

Route116_Text_DevanIntro:
	.string "Where are the Lapras?\p"
	.string "I heard they were in this cave!$"

Route116_Text_DevanDefeat:
	.string "No contest at all!$"

Route116_Text_DevanPostBattle:
	.string "Maybe that Lapras just isn't meant for\n"
	.string "me.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_JohnsonDefeat:
	.string "That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route117_Text_IsaacIntro:
	.string "Have you been to the POKéMON daycare\n"
	.string "up ahead?\p"
	.string "Breeding POKéMON is a good way to get\n"
	.string "good natures and egg moves!$"

Route117_Text_IsaacDefeat:
	.string "You've raised your POKéMON well.$"

Route117_Text_IsaacPostBattle:
	.string "Battling is important, but breeding and\n"
	.string "raising POKéMON should not be\l"
	.string "overlooked.$"

Route117_Text_IsaacRegister:
	.string "Hey, why don't you register me in your\n"
	.string "POKéNAV!\p"
	.string "That way I can make sure you are\n"
	.string "raising your POKéMON well.$"

Route117_Text_IsaacRematchIntro:
	.string "Hey, let's see how well you've raised\n"
	.string "your POKéMON!$"

Route117_Text_IsaacRematchDefeat:
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_IsaacPostRematch:
	.string "Battling is important, but breeding and\n"
	.string "raising POKéMON should not be\l"
	.string "overlooked.$"

Route117_Text_LydiaIntro:
	.string "I left my POKéMON in the daycare, but\n"
	.string "couldn't stand not to come check up on\l"
	.string "him!$"

Route117_Text_LydiaDefeat:
	.string "I hope my little Azumarill didn't watch\n"
	.string "me lose!$"

Route117_Text_LydiaPostBattle:
	.string "Hmm, maybe I'll leave another POKéMON in\n"
	.string "the daycare with my Azumarill so he\l"
	.string "doesn't get too lonely...$"

Route117_Text_LydiaRegister:
	.string "You're a rather strong TRAINER, perhaps\n"
	.string "we could have a rematch sometime.$"

Route117_Text_LydiaRematchIntro:
	.string "There you are, {PLAYER}.\p"
	.string "I need a battle to keep my mind off my\n"
	.string "Azumarill.$"

Route117_Text_LydiaRematchDefeat:
	.string "I hope my little Azumarill didn't watch\n"
	.string "me lose!$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I'm training for the Goldenrod\n"
	.string "Marathon, but I suppose I could take a\l"
	.string "quick break and battle!$"

Route117_Text_DylanDefeat:
	.string "You're lucky that I'm still exhausted\n"
	.string "from running.$"

Route117_Text_DylanPostBattle:
	.string "What do you mean you've never heard of\n"
	.string "the Goldenrod Marathon?$"

Route117_Text_DylanRegister:
	.string "If I ever recover my energy, I would\n"
	.string "like to battle with you again...$"

Route117_Text_DylanRematchIntro:
	.string "I'm right in the middle of training, but I\n"
	.string "always have time for a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "I didn't do very well in the Goldenrod\n"
	.string "Marathon, I suppose there's always\l"
	.string "next year...$"

Route117_Text_MariaIntro:
	.string "I do my marathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_MariaRegister:
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "I want to show these girls my bug\n"
	.string "collection, but I'm too nervous to talk\l"
	.string "to them!$"

Route117_Text_DerekDefeat:
	.string "I lost, now I really can't go talk to\n"
	.string "these girls.$"

Route117_Text_DerekPostBattle:
	.string "Some people just don't have an\n"
	.string "appreciation for bugs...$"

Route117_Text_AnnaIntro:
	.string "LYNN: Oh you look strong, how about a\n"
	.string "double battle!$"

Route117_Text_AnnaDefeat:
	.string "LYNN: I guess your looks were not\n"
	.string "deceiving, you are strong!$"

Route117_Text_AnnaPostBattle:
	.string "LYNN: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "LYNN: You will battle us again, won't\n"
	.string "you?\p"
	.string "We will show you the true power of our\n"
	.string "friendship!$"

Route117_Text_AnnaNotEnoughMons:
	.string "LYNN: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegIntro:
	.string "EVE: We will show you what true\n"
	.string "friendship can accomplish, come on\l"
	.string "LYNN!$"

Route117_Text_MegDefeat:
	.string "EVE: Our friendship wasn't powerful\n"
	.string "enough!$"

Route117_Text_MegPostBattle:
	.string "EVE: Double battles are fun, wouldn't\n"
	.string "you agree?$"

Route117_Text_MegNotEnoughMons:
	.string "EVE: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "LYNN: Are you prepared for a rematch,\n"
	.string "our friendship will crush you this time!$"

Route117_Text_AnnaRematchDefeat:
	.string "LYNN: You're still as strong as ever...$"

Route117_Text_AnnaPostRematch:
	.string "LYNN: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "LYNN: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegRematchIntro:
	.string "EVE: LYNN and I have been practicing\n"
	.string "double battles, prepare to lose this\l"
	.string "time!$"

Route117_Text_MegRematchDefeat:
	.string "EVE: Too strong!$"

Route117_Text_MegPostRematch:
	.string "EVE: Double battles are fun, wouldn't\n"
	.string "you agree?$"

Route117_Text_MegRematchNotEnoughMons:
	.string "EVE: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Oh, it seems there is a TRAINER in my\n"
	.string "path!$"

Route117_Text_MelinaDefeat:
	.string "Oh, that's quite impressive!$"

Route117_Text_MelinaPostBattle:
	.string "Running always relaxes me after a tough\n"
	.string "battle.$"

Route117_Text_BrandiIntro:
	.string "This creepy guy keeps looking at us.\n"
	.string "Maybe if he sees how tough we are, he\l"
	.string "will leave us alone!$"

Route117_Text_BrandiDefeat:
	.string "Astonishing!$"

Route117_Text_BrandiPostBattle:
	.string "The creepy guy still hasn't left, and\n"
	.string "why is he holding a net?$"

Route117_Text_AishaIntro:
	.string "I want to leave, but don't want to turn\n"
	.string "my back on this creepy guy!$"

Route117_Text_AishaDefeat:
	.string "You're pretty tough, maybe you can run\n"
	.string "off the creepy guy.$"

Route117_Text_AishaPostBattle:
	.string "When will this creepy guy let us leave?$"

Route118_Text_RoseIntro:
	.string "I love the sweet smell of flowers,\n"
	.string "nature really does create the finest\l"
	.string "perfume!$"

Route118_Text_RoseDefeat:
	.string "Oh, what is this foul stench?$"

Route118_Text_RosePostBattle:
	.string "You say you're from Cherrygrove?\p"
	.string "I've heard they have the best flowers.$"

Route118_Text_RoseRegister:
	.string "Sniff… That odor--it's a POKéNAV!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Did you come for a rematch, or to talk\n"
	.string "about the flowers?\p"
	.string "A rematch it is!$"

Route118_Text_RoseRematchDefeat:
	.string "There's that foul stench of defeat\n"
	.string "again...$"

Route118_Text_RosePostRematch:
	.string "You say you're from Cherrygrove?\p"
	.string "I've heard they have the best flowers.$"

Route118_Text_PerryIntro:
	.string "My bird POKéMON always have the high\n"
	.string "ground!\p"
	.string "There's no way I can lose!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "I crashed…$"

Route118_Text_PerryPostBattle:
	.string "I guess having the high ground doesn't\n"
	.string "always guarantee victory.$"

Route118_Text_ChesterIntro:
	.string "Nothing is more freeing than flight!$"

Route118_Text_ChesterDefeat:
	.string "Oof...\n"
	.string "Knocked back down to earth!$"

Route118_Text_ChesterPostBattle:
	.string "If you have the HM02, you can hitch a\n"
	.string "ride on your POKéMON and fly with them!$"

Route118_Text_BarnyIntro:
	.string "Fishing isn't too exciting at the\n"
	.string "moment, maybe you can liven things up\l"
	.string "for me!$"

Route118_Text_BarnyDefeat:
	.string "That's a little too lively for me.$"

Route118_Text_BarnyPostBattle:
	.string "The fish here are not very exciting,\n"
	.string "maybe I'll find a new fishing spot.$"

Route118_Text_WadeIntro:
	.string "Nobody can outfish me!\p"
	.string "I am a master baiter!$"

Route118_Text_WadeDefeat:
	.string "I'll have to try a different bait next\n"
	.string "time...$"

Route118_Text_WadePostBattle:
	.string "Choosing the perfect bait is the key to\n"
	.string "fishing.\p"
	.string "Maybe one day you too can become a\n"
	.string "master baiter like myself.$"

Route118_Text_DaltonIntro:
	.string "I'm amped up and ready for a battle!$"

Route118_Text_DaltonDefeat:
	.string "I've lost my spark!$"

Route118_Text_DaltonPostBattle:
	.string "I need to go recharge now.$"

Route118_Text_DaltonRegister:
	.string "You just rocked my world, maybe next\n"
	.string "time I can rock yours...$"

Route118_Text_DaltonRematchIntro:
	.string "I'm amped up again and ready for\n"
	.string "another battle!$"

Route118_Text_DaltonRematchDefeat:
	.string "I'm all out of juice!$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Sneak attack!$"

Route118_Text_DeandreDefeat:
	.string "You saw me through the fence?\p"
	.string "I guess I wasn't sneaky enough.$"

Route118_Text_DeandrePostBattle:
	.string "I was trying to emulate a ninja that\n"
	.string "jumped out from behind a fake tree and\l"
	.string "battled me.$"

Route119_Text_BrentIntro:
	.string "Buahaha!\p"
	.string "My vast collection of POKéMON will see\n"
	.string "me through the POKéMON League!$"

Route119_Text_BrentDefeat:
	.string "No, I thought I had all the best\n"
	.string "POKéMON...$"

Route119_Text_BrentPostBattle:
	.string "Your POKéMON collection is also quite\n"
	.string "admirable.$"

Route119_Text_DonaldIntro:
	.string "Hey! Who let you out of your cell!?$"

Route119_Text_DonaldDefeat:
	.string "With that strength, you must have\n"
	.string "broken out yourself.$"

Route119_Text_DonaldPostBattle:
	.string "No, please, just walk around our base\n"
	.string "like you own the place.\p"
	.string "Psh, kids.$"

Route119_Text_TaylorIntro:
	.string "Who are you?\p"
	.string "What are you doing in my secret cove!?$"

Route119_Text_TaylorDefeat:
	.string "Oh, so now you think you own this cove?$"

Route119_Text_TaylorPostBattle:
	.string "Fine, you can stay in my secret cove.\p"
	.string "Just don't tell anyone else about it.$"

Route119_Text_DougIntro:
	.string "Really? Which GRUNT forgot to take your\n"
	.string "POKéMON away from you?$"

Route119_Text_DougDefeat:
	.string "You're tougher than you look...$"

Route119_Text_DougPostBattle:
	.string "Having trouble with our warp pads?\n"
	.string "Haha!$"

Route119_Text_GregIntro:
	.string "Hey, you get back in your cell!\p"
	.string "I don't want DAMON to yell at me again!$"

Route119_Text_GregDefeat:
	.string "Great, I'll get yelled at for sure now.$"

Route119_Text_GregPostBattle:
	.string "This is a pretty stressful job, you\n"
	.string "know.\p"
	.string "Ah, you wouldn't understand.$"

Route119_Text_KentIntro:
	.string "Really, kid? I'm on my break!$"

Route119_Text_KentDefeat:
	.string "Now I really need a break!$"

Route119_Text_KentPostBattle:
	.string "I should have went with the other\n"
	.string "GRUNTS to the Ecruteak Base.$"

Route119_Text_JacksonIntro:
	.string "Humph!\p"
	.string "You think a whippersnapper like you has\n"
	.string "what it takes to face the POKéMON\l"
	.string "League?$"

Route119_Text_JacksonDefeat:
	.string "Hrmm... Yes... Perhaps you do have what\n"
	.string "it takes...$"

Route119_Text_JacksonPostBattle:
	.string "The POKéMON League is not for those\n"
	.string "who lack determination.$"

Route119_Text_JacksonRegister:
	.string "I would like to see how far your\n"
	.string "determination leads you.\p"
	.string "Please, let me see your POKéNAV...$"

Route119_Text_JacksonRematchIntro:
	.string "I've been waiting for your arrival.\p"
	.string "Please, allow me to evaluate your\n"
	.string "progress.$"

Route119_Text_JacksonRematchDefeat:
	.string "You have progressed quite far indeed!$"

Route119_Text_JacksonPostRematch:
	.string "I have no doubt you will surpass the\n"
	.string "POKéMON League, if you haven't already\l"
	.string "that is...$"

Route119_Text_CatherineIntro:
	.string "Do you believe in curses...?$"

Route119_Text_CatherineDefeat:
	.string "You have my admiration...\n"
	.string "And sympathy...$"

Route119_Text_CatherinePostBattle:
	.string "A powerful curse looms over the\n"
	.string "POKéMON League...$"

Route119_Text_CatherineRegister:
	.string "...$"

Route119_Text_CatherineRematchIntro:
	.string "Have you started believing in curses...?$"

Route119_Text_CatherineRematchDefeat:
	.string "...$"

Route119_Text_CatherinePostRematch:
	.string "A powerful curse looms over the\n"
	.string "POKéMON League...$"

Route119_Text_HughIntro:
	.string "The road ahead is long and difficult, do\n"
	.string "you think you are up for the challenge?$"

Route119_Text_HughDefeat:
	.string "I guess I didn't give you enough\n"
	.string "credit...$"

Route119_Text_HughPostBattle:
	.string "Up ahead lies Victory Road, and beyond\n"
	.string "that lies the POKéMON League...$"

Route119_Text_PhilIntro:
	.string "Yo! Are you preparing for the POKéMON\n"
	.string "League too?$"

Route119_Text_PhilDefeat:
	.string "You seem to be a little more prepared\n"
	.string "than I am...$"

Route119_Text_PhilPostBattle:
	.string "The strongest TRAINERS from Kanto and\n"
	.string "Johto all gather near the POKéMON\l"
	.string "League to train.$"

Route119_Text_YasuIntro:
	.string "And who might you be?\p"
	.string "An intruder!$"

Route119_Text_YasuDefeat:
	.string "A strong intruder, it seems...$"

Route119_Text_YasuPostBattle:
	.string "How did you discover our secret base?\p"
	.string "...\p"
	.string "Oh, DAMON must have brought you here.\p"
	.string "Crap, he'll be mad when he finds out you\n"
	.string "escaped.\p"
	.string "Could you please go back to your cell\n"
	.string "and wait there?$"

Route119_Text_TakashiIntro:
	.string "They never let me go on any fun\n"
	.string "missions, it's so boring at this base!$"

Route119_Text_TakashiDefeat:
	.string "Well at least that battle wasn't\n"
	.string "boring...$"

Route119_Text_TakashiPostBattle:
	.string "Who are you anyway?$"

Route119_Text_HideoIntro:
	.string "Alright kid, this is as far as you're\n"
	.string "going.\p"
	.string "Back to your cell!$"

Route119_Text_HideoDefeat:
	.string "So that's how you got past the other\n"
	.string "GRUNTS...$"

Route119_Text_HideoPostBattle:
	.string "You defeated me in a POKéMON battle, I\n"
	.string "guess there isn't anything else I can\l"
	.string "do to stop you now...$"

Route119_Text_ChrisIntro:
	.string "Don't expect me to be too laid back just\n"
	.string "because I'm a fisherman.\p"
	.string "These waters can get rough!$"

Route119_Text_ChrisDefeat:
	.string "My waves broke on your immovable wall.$"

Route119_Text_ChrisPostBattle:
	.string "Have you tried fishing at the\n"
	.string "Goldenvine Sea?$"

Route119_Text_FabianIntro:
	.string "Whether it's fishing, or battling,\n"
	.string "patience is key!$"

Route119_Text_FabianDefeat:
	.string "Now that battle really tested the\n"
	.string "limits of my patience...$"

Route119_Text_FabianPostBattle:
	.string "I have anger issues, and I thought\n"
	.string "fishing would calm my nerves and teach\l"
	.string "me to be more patient.$"

Route119_Text_DaytonIntro:
	.string "Are you one of the new recruits?\p"
	.string "...\p"
	.string "Hey wait! You're one of the kids they\n"
	.string "captured!$"

Route119_Text_DaytonDefeat:
	.string "Where did you get POKéMON that good?$"

Route119_Text_DaytonPostBattle:
	.string "Maybe you should be one of our new\n"
	.string "recruits, have you ever thought about\l"
	.string "committing to a life of crime?$"

Route119_Text_RachelIntro:
	.string "You seem familiar, have we met\n"
	.string "somewhere before...?$"

Route119_Text_RachelDefeat:
	.string "Oh... I know now...$"

Route119_Text_RachelPostBattle:
	.string "I had a vision of our battle years ago.\p"
	.string "It's a shame I didn't remember the\n"
	.string "outcome...$"

Route120_Text_ColinIntro:
	.string "Didn't roll your ankle jumping down the\n"
	.string "ledges, did you?\p"
	.string "Fwahaha!$"

Route120_Text_ColinDefeat:
	.string "Oh, I guess you rolled me!$"

Route120_Text_ColinPostBattle:
	.string "This rocky terrain isn't for everyone,\n"
	.string "but I love it!$"

Route120_Text_RobertIntro:
	.string "I have already forseen my victory at\n"
	.string "the POKéMON League!\p"
	.string "This battle will be a piece of cake in\n"
	.string "comparison!$"

Route120_Text_RobertDefeat:
	.string "Unfortunately, I haven't seen how long\n"
	.string "until I claim victory at the POKéMON\l"
	.string "League...$"

Route120_Text_RobertPostBattle:
	.string "My vision of defeating the POKéMON\n"
	.string "League is still crystal clear in my mind.\p"
	.string "I just don't know when it will happen...$"

Route120_Text_RobertRegister:
	.string "In the meantime, for more training...$"

Route120_Text_RobertRematchIntro:
	.string "Let me test how much closer I am to\n"
	.string "defeating the POKéMON League!$"

Route120_Text_RobertRematchDefeat:
	.string "Still not my time yet...$"

Route120_Text_RobertPostRematch:
	.string "My vision of defeating the POKéMON\n"
	.string "League is still crystal clear in my mind.\p"
	.string "I just don't know when it will happen...$"

Route120_Text_LorenzoIntro:
	.string "This route is pretty rough for a little\n"
	.string "kid like you.\p"
	.string "Allow me to test your POKéMON battling\n"
	.string "skills!$"

Route120_Text_LorenzoDefeat:
	.string "Ok, you passed my test.\n"
	.string "You can go on through.$"

Route120_Text_LorenzoPostBattle:
	.string "You know, you're stronger than you look,\n"
	.string "kid.$"

Route120_Text_JennaIntro:
	.string "Are you headed to the rest house too?$"

Route120_Text_JennaDefeat:
	.string "No, that's fine, really, I'm ok.$"

Route120_Text_JennaPostBattle:
	.string "I like to train near the rest house so I\n"
	.string "can heal my POKéMON up frequently.$"

Route120_Text_JeffreyIntro:
	.string "They said BUG-type POKéMON are too\n"
	.string "weak!\p"
	.string "I'll show them!\n"
	.string "I'll show all of you!$"

Route120_Text_JeffreyDefeat:
	.string "That wasn't what I meant to show you...$"

Route120_Text_JeffreyPostBattle:
	.string "One day I'll show you that BUG-type\n"
	.string "POKéMON can compete with the best of\l"
	.string "them!$"

Route120_Text_JeffreyRegister:
	.string "Hey, just give me another chance...\p"
	.string "Here, give me your POKéNAV!\p"
	.string "Then someday I can show you the true\n"
	.string "potential of BUG-type POKéMON!$"

Route120_Text_JeffreyRematchIntro:
	.string "There you are!\p"
	.string "I've been training!\p"
	.string "Now get ready to see the full potential\n"
	.string "of my BUG-type POKéMON!$"

Route120_Text_JeffreyRematchDefeat:
	.string "Maybe BUG-type POKéMON just... Don't...\n"
	.string "Have potential...\p"
	.string "No! That can't be it!$"

Route120_Text_JeffreyPostRematch:
	.string "One day I'll show you that BUG-type\n"
	.string "POKéMON can compete with the best of\l"
	.string "them!$"

Route120_Text_JenniferIntro:
	.string "I'll use you as a quick warm up for the\n"
	.string "POKéMON League!$"

Route120_Text_JenniferDefeat:
	.string "Well then, I guess I'm not ready yet...$"

Route120_Text_JenniferPostBattle:
	.string "I thought you would be an easy warm up\n"
	.string "since you're just a kid.\p"
	.string "I guess looks can be deceiving.$"

Route120_Text_ChipIntro:
	.string "We're getting close to Victory Road, one\n"
	.string "my favorite caves!$"

Route120_Text_ChipDefeat:
	.string "Well, that certainly ruined my good\n"
	.string "mood.$"

Route120_Text_ChipPostBattle:
	.string "I would say Meteor Falls in the Hoenn\n"
	.string "region is another favorite cave of mine.$"

Route120_Text_ClarissaIntro:
	.string "I was trying to go to Mt. Silver,\n"
	.string "but they won't let through!$"

Route120_Text_ClarissaDefeat:
	.string "Maybe I'm not as good as I thought I\n"
	.string "was...$"

Route120_Text_ClarissaPostBattle:
	.string "The gatehouse guards wouldn't let me go\n"
	.string "to Mt. Silver.\p"
	.string "I wonder why it's so special.$"

Route120_Text_AngelicaIntro:
	.string "Do you know why we're called\n"
	.string "COOLTRAINERS?$"

Route120_Text_AngelicaDefeat:
	.string "I was going to say it's because we're\n"
	.string "too cool to lose...$"

Route120_Text_AngelicaPostBattle:
	.string "Maybe we're called COOLTRAINERS\n"
	.string "because we keep our cool even when we\l"
	.string "lose...?$"

Route120_Text_KeigoIntro:
	.string "So, you saw through my perfect\n"
	.string "disguise?\p"
	.string "You must be good!$"

Route120_Text_KeigoDefeat:
	.string "I knew you would be good!$"

Route120_Text_KeigoPostBattle:
	.string "Us ninja are based in Mahogany Town,\n"
	.string "but it's too cold there for me this time\l"
	.string "of year.$"

Route120_Text_RileyIntro:
	.string "Like a ninja, you must have a good plan\n"
	.string "of attack before challenging the\l"
	.string "POKéMON League!$"

Route120_Text_RileyDefeat:
	.string "It appears my well thought out attack\n"
	.string "did not work on you!$"

Route120_Text_RileyPostBattle:
	.string "Perhaps I should have disguised myself\n"
	.string "as a local tree instead...$"

Route120_Text_CallieIntro:
	.string "Be careful, I'm not just a pretty face!$"

Route120_Text_CallieDefeat:
	.string "Oh, I guess I underestimated you too.$"

Route120_Text_CalliePostBattle:
	.string "You know, it takes a lot of work to stay\n"
	.string "this pretty.\p"
	.string "You wouldn't get it, you're too young.$"

Route120_Text_LeonelIntro:
	.string "Haha! Your POKéMON aren't getting tired\n"
	.string "yet, are they?$"

Route120_Text_LeonelDefeat:
	.string "Well now my POKéMON need a break!$"

Route120_Text_LeonelPostBattle:
	.string "Man, this route is longer than I thought\n"
	.string "it would be.\p"
	.string "Maybe I should stop by the rest house\n"
	.string "ahead.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat:
	.string "I have lost…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_CristinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle:
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro:
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route123_Text_WendyIntro:
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "I swam too far out and now I'm lost!$"

Route124_Text_SpencerDefeat:
	.string "That was a fun battle, but I'm still\n"
	.string "lost...$"

Route124_Text_SpencerPostBattle:
	.string "Hmm... Now which way was Olivine again...$"

Route124_Text_RolandIntro:
	.string "Get off your POKéMON and swim!\p"
	.string "It's the best form of exercise!$"

Route124_Text_RolandDefeat:
	.string "Maybe you don't know how to swim.$"

Route124_Text_RolandPostBattle:
	.string "Swimming around the Whirl Islands is\n"
	.string "great exercise, I do it every day!$"

Route124_Text_JennyIntro:
	.string "I'm imitating a whirlpool!$"

Route124_Text_JennyDefeat:
	.string "Ugh, I'm getting dizzy!$"

Route124_Text_JennyPostBattle:
	.string "Do you think whirlpools get dizzy from\n"
	.string "spinning so much?$"

Route124_Text_JennyRegister:
	.string "I'm getting bored of spinning in circles,\n"
	.string "you should register me in your POKéNAV.\p"
	.string "I'll call you sometime.$"

Route124_Text_JennyRematchIntro:
	.string "I've been spinning so much, I can't stop\n"
	.string "now!$"

Route124_Text_JennyRematchDefeat:
	.string "Hey! You beat me again!$"

Route124_Text_JennyPostRematch:
	.string "I've spent so much time out here\n"
	.string "spinning in circles, that I no longer get\l"
	.string "dizzy at all!$"

Route124_Text_GraceIntro:
	.string "Are you looking for the legendary\n"
	.string "POKéMON too?$"

Route124_Text_GraceDefeat:
	.string "I think you're strong enough without a\n"
	.string "legendary POKéMON...$"

Route124_Text_GracePostBattle:
	.string "I've heard there are legendary POKéMON\n"
	.string "in the Whirl Islands, but I'm having\l"
	.string "trouble getting inside.$"

Route124_Text_ChadIntro:
	.string "Are you going out to the Goldenvine Sea\n"
	.string "too?$"

Route124_Text_ChadDefeat:
	.string "You nearly sank me!$"

Route124_Text_ChadPostBattle:
	.string "The Goldenvine Sea rapids will take you\n"
	.string "all the way to Goldenrod City, it's a\l"
	.string "long way back though.$"

Route124_Text_LilaIntro:
	.string "LILY: I'm teaching my little brother to\n"
	.string "swim, and battle POKéMON!$"

Route124_Text_LilaDefeat:
	.string "LILY: I guess my little brother needs\n"
	.string "to learn how to lose gracefully as well...$"

Route124_Text_LilaPostBattle:
	.string "LILY: My little brother seems to be\n"
	.string "getting better at swimming, all the\l"
	.string "training must be paying off.$"

Route124_Text_LilaNotEnoughMons:
	.string "LILY: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "RON: My sister has been teaching me a\n"
	.string "lot about battling, this will be easy!$"

Route124_Text_RoyDefeat:
	.string "RON: Wow! You're a lot tougher than you\n"
	.string "look!$"

Route124_Text_RoyPostBattle:
	.string "RON: My sister has been teaching me how\n"
	.string "to swim too!\p"
	.string "I swam all the way out here from\n"
	.string "Cianwood!$"

Route124_Text_LilaRoyRegister:
	.string "LILY: Say, you should register us in\n"
	.string "your POKéNAV so my brother can get\l"
	.string "more experience battling too.$"

Route124_Text_RoyNotEnoughMons:
	.string "RON: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILY: There you are!\p"
	.string "Come on RON, let's show {PLAYER} how\n"
	.string "much you've improved!$"

Route124_Text_LilaRematchDefeat:
	.string "LILY: I guess there's always room for\n"
	.string "more improvement...$"

Route124_Text_LilaPostRematch:
	.string "LILY: We'll stay out here and train, one\n"
	.string "day we will defeat you...$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILY: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "RON: Come on! Let me show you how much\n"
	.string "better I've gotten!$"

Route124_Text_RoyRematchDefeat:
	.string "RON: Better at swimming that is...\n"
	.string "Maybe not battling...$"

Route124_Text_RoyPostRematch:
	.string "RON: My sister and I swam all the way to\n"
	.string "Olivine and back, I'm definitely getting\l"
	.string "better!$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "RON: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Can't figure out how to get into the\n"
	.string "Whirl Islands?\p"
	.string "I might tell you the secret if you\n"
	.string "defeat me...$"

Route124_Text_DeclanDefeat:
	.string "Fine, I'll tell you the secret!$"

Route124_Text_DeclanPostBattle:
	.string "Ok, I'll tell you...\p"
	.string "See those dark patches of water?\p"
	.string "If you have the HM move, Dive, you can\n"
	.string "go underneath the rocks and whirlpools.$"

Route124_Text_IsabellaIntro:
	.string "I've been swimming and training POKéMON\n"
	.string "my entire life!\p"
	.string "Think you can beat me?$"

Route124_Text_IsabellaDefeat:
	.string "How did you get so good at battling\n"
	.string "POKéMON?$"

Route124_Text_IsabellaPostBattle:
	.string "At least I'm sure I could outswim you...$"

Route125_Text_NolenIntro:
	.string "The water can get rougher this far out,\n"
	.string "let me test your composure!$"

Route125_Text_NolenDefeat:
	.string "You just pushed me around like a strong\n"
	.string "current.$"

Route125_Text_NolenPostBattle:
	.string "I was going to swim in the Goldenvine\n"
	.string "Sea, but the rapids are too strong.$"

Route125_Text_StanIntro:
	.string "Yo! Why ride on your POKéMON?\p"
	.string "The water is nice and cool this time of\n"
	.string "year!$"

Route125_Text_StanDefeat:
	.string "Glup glup!$"

Route125_Text_StanPostBattle:
	.string "Honestly, the water is too cold for me.\p"
	.string "I'm just trying to look cool.$"

Route125_Text_TanyaIntro:
	.string "Are you headed for the Whirl Islands?$"

Route125_Text_TanyaDefeat:
	.string "Ok! Forget I asked!$"

Route125_Text_TanyaPostBattle:
	.string "I was just going to tell you to be\n"
	.string "careful around the whirlpools...$"

Route125_Text_SharonIntro:
	.string "Lap number 62!\p"
	.string "Hey, don't get in my way!$"

Route125_Text_SharonDefeat:
	.string "Now I've lost count of my laps...$"

Route125_Text_SharonPostBattle:
	.string "I was trying to see how many laps I can\n"
	.string "do around this rock, now I'll have to\l"
	.string "start over...$"

Route125_Text_ErnestIntro:
	.string "How's the fishing going out in the seas\n"
	.string "you ask?\p"
	.string "I'll show you!$"

Route125_Text_ErnestDefeat:
	.string "With your skills, you could make a good\n"
	.string "fisherman...$"

Route125_Text_ErnestPostBattle:
	.string "How's the fishing going out in the seas\n"
	.string "you ask?\p"
	.string "Much better than fishing along some\n"
	.string "river, I assure you.$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV, and I'll let\n"
	.string "you know about great fishing spots.$"

Route125_Text_ErnestRematchIntro:
	.string "If you can defeat me again, I'll tell you\n"
	.string "about a good fishing spot I found!$"

Route125_Text_ErnestRematchDefeat:
	.string "Ok, you should try fishing in Tohjo\n"
	.string "Falls.\p"
	.string "I hear it's the only place in Johto you\n"
	.string "can find Feebas.$"

Route125_Text_ErnestRematchPostBattle:
	.string "Have you tried fishing in Tohjo Falls?\p"
	.string "I hear it's the only place in Johto you\n"
	.string "can find Feebas.$"

Route125_Text_KimIntro:
	.string "EVA: You look like a formidable\n"
	.string "opponent.\p"
	.string "Hey SIRI! Let's show them what we're\n"
	.string "made of!$"

Route125_Text_KimDefeat:
	.string "EVA: That's not the battle I wanted to\n"
	.string "show my junior.$"

Route125_Text_KimPostBattle:
	.string "EVA: Hey SIRI! Remind me to find some\n"
	.string "better POKéMON in the Safari Zone.\p"
	.string "SIRI: I will write that down for you,\n"
	.string "EVA.$"

Route125_Text_KimNotEnoughMons:
	.string "EVA: Excuse me, but you will need more\n"
	.string "than one POKéMON to battle us.$"

Route125_Text_IrisIntro:
	.string "SIRI: My senior taught me how to handle\n"
	.string "TRAINERS like you!$"

Route125_Text_IrisDefeat:
	.string "SIRI: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "EVA: Hey SIRI! Remind me to find some\n"
	.string "better POKéMON in the Safari Zone.\p"
	.string "SIRI: I will write that down for you,\n"
	.string "EVA.$"

Route125_Text_IrisNotEnoughMons:
	.string "SIRI: Excuse me, but you will need more\n"
	.string "than one POKéMON to battle us.$"

Route125_Text_PresleyIntro:
	.string "Did you really just ride on your POKéMON\n"
	.string "out onto this little island?$"

Route125_Text_PresleyDefeat:
	.string "You're a bit tougher than I would like\n"
	.string "to admit.$"

Route125_Text_PresleyPostBattle:
	.string "I'll admit, I'm not much better.\p"
	.string "My bird POKéMON flew me out here.$"

Route125_Text_AuronIntro:
	.string "Don't bug me kid, I'm on the hunt for\n"
	.string "buried treasure!$"

Route125_Text_AuronDefeat:
	.string "Hmm... And I thought I was the expert!$"

Route125_Text_AuronPostBattle:
	.string "I can't find anymore treasure on this\n"
	.string "beach...\p"
	.string "I think I've cleared it all out,\n"
	.string "unfortunately.$"

Route126_Text_BarryIntro:
	.string "Hey! Where did you come from?$"

Route126_Text_BarryDefeat:
	.string "Scared me, and took my money!\n"
	.string "What a jerk!$"

Route126_Text_BarryPostBattle:
	.string "You scared me when you popped out of\n"
	.string "the water!$"

Route126_Text_DeanIntro:
	.string "You can't call yourself an expert\n"
	.string "swimmer unless you swim this far out in\l"
	.string "the ocean!$"

Route126_Text_DeanDefeat:
	.string "I thought swimming would help with my\n"
	.string "POKéMON battling, but I guess not...$"

Route126_Text_DeanPostBattle:
	.string "I think I swam too far from shore...$"

Route126_Text_NikkiIntro:
	.string "Riding on your POKéMON?\p"
	.string "I should have thought of that!$"

Route126_Text_NikkiDefeat:
	.string "Carrying you around must have\n"
	.string "strengthened your POKéMON!$"

Route126_Text_NikkiPostBattle:
	.string "Swimming is great exercise for both\n"
	.string "people and POKéMON!$"

Route126_Text_BrendaIntro:
	.string "My mom told me I could be anything when\n"
	.string "I grow up, but I'm still not a mermaid!$"

Route126_Text_BrendaDefeat:
	.string "Now you've shattered my POKéMON dreams\n"
	.string "as well!$"

Route126_Text_BrendaPostBattle:
	.string "If I keep swimming, will I eventually\n"
	.string "develop fish legs?$"

Route126_Text_PabloIntro:
	.string "So, you've discovered my secret\n"
	.string "training spot?$"

Route126_Text_PabloDefeat:
	.string "Hmm... Maybe you could help with my\n"
	.string "training.$"

Route126_Text_PabloPostBattle:
	.string "I've been treading water here for three\n"
	.string "days!\p"
	.string "I'm not done yet though!$"

Route126_Text_PabloRegister:
	.string "If you ever feel like training with me,\n"
	.string "I'll be here waiting for you...$"

Route126_Text_PabloRematchIntro:
	.string "Back for more training, are you?$"

Route126_Text_PabloRematchDefeat:
	.string "I'm still no match!\p"
	.string "Must train harder!$"

Route126_Text_PabloPostRematch:
	.string "I've been treading water here for five\n"
	.string "days!\p"
	.string "I'm not done yet though!$"

Route126_Text_LeonardoIntro:
	.string "I want to dive for fossils, but I'm\n"
	.string "afraid of the depths!$"

Route126_Text_LeonardoDefeat:
	.string "Whoa, you must not be afraid of\n"
	.string "anything!$"

Route126_Text_LeonardoPostBattle:
	.string "Rare fossils can be found in underwater\n"
	.string "caves, at least that's what I've heard.$"

Route126_Text_IsobelIntro:
	.string "Hmm...\n"
	.string "Which way was back to land again?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "You took advantage of my confusion!\p"
	.string "I would have won if I wasn't distracted.$"

Route126_Text_SiennaIntro:
	.string "It's an ambush!$"

Route126_Text_SiennaDefeat:
	.string "You were prepared for my ambush?\n"
	.string "You must be good!$"

Route126_Text_SiennaPostBattle:
	.string "I should have dove underneath you and\n"
	.string "attacked from below!$"

Route127_Text_CamdenIntro:
	.string "You'll stay warmer if you keep moving!$"

Route127_Text_CamdenDefeat:
	.string "Oh! You got me!$"

Route127_Text_CamdenPostBattle:
	.string "Battling is a good way to keep active,\n"
	.string "and keep your heart rate up.$"

Route127_Text_DonnyIntro:
	.string "Are you looking for a place to ski as\n"
	.string "well?$"

Route127_Text_DonnyDefeat:
	.string "Oh, I guess you just wanted a battle.$"

Route127_Text_DonnyPostBattle:
	.string "I was going to ski here, but I'm afraid\n"
	.string "I'll slide into the water.$"

Route127_Text_JonahIntro:
	.string "Wherever you find water, you will find a\n"
	.string "fisherman!$"

Route127_Text_JonahDefeat:
	.string "Oh, you're too much!$"

Route127_Text_JonahPostBattle:
	.string "I like ice fishing, but the edge of the\n"
	.string "water is pretty slippery.\p"
	.string "I would hate to fall in!$"

Route127_Text_HenryIntro:
	.string "Ice fishing is the best!$"

Route127_Text_HenryDefeat:
	.string "Snagged my line!$"

Route127_Text_HenryPostBattle:
	.string "The water actually stays warmer\n"
	.string "underneath the ice.$"

Route127_Text_RogerIntro:
	.string "Oh! I think I caught a big one!$"

Route127_Text_RogerDefeat:
	.string "Actually, I think my line is just frozen\n"
	.string "to the bottom...$"

Route127_Text_RogerPostBattle:
	.string "I miss fishing on the beach.\p"
	.string "When will it be summer again?$"

Route127_Text_AidanIntro:
	.string "The heat from my POKéMON melted a\n"
	.string "patch of snow!$"

Route127_Text_AidanDefeat:
	.string "You burnt me up!$"

Route127_Text_AidanPostBattle:
	.string "I could melt all the snow in Johto if I\n"
	.string "wanted to.\p"
	.string "That would just be too much walking for\n"
	.string "me...$"

Route127_Text_KojiIntro:
	.string "Training in the snow is harsh, but it\n"
	.string "gives great results!$"

Route127_Text_KojiDefeat:
	.string "I almost slipped off the bridge!$"

Route127_Text_KojiPostBattle:
	.string "I think my feet are frozen solid, but\n"
	.string "it's all a part of Master LEE's special\l"
	.string "training.$"

Route127_Text_KojiRegister:
	.string "You're a tough opponent, we should\n"
	.string "battle again sometime...$"

Route127_Text_KojiRematchIntro:
	.string "I'm still here training, but I do have\n"
	.string "time for another battle!$"

Route127_Text_KojiRematchDefeat:
	.string "Almost slipped off the bridge again!$"

Route127_Text_KojiPostRematch:
	.string "I think my feet are frozen solid, but\n"
	.string "it's all a part of Master LEE's special\l"
	.string "training.$"

Route127_Text_AthenaIntro:
	.string "The cool weather is perfect for a\n"
	.string "COOLTRAINER, don't you agree?$"

Route127_Text_AthenaDefeat:
	.string "You're too cold for me though!$"

Route127_Text_AthenaPostBattle:
	.string "What do you mean a COOLTRAINER doesn't\n"
	.string "have to be in a cool area?$"

Route128_Text_IsaiahIntro:
	.string "104... 105...\p"
	.string "Hey! You made me lose count of my laps!$"

Route128_Text_IsaiahDefeat:
	.string "You're lucky I'm exhausted from\n"
	.string "swimming so many laps...$"

Route128_Text_IsaiahPostBattle:
	.string "How many laps was that again...?$"

Route128_Text_IsaiahRegister:
	.string "You won't be so lucky next time...$"

Route128_Text_IsaiahRematchIntro:
	.string "132... 133...\p"
	.string "I won't lose count of my laps this time!$"

Route128_Text_IsaiahRematchDefeat:
	.string "Lap number...\n"
	.string "Uh... 113?$"

Route128_Text_IsaiahPostRematch:
	.string "Why do I even keep battling you?$"

Route128_Text_KatelynIntro:
	.string "Why ride on your POKéMON when the water\n"
	.string "feels so delightful?$"

Route128_Text_KatelynDefeat:
	.string "You know what isn't delightful...?\n"
	.string "Losing a battle.$"

Route128_Text_KatelynPostBattle:
	.string "There's nothing more delightful than\n"
	.string "swimming in tropical ocean water!$"

Route128_Text_KatelynRegister:
	.string "I can't leave it off like that.\p"
	.string "Give me another chance to win sometime,\n"
	.string "ok.$"

Route128_Text_KatelynRematchIntro:
	.string "There you are!\p"
	.string "This time, I will claim victory!$"

Route128_Text_KatelynRematchDefeat:
	.string "If I claimed victory now, it would just\n"
	.string "be a false claim...$"

Route128_Text_KatelynPostRematch:
	.string "There's nothing more delightful than\n"
	.string "swimming in tropical ocean water!$"

Route128_Text_AlexaIntro:
	.string "Don't think I'll be a pushover just\n"
	.string "because I need floaties to swim!$"

Route128_Text_AlexaDefeat:
	.string "You're mean!\n"
	.string "I'm just a little girl!$"

Route128_Text_AlexaPostBattle:
	.string "Can you swim without an inner tube?$"

Route128_Text_RubenIntro:
	.string "I hope you're wearing enough\n"
	.string "sunscreen!$"

Route128_Text_RubenDefeat:
	.string "Ouch, I still got burned!$"

Route128_Text_RubenPostBattle:
	.string "If you don't have sunscreen, a parasol\n"
	.string "does a pretty good job too.$"

Route128_Text_WayneIntro:
	.string "A fisherman should always bring the\n"
	.string "right rod for the job!$"

Route128_Text_WayneDefeat:
	.string "I should have brought the right\n"
	.string "POKéMON too.$"

Route128_Text_WaynePostBattle:
	.string "The right rod and reel combo are key to\n"
	.string "catching the best fish, trust me!$"

Route128_Text_HarrisonIntro:
	.string "I've been training to hold my breath for\n"
	.string "years.\p"
	.string "My record is five minutes!$"

Route128_Text_HarrisonDefeat:
	.string "Gasp!\p"
	.string "I was holding my breath for that entire\n"
	.string "battle!$"

Route128_Text_HarrisonPostBattle:
	.string "The trick to holding your breath is to\n"
	.string "remain calm.\p"
	.string "Unfortunately, I couldn't remain calm\n"
	.string "during our battle.$"

Route128_Text_CarleeIntro:
	.string "Are you headed to Lazulan City?$"

Route128_Text_CarleeDefeat:
	.string "So harsh!\n"
	.string "I was just asking...$"

Route128_Text_CarleePostBattle:
	.string "The millennium comet only flies by once\n"
	.string "every thousand years!$"

Route129_Text_ChaseIntro:
	.string "Yo kid, where's your board?$"

Route129_Text_ChaseDefeat:
	.string "Chilled to the bone!$"

Route129_Text_ChasePostBattle:
	.string "I scratched up my snowboard when I slid\n"
	.string "onto this path, this is awful!$"

Route129_Text_AllisonIntro:
	.string "Sure, I'll take a quick break from\n"
	.string "skiing!$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "They wouldn't let me into the Rage\n"
	.string "Resort, so I'm skiing around here\l"
	.string "instead.$"

Route129_Text_ReedIntro:
	.string "Did you slide across the ice, or walk\n"
	.string "around?$"

Route129_Text_ReedDefeat:
	.string "I slipped up!$"

Route129_Text_ReedPostBattle:
	.string "The whole Lake of Rage is frozen right\n"
	.string "now, I've heard there are still people\l"
	.string "out on the ice though.$"

Route129_Text_TishaIntro:
	.string "I love skiing almost as much as I love\n"
	.string "battling!$"

Route129_Text_TishaDefeat:
	.string "Well, I guess I don't love losing\n"
	.string "battles...$"

Route129_Text_TishaPostBattle:
	.string "Have you ever tried skiing?$"

Route129_Text_ClarenceIntro:
	.string "I'm practicing for the slopes!$"

Route129_Text_ClarenceDefeat:
	.string "Maybe I should have practiced my\n"
	.string "POKéMON battling instead.$"

Route129_Text_ClarencePostBattle:
	.string "Practice makes perfect.\p"
	.string "That's what I've always heard at least.$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "I think I've been swimming for too long.\p"
	.string "I'm starting to prune!$"

Route131_Text_RichardDefeat:
	.string "I've really lost my edge too.\n"
	.string "Maybe because my skin is all pruney.$"

Route131_Text_RichardPostBattle:
	.string "I heard SILVER was in Lazulan, I wonder\n"
	.string "if he's here for the festival.$"

Route131_Text_HermanIntro:
	.string "Treading water is too boring, let's have\n"
	.string "a battle!$"

Route131_Text_HermanDefeat:
	.string "How could this have happened to me...?$"

Route131_Text_HermanPostBattle:
	.string "Hey, your POKéMON is treading water for\n"
	.string "you.\p"
	.string "That's cheating!$"

Route131_Text_SusieIntro:
	.string "There's a park bench on this little\n"
	.string "island.\p"
	.string "It's a popular makeout spot, hehe...$"

Route131_Text_SusieDefeat:
	.string "Hey, you're pretty tough!$"

Route131_Text_SusiePostBattle:
	.string "My boyfriend took me this island on our\n"
	.string "very first date.\p"
	.string "We watched the sun set along the ocean,\n"
	.string "it was magical!$"

Route131_Text_KaraIntro:
	.string "Don't you think it's a little too warm\n"
	.string "out for a winter coat?$"

Route131_Text_KaraDefeat:
	.string "Ok, I guess I was wrong.\n"
	.string "Whatever works for you!$"

Route131_Text_KaraPostBattle:
	.string "Staying warm like that must amp you up.\p"
	.string "Am I right?$"

Route131_Text_ReliIntro:
	.string "KAT: Don't underestimate us!\p"
	.string "My little brother is stronger than he\n"
	.string "looks!$"

Route131_Text_ReliDefeat:
	.string "KAT: I guess you're stronger than you\n"
	.string "look as well!$"

Route131_Text_ReliPostBattle:
	.string "KAT: I should have figured you were\n"
	.string "strong since you went out of your way\l"
	.string "just to battle us.$"

Route131_Text_ReliNotEnoughMons:
	.string "KAT: Oh, you only have one POKéMON?\p"
	.string "Sorry, but we battle as a team.\p"
	.string "Come back with more POKéMON, and we'll\n"
	.string "battle you!$"

Route131_Text_IanIntro:
	.string "STAN: Don't underestimate us!\p"
	.string "My big sister is really strong!$"

Route131_Text_IanDefeat:
	.string "STAN: I've never seen my sister lose a\n"
	.string "battle, you must be really good!$"

Route131_Text_IanPostBattle:
	.string "STAN: I'm actually not that good at\n"
	.string "swimming yet.\p"
	.string "I'm just holding onto this rock.$"

Route131_Text_IanNotEnoughMons:
	.string "STAN: You look like a strong TRAINER,\n"
	.string "but we only battle as a team.$"

Route131_Text_TaliaIntro:
	.string "You really thought you could slip by me\n"
	.string "unnoticed, huh?$"

Route131_Text_TaliaDefeat:
	.string "Pleh, pleh!\n"
	.string "Some salt water got im my mouth!$"

Route131_Text_TaliaPostBattle:
	.string "I love swimming in the ocean, but can't\n"
	.string "stand the taste of salt water.$"

Route131_Text_KevinIntro:
	.string "I spend most of the day swimming out\n"
	.string "here.\p"
	.string "Do you really think you can beat me on\n"
	.string "my home turf?$"

Route131_Text_KevinDefeat:
	.string "What do you mean, the ocean isn't turf?\n"
	.string "Is that why I lost...?$"

Route131_Text_KevinPostBattle:
	.string "So turf is the top layer of soil along\n"
	.string "with grass?\p"
	.string "I had no idea.\p"
	.string "I'll have to change up my battle intro\n"
	.string "message then...$"

Route132_Text_GilbertIntro:
	.string "What's the furthest you've ever swam\n"
	.string "before?$"

Route132_Text_GilbertDefeat:
	.string "Your skill is too far from my reach!$"

Route132_Text_GilbertPostBattle:
	.string "I once swam all the way from Cianwood\n"
	.string "to Lazulan.\p"
	.string "I wasn't sure I'd make it!$"

Route132_Text_DanaIntro:
	.string "Swimming in the rain is so underrated!$"

Route132_Text_DanaDefeat:
	.string "Wiped out...$"

Route132_Text_DanaPostBattle:
	.string "The rain sounds really cool when you're\n"
	.string "underwater.$"

Route132_Text_RonaldIntro:
	.string "I was hoping to catch a fish, but\n"
	.string "caught a TRAINER instead!$"

Route132_Text_RonaldDefeat:
	.string "Oh no, it seems I'm the one who was\n"
	.string "caught!$"

Route132_Text_RonaldPostBattle:
	.string "Isn't it funny that you can fish for\n"
	.string "MAGIKARP in any pool of water, no\l"
	.string "matter where you are?$"

Route132_Text_KiyoIntro:
	.string "I'll show you the skills I've honed over\n"
	.string "the last ten years!$"

Route132_Text_KiyoDefeat:
	.string "How could this be...?$"

Route132_Text_KiyoPostBattle:
	.string "I've trained relentlessly for the last\n"
	.string "ten years, but lost to someone who\l"
	.string "barely looks older than ten...\p"
	.string "Maybe I should find a new hobby...$"

Route132_Text_MakaylaIntro:
	.string "Don't count me out just because I'm an\n"
	.string "old lady!$"

Route132_Text_MakaylaDefeat:
	.string "Oh, you're too much for this old lady!$"

Route132_Text_MakaylaPostBattle:
	.string "I have a grandson who is just your age!\p"
	.string "I'll introduce you sometime.$"

Route132_Text_JonathanIntro:
	.string "They really need to do something about\n"
	.string "all of this rain, my shoes are soaking\l"
	.string "wet!$"

Route132_Text_JonathanDefeat:
	.string "Hey, chill out!$"

Route132_Text_JonathanPostBattle:
	.string "I like all of the tropical scenery, but\n"
	.string "it never seems to stop raining here.\p"
	.string "It's just awful!$"

Route132_Text_PaxtonIntro:
	.string "Hmm... You look like a spry young\n"
	.string "TRAINER!$"

Route132_Text_PaxtonDefeat:
	.string "I was right, you certainly are spry!$"

Route132_Text_PaxtonPostBattle:
	.string "I wish I was still a spry young lad.\p"
	.string "Hmm... or at least just a couple of\n"
	.string "decades younger...$"

Route132_Text_DarcyIntro:
	.string "Locked onto TRAINER.\p"
	.string "Initiating POKéMON battle!$"

Route132_Text_DarcyDefeat:
	.string "Does not compute!$"

Route132_Text_DarcyPostBattle:
	.string "I'm not really a robot, I'm just acting\n"
	.string "like one...\p"
	.string "Hehe...$"

Route133_Text_FranklinIntro:
	.string "Slow down there, champ!\p"
	.string "Let's have a battle!$"

Route133_Text_FranklinDefeat:
	.string "Wow, I didn't realize you actually were a\n"
	.string "Champion.$"

Route133_Text_FranklinPostBattle:
	.string "You sure are strong, it's no wonder you\n"
	.string "became a Champion.$"

Route133_Text_DebraIntro:
	.string "You're not getting tired of the ocean\n"
	.string "yet, are you?$"

Route133_Text_DebraDefeat:
	.string "Darn, I was hoping you were tired\n"
	.string "enough for me to beat you.$"

Route133_Text_DebraPostBattle:
	.string "You're lucky.\p"
	.string "If you get too tired, you can just have\n"
	.string "your POKéMON fly you back to land.$"

Route133_Text_LindaIntro:
	.string "Are you here to see GOLD'S private\n"
	.string "island as well?$"

Route133_Text_LindaDefeat:
	.string "Hey, you might actually be a match for\n"
	.string "GOLD.$"

Route133_Text_LindaPostBattle:
	.string "I wish I could live here with GOLD, that\n"
	.string "would be like a dream come true!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Did you get carried away by the rapids\n"
	.string "too?$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I was exploring the Whirl Islands, but\n"
	.string "then got too close to the rapids.$"

Route134_Text_LaurelIntro:
	.string "I rode the rapids too far, now I can't go\n"
	.string "back!$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "If only I had a POKéMON that could dive\n"
	.string "underneath the rapids, I might be able\l"
	.string "to get back then...$"

Route134_Text_AlexIntro:
	.string "I don't know how I wound up with this\n"
	.string "group, but I must protect this item!$"

Route134_Text_AlexDefeat:
	.string "I'm a failure as a guardian.$"

Route134_Text_AlexPostBattle:
	.string "You didn't take the item, did you?$"

Route134_Text_HitoshiIntro:
	.string "You dare step foot upon this small sand\n"
	.string "island!?\p"
	.string "We must now do battle!$"

Route134_Text_HitoshiDefeat:
	.string "I concede... This island is yours...$"

Route134_Text_HitoshiPostBattle:
	.string "I was sharing this island anyway, it\n"
	.string "wasn't mine alone...$"

Route134_Text_AaronIntro:
	.string "Kiyah! I hope you're ready for a kick to\n"
	.string "the throat!$"

Route134_Text_AaronDefeat:
	.string "I have been defeated...\n"
	.string "Please, kick my throat instead...$"

Route134_Text_AaronPostBattle:
	.string "Perhaps life isn't just about endless\n"
	.string "kicking...$"

Route134_Text_KelvinIntro:
	.string "I joined this little group because it\n"
	.string "looked like it would be fun!$"

Route134_Text_KelvinDefeat:
	.string "Win or lose, I still had fun.$"

Route134_Text_KelvinPostBattle:
	.string "We used to run in circles around this\n"
	.string "island, but we all got stuck behind the\l"
	.string "first person that stopped.\p"
	.string "This pattern is much more effective.$"

Route134_Text_MarleyIntro:
	.string "My Hitmonchan's punches are too fast,\n"
	.string "you'll never see them coming!$"

Route134_Text_MarleyDefeat:
	.string "I guess a Hitmonchan throwing punches\n"
	.string "is pretty obvious...$"

Route134_Text_MarleyPostBattle:
	.string "Don't tell the guy next to me, but\n"
	.string "punches are way better than kicks!$"

Route134_Text_ReynaIntro:
	.string "I don't even want this little island!$"

Route134_Text_ReynaDefeat:
	.string "Were you not challenging me for the\n"
	.string "island?$"

Route134_Text_ReynaPostBattle:
	.string "I landed on this little island, and this\n"
	.string "man challenged me to a battle.\p"
	.string "He said we can share it since I beat him.$"

Route134_Text_HudsonIntro:
	.string "These rapids will take you all the way\n"
	.string "to Goldenrod City!$"

Route134_Text_HudsonDefeat:
	.string "You seem to know what you're doing.$"

Route134_Text_HudsonPostBattle:
	.string "Don't ride the rapids too far, or you may\n"
	.string "not make it back.$"
