Route102_Text_CalvinIntro:
	.string "Stop right there!\p"
	.string "I've locked eyes with you, that means\n"
	.string "we must have a POKéMON battle, there is\l"
	.string "no way around it!$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, I lost…\n"
	.string "I should have trained mine more…$"

Route102_Text_CalvinPostBattle:
	.string "Yes, you do seem strong. You may be\n"
	.string "worthy enough to be my rival.$"

Route102_Text_CalvinRegister:
	.string "I've been working hard at this since\n"
	.string "I saw you before, my rival.\p"
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, I lost…\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you're going to get stronger,\n"
	.string "I'll get stronger too, my rival.$"

Route102_Text_AllenIntro:
	.string "Did you just become a TRAINER?\n"
	.string "I can totally beat a kid like you!$"

Route102_Text_AllenDefeated:
	.string "I called you out because I thought\n"
	.string "I could beat you…$"

Route102_Text_AllenPostBattle:
	.string "I haven't won once yet…\n"
	.string "I wish I would win soon…$"

Route102_Text_RickIntro:
	.string "You don't like bugs?\n"
	.string "Well that's too bad, because I love\l"
	.string "bugs!$"

Route102_Text_RickDefeated:
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:
	.string "You should have known better than to\n"
	.string "walk in front of me, I will defeat you\l"
	.string "now!$"

Route102_Text_TianaDefeated:
	.string "How could I lose…$"

Route102_Text_TianaPostBattle:
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Did you feel the tug of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_DaisyDefeated:
	.string "You weren't led astray by our aroma…$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_AmyIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyDefeated:
	.string "AMY: Uh-oh, we lost.$"

Route103_Text_AmyPostBattle:
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivIntro:
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh, we lost, big sister…$"

Route103_Text_LivPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: If you want to battle us,\n"
	.string "you have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, boo!\n"
	.string "We couldn't win again…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivRematchIntro:
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: If you want to battle us, you\n"
	.string "have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AndrewIntro:
	.string "Gah! My fishing line's all snarled up!\n"
	.string "I'm getting frustrated and mean!\l"
	.string "That's it! Battle me!$"

Route103_Text_AndrewDefeated:
	.string "Gah! Lost it!\n"
	.string "I'm even more annoyed now!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, I'm still boiling mad…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "My POKéMON is delightfully adorable!\n"
	.string "Don't be shy--I'll show you!$"

Route103_Text_MiguelDefeated:
	.string "Oh, my gosh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "My delightful POKéMON looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_MiguelRegister:
	.string "I'll get you to come out and look in\n"
	.string "on my delightful POKéMON again!$"

Route103_Text_MiguelRematchIntro:
	.string "Hi, you! My delightfully adorable\n"
	.string "POKéMON has become more darling!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "The more I spend time with it,\n"
	.string "the more adorable my POKéMON becomes.$"

Route103_Text_PeteIntro:
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_PeteDefeated:
	.string "Oh, that's good going!$"

Route103_Text_PetePostBattle:
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I'd want to SURF on it, too!$"

Route103_Text_IsabelleIntro:
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_IsabelleDefeated:
	.string "Groan…$"

Route103_Text_IsabellePostBattle:
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "How'd you get into a space this small?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "The kid can rock!$"

Route103_Text_RhettPostBattle:
	.string "Do you like cramped quarters\n"
	.string "like this?$"

Route103_Text_MarcosIntro:
	.string "Did my guitar's wailing draw you in?$"

Route103_Text_MarcosDefeated:
	.string "My one-man show is ruined…$"

Route103_Text_MarcosPostBattle:
	.string "I was playing my guitar where few\n"
	.string "people were around, but a lot of fans\l"
	.string "have gathered.\p"
	.string "Heh, maybe I should turn pro.$"

Route104_Text_GinaIntro:
	.string "TINA: Are you prepared for a double\n"
	.string "battle?$"

Route104_Text_GinaDefeat:
	.string "TINA: Losing upsets me!$"

Route104_Text_GinaPostBattle:
	.string "TINA: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_GinaNotEnoughMons:
	.string "TINA: Oh, it looks like you aren't\n"
	.string "prepared for a double battle.\p"
	.string "You will need more than one POKéMON.$"

Route104_Text_MiaIntro:
	.string "MAI: Us twins do everything\n"
	.string "together, even POKéMON battles!$"

Route104_Text_MiaDefeat:
	.string "MAI: We battled together, but we\n"
	.string "both lost…$"

Route104_Text_MiaPostBattle:
	.string "MAI: We will train our POKéMON more\n"
	.string "and be strong like you.$"

Route104_Text_MiaNotEnoughMons:
	.string "MAI: Sorry, but you will have to bring\n"
	.string "more POKéMON if you want to battle us.$"

Route104_Text_IvanIntro:
	.string "I'm one of the best fishermen around.\p"
	.string "What?\p"
	.string "You don't believe me?$"

Route104_Text_IvanDefeat:
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON…$"

Route104_Text_BillyIntro:
	.string "Hey, you look like a weakling!\p"
	.string "This will be easy.$"

Route104_Text_BillyDefeat:
	.string "You should have told me you weren't a\n"
	.string "weakling.$"

Route104_Text_BillyPostBattle:
	.string "I'm looking for weak TRAINERS to battle\n"
	.string "to practice on.$"

Route104_Text_HaleyIntro:
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will battle!$"

Route104_Text_HaleyDefeat:
	.string "I shouldn't have battled…$"

Route104_Text_HaleyPostBattle:
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for you,\l"
	.string "you will regret it, however things\l"
	.string "turn out.$"

Route104_Text_HaleyRegister1:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRegister2:
	.string "You're strong, but should I register\n"
	.string "you in my POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_HaleyPostRematch:
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro:
	.string "Oh, sure, I'll accept your challenge.\n"
	.string "You don't look very tough to me.$"

Route104_Text_WinstonDefeat:
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostBattle:
	.string "You're tougher than you look, but can\n"
	.string "you survive camping in Mt. Mortar?$"

Route104_Text_WinstonRegister1:
	.string "...\p"
	.string "What's that?\p"
	.string "You want to register me in your\n"
	.string "POKéNAV?$"

Route104_Text_WinstonRegister2:
	.string "...\p"
	.string "What's that?\p"
	.string "You want to register me in your\n"
	.string "POKéNAV?$"

Route104_Text_WinstonRematchIntro:
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch:
	.string "You're tougher than you look, but can\n"
	.string "you survive camping in Mt. Silver?$"

Route104_Text_CindyIntro:
	.string "Maybe you can satisfy my need for a\n"
	.string "strong opponent, my boyfriend never\l"
	.string "puts up much of a challenge.$"

Route104_Text_CindyDefeat:
	.string "Oh, my!$"

Route104_Text_CindyPostBattle:
	.string "You sure know how to please a woman.$"

Route104_Text_CindyRegister1:
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "That was so much fun!\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hello, we meet again.\n"
	.string "Will you satisfy my needs this time?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, my…\n"
	.string "Consider me satisfied…$"

Route104_Text_CindyPostRematch:
	.string "That was fun, we should do this again\n"
	.string "sometime.$"

Route104_Text_DarianIntro:
	.string "You can fish up better POKéMON with\n"
	.string "better rods.\p"
	.string "Let me show you!$"

Route104_Text_DarianDefeat:
	.string "What the…$"

Route104_Text_DarianPostBattle:
	.string "I guess you had the better POKéMON.$"

Route105_Text_FosterIntro:
	.string "Are you headed to Mt. Mortar?\p"
	.string "It's my favorite mountain by far!$"

Route105_Text_FosterDefeated:
	.string "I should have concentrated more on our\n"
	.string "battle.$"

Route105_Text_FosterPostBattle:
	.string "I've heard Mt. Silver is also a nice\n"
	.string "mountain, but very few are allowed\l"
	.string "there.$"

Route105_Text_LuisIntro:
	.string "Hmph, I say, you look like you're\n"
	.string "prepared for a battle!$"

Route105_Text_LuisDefeated:
	.string "Quite prepared indeed...$"

Route105_Text_LuisPostBattle:
	.string "A gentleman such as myself only battles\n"
	.string "TRAINERS who appear well learned in\l"
	.string "the art of POKéMON battles.$"

Route105_Text_DominikIntro:
	.string "I'll show you the best POKéMON money\n"
	.string "can buy!$"

Route105_Text_DominikDefeated:
	.string "No, I paid so much for that Porygon!\n"
	.string "I want a refund.$"

Route105_Text_DominikPostBattle:
	.string "I tried to purchase the Dance Theater in\n"
	.string "Ecruteak, but they told me it's not for\l"
	.string "sale.\p"
	.string "The nerve of those people!$"

Route105_Text_BeverlyIntro:
	.string "Go, my adorable POKéMON!$"

Route105_Text_BeverlyDefeated:
	.string "I guess cuteness doesn't win POKéMON\n"
	.string "battles...$"

Route105_Text_PostBattle:
	.string "I was training up my cute little\n"
	.string "ELECTRIC-type POKéMON to take on\l"
	.string "WATARU, but it seems they aren't ready\l"
	.string "yet.$"

Route105_Text_ImaniIntro:
	.string "I was just out for a stroll, but I\n"
	.string "suppose I have time for a quick battle!$"

Route105_Text_ImaniDefeated:
	.string "Perhaps I should have chosen an easier\n"
	.string "opponent...$"

Route105_Text_ImaniPostBattle:
	.string "Have you been to the Dance Theater in\n"
	.string "Ecruteak?\p"
	.string "I wish I could be like those girls.$"

Route105_Text_AndresIntro:
	.string "Fwahahaha! Hiking is the best!$"

Route105_Text_AndresDefeated:
	.string "I'm a better hiker than a battler,\n"
	.string "trust me.$"

Route105_Text_AndresPostBattle:
	.string "I've hiked every mountain in Johto, now\n"
	.string "I have my sights set on Mt. Tempest in\l"
	.string "the Golden Islands...$"

Route105_Text_AndresRegister:
	.string "Register me in your POKéNAV so I can\n"
	.string "tell you all about the greatness of\l"
	.string "hiking later!$"

Route105_Text_AndresRematchIntro:
	.string "Have you found an appreciation for\n"
	.string "hiking yet?$"

Route105_Text_AndresRematchDefeated:
	.string "You're still a good battler I see.$"

Route105_Text_AndresRematchPostBattle:
	.string "Have you been to Mt. Tempest?\p"
	.string "I've heard very strong TRAINERS visit\n"
	.string "there.$"

Route105_Text_JosueIntro:
	.string "Birds are real, and I will prove it to\n"
	.string "you!$"

Route105_Text_JosueDefeated:
	.string "Are any of us real...?$"

Route105_Text_JosuePostBattle:
	.string "This could all be a simulation!\p"
	.string "Just look at that hiker, I haven't seen\n"
	.string "him blink once!$"

Route106_Text_ElliotIntro:
	.string "Which do you prefer, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_ElliotDefeated:
	.string "Like in deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_ElliotRegister:
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro:
	.string "I caught a bunch of POKéMON fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated:
	.string "I lost again spectacularly!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Win or lose, POKéMON are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro:
	.string "That guy over there is hogging the best\n"
	.string "fishing spot!$"

Route106_Text_NedDefeated:
	.string "I lost out on the good fishing spot and\n"
	.string "this battle.$"

Route106_Text_NedPostBattle:
	.string "Maybe that other fisherman will leave\n"
	.string "soon, and I can have my spot back.$"

Route106_Text_DouglasIntro:
	.string "My super BUG POKéMON will have you\n"
	.string "begging for mercy!$"

Route106_Text_DouglasDefeated:
	.string "I give up!$"

Route106_Text_DouglasPostBattle:
	.string "I wouldn't lose in a bug catching\n"
	.string "contest.$"

Route106_Text_KylaIntro:
	.string "Ick! I hate bugs!\p"
	.string "That's almost all that's in this grass.$"

Route106_Text_KylaDefeated:
	.string "Squashed, like a bug.$"

Route106_Text_KylaPostBattle:
	.string "There's a bug catcher over by the DARK\n"
	.string "CAVE entrance, bug catchers give me\l"
	.string "the creeps.$"

Route107_Text_DarrinIntro:
	.string "Did you come here from Goldenrod City?\p"
	.string "I will show you the power of a true\n"
	.string "POKéMON fan!$"

Route107_Text_DarrinDefeated:
	.string "Oh, you must be a bigger POKéMON fan\n"
	.string "than I am.$"

Route107_Text_DarrinPostBattle:
	.string "Have you been to the POKéMON Fan Club\n"
	.string "in Goldenrod City?$"

Route107_Text_TonyIntro:
	.string "I'll show you the awesome BUG-type\n"
	.string "POKéMON I just caught!$"

Route107_Text_TonyDefeated:
	.string "Maybe I should train my Pinsir before\n"
	.string "battling with it.$"

Route107_Text_TonyPostBattle:
	.string "Have you been into the National Park\n"
	.string "yet?\p"
	.string "They have all kinds of awesome\n"
	.string "BUG-type POKéMON!$"

Route107_Text_TonyRegister:
	.string "Here, register me in your POKéNAV so I\n"
	.string "can tell you more about what makes\l"
	.string "BUGS awesome!$"

Route107_Text_TonyRematchIntro:
	.string "Let me show you how much my Pinsir has\n"
	.string "grown!$"

Route107_Text_TonyRematchDefeated:
	.string "I guess I haven't grown my Pinsir\n"
	.string "enough yet...$"

Route107_Text_TonyRematchPostBattle:
	.string "Have you been into the National Park\n"
	.string "yet?\p"
	.string "They have all kinds of awesome\n"
	.string "BUG-type POKéMON!$"

Route107_Text_DeniseIntro:
	.string "Go! All of my cute babies!$"

Route107_Text_DeniseDefeated:
	.string "No! My babies!$"

Route107_Text_DenisePostBattle:
	.string "My babies like to come here and check\n"
	.string "out the weird tree.$"

Route107_Text_BethIntro:
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_BethDefeated:
	.string "I wasn't good enough for you.$"

Route107_Text_BethPostBattle:
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_LisaIntro:
	.string "LISA: Hey! You found our secret\n"
	.string "make-out spot!$"

Route107_Text_LisaDefeated:
	.string "LISA: Way to ruin the mood...$"

Route107_Text_LisaPostBattle:
	.string "LISA: Go find your own make-out spot.\p"
	.string "This one is taken.$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Only one POKéMON?\p"
	.string "That's pretty ballsy, but we always\n"
	.string "battle as a team.$"

Route107_Text_RayIntro:
	.string "RAY: Oh come on, read the room kid!$"

Route107_Text_RayDefeated:
	.string "RAY: My disappointment is immeasurable,\n"
	.string "and my day is ruined.$"

Route107_Text_RayPostBattle:
	.string "RAY: I found this nice secluded area to\n"
	.string "make-out with my girlfriend, but you\l"
	.string "just had to come along and ruin it.$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Just one POKéMON?\p"
	.string "You've got guts kid, now get out of\n"
	.string "here.$"

Route107_Text_CamronIntro:
	.string "I'm training for a huge triathlon, help\n"
	.string "me train my POKéMON too!$"

Route107_Text_CamronDefeated:
	.string "That exhausted me…$"

Route107_Text_CamronPostBattle:
	.string "My POKéMON might not be ready, but I\n"
	.string "think I am.$"

Route108_Text_JeromeIntro:
	.string "You didn't buy anything from that shady\n"
	.string "looking guy, did you?$"

Route108_Text_JeromeDefeated:
	.string "You rocked my world...$"

Route108_Text_JeromePostBattle:
	.string "I thought you would be an easy win\n"
	.string "since you fell for that shady guys\l"
	.string "sales pitch.$"

Route108_Text_MatthewIntro:
	.string "Take flight, my bird POKéMON!$"

Route108_Text_MatthewDefeated:
	.string "No!\n"
	.string "Knocked back down to earth!$"

Route108_Text_MatthewPostBattle:
	.string "Flight allows birds to experience\n"
	.string "freedom like no human can.$"

Route108_Text_TaraIntro:
	.string "It never stops raining on this route,\n"
	.string "it's so much fun!$"

Route108_Text_TaraDefeated:
	.string "Oh, boo!$"

Route108_Text_TaraPostBattle:
	.string "Have you been down into the Slowpoke\n"
	.string "Well?\p"
	.string "It's so damp and cozy.$"

Route108_Text_MissyIntro:
	.string "I'm out here training to reduce my\n"
	.string "stress!$"

Route108_Text_MissyDefeated:
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_MissyPostBattle:
	.string "Work off your stress by exercising!\n"
	.string "It's so healthy!$"

Route108_Text_CoryIntro:
	.string "Hiyah!\p"
	.string "I will show you the result of years of\n"
	.string "training!$"

Route108_Text_CoryDefeated:
	.string "Maybe the quality of one's training\n"
	.string "matters as well...$"

Route108_Text_CoryPostBattle:
	.string "It seems I need more quality training.$"

Route108_Text_CoryRegister:
	.string "I love tough TRAINERS,\n"
	.string "Register me in your POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Win or lose, I love battling!$"

Route108_Text_CoryRematchDefeated:
	.string "Defeated yet again...$"

Route108_Text_CoryRematchPostBattle:
	.string "It seems I need more quality training.$"

Route108_Text_CarolinaIntro:
	.string "I take huge pride in my cute POKéMON.\n"
	.string "We'll show you an adorable battle!$"

Route108_Text_CarolinaDefeated:
	.string "That wasn't cute at all.$"

Route108_Text_CarolinaPostBattle:
	.string "Cute POKéMON are my favorite, what kind\n"
	.string "is your favorite?$"

Route109_Text_DavidIntro:
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Flubbed out!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "with POKéMON battles!$"

Route109_Text_AliceIntro:
	.string "Yeehaw! Show me what you've got!$"

Route109_Text_AliceDefeated:
	.string "You're not too bad for a city slicker!$"

Route109_Text_AlicePostBattle:
	.string "Life on the farm can be more\n"
	.string "entertaining than you think!$"

Route109_Text_HueyIntro:
	.string "Me crewmates sailed off without me, now\n"
	.string "I'm mad!$"

Route109_Text_HueyDefeated:
	.string "That didn't help, now I'm even more\n"
	.string "angry!$"

Route109_Text_HueyPostBattle:
	.string "Maybe I'll go to the sweet shop in\n"
	.string "Olivine and cool my head.$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Battle? With me?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "I'm usually stronger than this!\n"
	.string "I'm just seasick as a dog!\p"
	.string "I'm a SAILOR, but…$"

Route109_Text_RickyIntro:
	.string "Headed to Olivine, are you?$"

Route109_Text_RickyDefeated:
	.string "Say, you're not half bad!$"

Route109_Text_RickyPostBattle:
	.string "Olivine has to be one of my favorite\n"
	.string "port towns, for sure.$"

Route109_Text_RickyRegister:
	.string "How about another match sometime?$"

Route109_Text_RickyRematchIntro:
	.string "You showed up at the perfect time, I\n"
	.string "was itching for another match!$"

Route109_Text_RickyRematchDefeated:
	.string "Good match, good match.$"

Route109_Text_RickyRematchPostBattle:
	.string "Olivine has to be one of my favorite\n"
	.string "port towns, by a long shot!$"

Route109_Text_LolaIntro:
	.string "Your hands aren't calloused at all!\p"
	.string "You wouldn't last 2 seconds on the\n"
	.string "farm!$"

Route109_Text_LolaDefeated:
	.string "No fair, your POKéMON did all the work\n"
	.string "for you!$"

Route109_Text_LolaPostBattle:
	.string "Farm life is tough, but I wouldn't trade\n"
	.string "it for the world!$"

Route109_Text_LolaRegister:
	.string "You may not be rugged, but your POKéMON\n"
	.string "sure are.\p"
	.string "I wouldn't mind battling you again\n"
	.string "sometime...$"

Route109_Text_LolaRematchIntro:
	.string "Hey! I think I'm starting to see little\n"
	.string "callouses forming on your hands!$"

Route109_Text_LolaRematchDefeated:
	.string "Your POKéMON sure are tough!$"

Route109_Text_LolaRematchPostBattle:
	.string "I'm going to put your POKéMON to work\n"
	.string "on the farm!$"

Route109_Text_AustinaIntro:
	.string "Saddle up partner!$"

Route109_Text_AustinaDefeated:
	.string "No! I fell off!$"

Route109_Text_AustinaPostBattle:
	.string "You know what they say, if you fall off\n"
	.string "your Ponyta, you've gotta get back on!$"

Route109_Text_GwenIntro:
	.string "Hi, big TRAINER.\n"
	.string "Will you battle with me?$"

Route109_Text_GwenDefeated:
	.string "Oh, you're strong.$"

Route109_Text_GwenPostBattle:
	.string "How did you get to be so strong?$"

Route109_Text_CarterIntro:
	.string "Aah! I broke my rod reeling in a big one!\p"
	.string "Now I'm going to take my anger out on\n"
	.string "you!$"

Route109_Text_CarterDefeated:
	.string "Broke my rod, and now my spirit...$"

Route109_Text_CarterPostBattle:
	.string "What do you want now?\p"
	.string "What else will you take from me?$"

Route109_Text_PaulIntro:
	.string "PAUL: Really kid? You want a battle now\n"
	.string "of all times?$"

Route109_Text_PaulDefeated:
	.string "PAUL: Well that's just great!$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Hey, uh, could you leave us alone\n"
	.string "now?$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Really kid? You want a battle now\n"
	.string "of all times?\p"
	.string "...\p"
	.string "You don't even have two POKéMON!\p"
	.string "Get lost!$"

Route109_Text_MelIntro:
	.string "MEL: I'll show you what true love is\n"
	.string "capable of!$"

Route109_Text_MelDefeated:
	.string "MEL: Oh no... Is our love not true?$"

Route109_Text_MelPostBattle:
	.string "MEL: PAUL is so possessive, but I love\n"
	.string "it!$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: I'll show you what true love is\n"
	.string "capable of!\p"
	.string "...\p"
	.string "When you bring more POKéMON that is...$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! See?\n"
	.string "My inner tube's round!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Too bad!$"

Route109_Text_ChandlerPostBattle:
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_HaileyIntro:
	.string "I'll show you what it means to be farm\n"
	.string "tough!$"

Route109_Text_HaileyDefeated:
	.string "How could this happen?$"

Route109_Text_HaileyPostBattle:
	.string "Farm life toughens a person up, y'all\n"
	.string "city folk just don't get it.$"

Route109_Text_ElijahIntro:
	.string "Let me show you what it means to rock!$"

Route109_Text_ElijahDefeated:
	.string "I got rolled!$"

Route109_Text_ElijahPostBattle:
	.string "One day, I hope to join The\n"
	.string "Thunderbolts, and play around the\l"
	.string "world!$"

Route110_Text_JacobIntro:
	.string "Whoa! Watch it!\n"
	.string "I guess you're not used to BIKE racing.$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_JacobPostBattle:
	.string "Flat tires and brake problems can\n"
	.string "cause serious injury!\l"
	.string "Inspect your BIKE for problems!$"

Route110_Text_AnthonyIntro:
	.string "Yo, you!\n"
	.string "Can you keep up with my speed?$"

Route110_Text_AnthonyDefeated:
	.string "Crash and burn!$"

Route110_Text_AnthonyPostBattle:
	.string "Speed alone won't let me win at POKéMON.\n"
	.string "I need to reconsider this…$"

Route110_Text_BenjaminIntro:
	.string "Don't panic if your BIKE's going fast!$"

Route110_Text_BenjaminDefeated:
	.string "I shouldn't panic during POKéMON\n"
	.string "battles…$"

Route110_Text_BenjaminPostBattle:
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_BenjaminRegister:
	.string "I'll keep chugging on without stressing.\n"
	.string "Give me a shout if you're up to it.$"

Route110_Text_BenjaminRematchIntro:
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_BenjaminRematchDefeated:
	.string "I didn't panic, but I still lost…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_AbigailIntro:
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to complete the three events\n"
	.string "of swimming, cycling, and running.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON battles are hard, too!$"

Route110_Text_AbigailPostBattle:
	.string "I'm exhausted, so I need a break.\n"
	.string "It's important to get proper rest.$"

Route110_Text_AbigailRegister:
	.string "You know, I like you!\n"
	.string "Let's have a rematch on CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "How could you be so strong?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro:
	.string "I've been riding without stopping.\n"
	.string "My thighs are like rocks!$"

Route110_Text_JasmineDefeated:
	.string "I'm worried about muscle cramps…$"

Route110_Text_JasminePostBattle:
	.string "Oh, you have some GYM BADGES?\n"
	.string "No wonder you're so strong!$"

Route110_Text_EdwardIntro:
	.string "I have foreseen your intentions!\n"
	.string "I cannot possibly lose!$"

Route110_Text_EdwardDefeated:
	.string "I failed to prophesize my own demise!$"

Route110_Text_EdwardPostBattle:
	.string "I see your future…\p"
	.string "Hmm…\n"
	.string "I see a shining light…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "I'll dazzle you with my wonders!$"

Route110_Text_JaclynDefeated:
	.string "I wondrously lost!$"

Route110_Text_JaclynPostBattle:
	.string "You managed to win only because it was\n"
	.string "a wonder! Yes, a wonder!\l"
	.string "Don't think you can win all the time!$"

Route110_Text_EdwinIntro:
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinDefeated:
	.string "I wanted to complete\n"
	.string "my collection…$"

Route110_Text_EdwinPostBattle:
	.string "When I see a POKéMON that I don't know,\n"
	.string "my passion as a collector is ignited!$"

Route110_Text_EdwinRegister:
	.string "I like collecting MATCH CALL\n"
	.string "registrations, too…$"

Route110_Text_EdwinRematchIntro:
	.string "Hi, have you caught any new POKéMON?\p"
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinRematchDefeated:
	.string "Your POKéMON…\n"
	.string "I envy you.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, I long to make all rare POKéMON\n"
	.string "mine!$"

Route110_Text_DaleIntro:
	.string "Hey!\n"
	.string "Don't sneak up behind me like that!$"

Route110_Text_DaleDefeated:
	.string "I lost!\n"
	.string "Drat!$"

Route110_Text_DalePostBattle:
	.string "Fishing is all about concentration.\n"
	.string "You have to focus on the floater.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! I would go anywhere to show\n"
	.string "off my delightful POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelPostBattle:
	.string "Rather than battling, perhaps I should\n"
	.string "show off my POKéMON at the FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "That wasn't close to what I could\n"
	.string "do to show off my POKéMON.\p"
	.string "I'll have you as my captive audience\n"
	.string "as often as possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my POKéMON as often as you like!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelRematchPostBattle:
	.string "I don't think that I could ever stop\n"
	.string "from showing off my POKéMON.\p"
	.string "But I like to battle, too!$"

Route110_Text_TimmyIntro:
	.string "I found some cool POKéMON in the grass\n"
	.string "around here!$"

Route110_Text_TimmyDefeated:
	.string "Being cool isn't enough to win…$"

Route110_Text_TimmyPostBattle:
	.string "It's hard to battle with POKéMON you\n"
	.string "just caught.$"

Route110_Text_AlyssaIntro:
	.string "I fell off CYCLING ROAD…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling with you!$"

Route110_Text_AlyssaDefeated:
	.string "Oops!\n"
	.string "I ended up losing!$"

Route110_Text_AlyssaPostBattle:
	.string "Falling… Losing…\n"
	.string "This is so humiliating for me!$"

Route110_Text_JosephIntro:
	.string "Okay! Full-throttle time! If you can't\n"
	.string "groove, you get left behind!$"

Route110_Text_JosephDefeated:
	.string "You got into the groove all right…$"

Route110_Text_JosephPostBattle:
	.string "This isn't going to bring me down!\n"
	.string "Losing has made me a better man!$"

Route110_Text_KalebIntro:
	.string "When cute POKéMON help each other…\n"
	.string "You won't see a more adorable sight!$"

Route110_Text_KalebDefeated:
	.string "Have you no compassion or pity?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, you've done the best you\n"
	.string "could, my pretties.$"

Route111_Text_DrewIntro:
	.string "Oh, hey! Those GO-GOGGLES suit you.\n"
	.string "But I think they look better on me.\p"
	.string "Let's decide who they look better on\n"
	.string "with a battle!$"

Route111_Text_DrewDefeat:
	.string "I couldn't see what was happening at\n"
	.string "my sides because of the GO-GOGGLES.$"

Route111_Text_DrewPostBattle:
	.string "The GO-GOGGLES make it possible to\n"
	.string "get through sandstorms.\l"
	.string "That makes me happy!$"

Route111_Text_HeidiIntro:
	.string "I'm having a picnic in the desert.\p"
	.string "You can always find a TRAINER,\n"
	.string "so I can enjoy a battle here, too!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! You're mean!$"

Route111_Text_HeidiPostBattle:
	.string "When you're battling in a sandstorm,\n"
	.string "watch out for your POKéMON's HP.\p"
	.string "It can faint if you don't keep\n"
	.string "an eye on it!$"

Route111_Text_BeauIntro:
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a superhero.\l"
	.string "Right now, nobody can beat me!$"

Route111_Text_BeauDefeat:
	.string "I can't win on spirit alone…$"

Route111_Text_BeauPostBattle:
	.string "I'm going to be a real hero one day.\n"
	.string "I'm going to work harder to make me\l"
	.string "and my POKéMON stronger.$"

Route111_Text_BeckyIntro:
	.string "I heard there are fossils to be found\n"
	.string "in the desert. Where could they be?$"

Route111_Text_BeckyDefeat:
	.string "I came up short…$"

Route111_Text_BeckyPostBattle:
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_DustyIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\l"
	.string "I am to be challenged?$"

Route111_Text_DustyDefeat:
	.string "While I have searched for ruins,\n"
	.string "I've not searched for strong POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Which was it now?$"

Route111_Text_DustyRegister:
	.string "I haven't been searching for any\n"
	.string "tough POKéMON.\p"
	.string "But, for some reason, I sure do like\n"
	.string "POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat:
	.string "I've found no ruins, nor have I found\n"
	.string "any strong POKéMON…$"

Route111_Text_DustyPostRematch:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years\n"
	.string "I've searched?\p"
	.string "Hmm… It could even be fifty…\n"
	.string "How long have I been at this?$"

Route111_Text_TravisIntro:
	.string "I'm full of pep!\n"
	.string "And my POKéMON is peppy, too!$"

Route111_Text_TravisDefeat:
	.string "My POKéMON lost its pep…$"

Route111_Text_TravisPostBattle:
	.string "When I see a TRAINER with a lot of pep,\n"
	.string "I can't help looking.$"

Route111_Text_IreneIntro:
	.string "I don't know where you're going,\n"
	.string "but would you like to battle?$"

Route111_Text_IreneDefeat:
	.string "Oh, you're disgustingly good!$"

Route111_Text_IrenePostBattle:
	.string "I'm thinking that I should go to\n"
	.string "MT. CHIMNEY, but the view around\l"
	.string "here is very nice, too.$"

Route111_Text_DaisukeIntro:
	.string "To train myself, I challenge all\n"
	.string "whom I meet!$"

Route111_Text_DaisukeDefeat:
	.string "Uncle! I give up!$"

Route111_Text_DaisukePostBattle:
	.string "All I can do is keep training until\n"
	.string "I can defeat strong TRAINERS such\l"
	.string "as yourself.$"

Route111_Text_WiltonIntro:
	.string "Show me how much you've toughened\n"
	.string "your POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON and TRAINERS learn much\n"
	.string "through battling.\p"
	.string "What's important is to never give up\n"
	.string "even if you lose.$"

Route111_Text_WiltonRegister:
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_WiltonRematchIntro:
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:
	.string "Since you're that strong, you should\n"
	.string "aim for the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "Oh, your POKéMON look like serious\n"
	.string "actors.\l"
	.string "I have to ask you for an engagement.$"

Route111_Text_BrookeDefeat:
	.string "They didn't just look strong,\n"
	.string "they are strong!$"

Route111_Text_BrookePostBattle:
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but, oh no, there is still\l"
	.string "much to be done.$"

Route111_Text_BrookeRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "You can make POKéMON stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your POKéMON\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat:
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should have stopped my\n"
	.string "POKéMON from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_CeliaIntro:
	.string "I shouldn't have come to a place like\n"
	.string "this for a picnic!$"

Route111_Text_CeliaDefeat:
	.string "Aww!\n"
	.string "I really shouldn't have come!$"

Route111_Text_CeliaPostBattle:
	.string "In a sandstorm like this, I can't set\n"
	.string "the places for a picnic even with my\l"
	.string "GO-GOGGLES on…$"

Route111_Text_BryanIntro:
	.string "How tough are you?\n"
	.string "We shall expose that secret!$"

Route111_Text_BryanDefeat:
	.string "Oh! Your strength!\n"
	.string "It is shrouded in mystery!$"

Route111_Text_BryanPostBattle:
	.string "This desert hoards mysteries in\n"
	.string "its shifting sands!$"

Route111_Text_BrandenIntro:
	.string "I'll give you some of my sandwich\n"
	.string "if you'll lose.$"

Route111_Text_BrandenDefeat:
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_BrandenPostBattle:
	.string "My SANDSHREW loves eating\n"
	.string "my sandwiches.$"

Route111_Text_TyronIntro:
	.string "This is my favorite kind of POKéMON!$"

Route111_Text_TyronDefeat:
	.string "Wait!\n"
	.string "Did you get a good look at my POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "When having a battle, I get a kick out\n"
	.string "of showing off my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they enter a battle!$"

Route111_Text_CelinaIntro:
	.string "Show me how to put a little excitement\n"
	.string "into my life.$"

Route111_Text_CelinaDefeat:
	.string "Oh… My…\n"
	.string "That was too much excitement.$"

Route111_Text_CelinaPostBattle:
	.string "My pulse is still racing.\n"
	.string "You're one fabulous TRAINER.$"

Route111_Text_HaydenIntro:
	.string "When you're as famished as I am,\n"
	.string "there is no room for pity!$"

Route111_Text_HaydenDefeat:
	.string "Groan…$"

Route111_Text_HaydenPostBattle:
	.string "My stomach is grumbling!\n"
	.string "Maybe I can grill some BERRIES…$"

Route111_Text_BiancaIntro:
	.string "Did you come from MAUVILLE?\n"
	.string "Then you should be full of energy!$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "That's a lot to take!$"

Route111_Text_BiancaPostBattle:
	.string "This road here…\n"
	.string "You have quite a ways to travel.$"

Route112_Text_BriceIntro:
	.string "Y'all city folk wouldn't last a day out\n"
	.string "on the farm!$"

Route112_Text_BriceDefeat:
	.string "Ok, yer tougher than you look.$"

Route112_Text_BricePostBattle:
	.string "Farm life is tough, but you might have\n"
	.string "what it takes.$"

Route112_Text_TrentIntro:
	.string "Howdy!\n"
	.string "Are you headed to Moomoo Farm?$"

Route112_Text_TrentDefeat:
	.string "I reckon you'd make a good farmhand.$"

Route112_Text_TrentPostBattle:
	.string "Ma and Pa own Moomoo Farm, I always had\n"
	.string "fun playin' with the Miltank when I was\l"
	.string "younger.$"

Route112_Text_TrentRegister:
	.string "If you're ever interested in workin' on\n"
	.string "the farm, or if you just want another\l"
	.string "battle sometime...$"

Route112_Text_TrentRematchIntro:
	.string "I knew you'd be back, let's battle!$"

Route112_Text_TrentRematchDefeat:
	.string "I reckon you're even stronger than last\n"
	.string "time!$"

Route112_Text_TrentRematchPostBattle:
	.string "Ma and Pa own Moomoo Farm, I always had\n"
	.string "fun playin' with the Miltank when I was\l"
	.string "younger.$"

Route112_Text_LarryIntro:
	.string "Three years ago I had a vision...\p"
	.string "I forsaw us having a battle!$"

Route112_Text_LarryDefeat:
	.string "Unfortunately, this is the same\n"
	.string "outcome I saw in my vision.$"

Route112_Text_LarryPostBattle:
	.string "Knowing the future isn't as fun when I\n"
	.string "can't change it.$"

Route112_Text_CarolIntro:
	.string "Would you like me to read your fortune?\p"
	.string "It ends in your defeat!$"

Route112_Text_CarolDefeat:
	.string "No, my predictions have never been\n"
	.string "wrong before...$"

Route112_Text_CarolPostBattle:
	.string "There's something special about you...\p"
	.string "I just can't place my finger on what it\n"
	.string "is exactly...$"

Route112_Text_BryantIntro:
	.string "Fly! My fools!$"

Route112_Text_BryantDefeat:
	.string "What a bumpy flight that was!$"

Route112_Text_BryantPostBattle:
	.string "I didn't expect to lose to a ground\n"
	.string "dweller such as yourself.$"

Route112_Text_ShaylaIntro:
	.string "My my, what an adorable TRAINER.\n"
	.string "Care for a battle?$"

Route112_Text_ShaylaDefeat:
	.string "Adorable and strong!\n"
	.string "Two great qualities.$"

Route112_Text_ShaylaPostBattle:
	.string "This is my favorite route to take walks\n"
	.string "on, there's just something about it\l"
	.string "that put's me at peace.$"

Route113_Text_JaylenIntro:
	.string "This place stinks, and I almost fell\n"
	.string "through the floor!$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_JaylenPostBattle:
	.string "I'm giving this place the worst rating I\n"
	.string "can, nobody should come here.$"

Route113_Text_DillonIntro:
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive.$"

Route113_Text_DillonDefeat:
	.string "You're some kind of strong!$"

Route113_Text_DillonPostBattle:
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was bad, sorry…$"

Route113_Text_MadelineIntro:
	.string "I use this parasol to ward off this\n"
	.string "filthy, yucky volcanic ash from\l"
	.string "my dear NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff…\n"
	.string "I am exhausted…$"

Route113_Text_MadelinePostBattle:
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_MadelineRegister:
	.string "Here, slide under my parasol.\n"
	.string "Let me register you in my POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch:
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_LaoIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostBattle:
	.string "I must refine the art of concealment.\n"
	.string "I bid thee farewell.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of POKéNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_LungDefeat:
	.string "I'll use my ninjutsu on you…\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "…What?\n"
	.string "It's already over?$"

Route113_Text_LungPostBattle:
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_ToriIntro:
	.string "TORI: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_ToriDefeat:
	.string "TORI: We lost… It's boring, so I'm going\n"
	.string "to get some more ashes.$"

Route113_Text_ToriPostBattle:
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_TiaIntro:
	.string "TIA: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_TiaDefeat:
	.string "TIA: We couldn't win… It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_TiaPostBattle:
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "Pfft, with these wings I can\n"
	.string "flick you away!$"

Route113_Text_CobyDefeat:
	.string "A… What?$"

Route113_Text_CobyPostBattle:
	.string "I don't know what to say when I get\n"
	.string "beaten so easily…$"

Route113_Text_SophieIntro:
	.string "I got separated from my tour group,\n"
	.string "maybe a loud battle will alert them to\l"
	.string "my location!$"

Route113_Text_SophieDefeat:
	.string "That battle got way too intense!$"

Route113_Text_SophiePostBattle:
	.string "They really need to put up some signs in\n"
	.string "this place, it's too easy to get lost.$"

Route113_Text_LawrenceIntro:
	.string "I read some great reviews about this\n"
	.string "place, but it's a pile of trash!$"

Route113_Text_LawrenceDefeat:
	.string "No need to be so hostile!$"

Route113_Text_LawrencePostBattle:
	.string "I wanted to go to the Bell Tower\n"
	.string "instead, but they wouldn't let me in.\p"
	.string "This town is the worst!$"

Route113_Text_WyattIntro:
	.string "Excuse me, do you work here?\p"
	.string "I just saw a huge rat!$"

Route113_Text_WyattDefeat:
	.string "So, you don't work here?$"

Route113_Text_WyattPostBattle:
	.string "Whoever runs this place really needs to\n"
	.string "do something about the rat problem!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_LucasDefeat:
	.string "The mountains are unforgiving…$"

Route114_Text_LucasPostBattle:
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_ShaneIntro:
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_ShaneDefeat:
	.string "Way too strong!$"

Route114_Text_ShanePostBattle:
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_NancyIntro:
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_NancyDefeat:
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-My POKéMON…$"

Route114_Text_StevePostBattle:
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I wish I had a POKéMON like that…$"

Route114_Text_SteveRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, battle my POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro:
	.string "If you're lighting a campfire,\n"
	.string "make sure you have water handy.$"

Route114_Text_BernieDefeat:
	.string "Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_BernieRegister:
	.string "You set my spirit on fire.\n"
	.string "Let's register each other!$"

Route114_Text_BernieRematchIntro:
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_BerniePostRematch:
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "If we were fishing, I would've won…$"

Route114_Text_ClaudePostBattle:
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_NolanIntro:
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_NolanDefeat:
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it…$"

Route114_Text_NolanPostBattle:
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_IvyIntro:
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: What an amazing battle style!$"

Route114_Text_IvyPostBattle:
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_KaiIntro:
	.string "I landed a big one!\n"
	.string "A huge one, I tell you!$"

Route114_Text_KaiDefeat:
	.string "What was that about?\n"
	.string "Did mine lose in size?$"

Route114_Text_KaiPostBattle:
	.string "Okay!\n"
	.string "I'll just fish me a bigger one!$"

Route114_Text_CharlotteIntro:
	.string "Me!\n"
	.string "I'm not just a pretty face!$"

Route114_Text_CharlotteDefeat:
	.string "That wasn't cute in the least!$"

Route114_Text_CharlottePostBattle:
	.string "I don't want a POKéMON that's\n"
	.string "just cute.\p"
	.string "I adore cute ones that have a quirk\n"
	.string "or two!$"

Route114_Text_AngelinaIntro:
	.string "Have you made your POKéMON evolve\n"
	.string "very much?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, I see.\n"
	.string "That's good to know.$"

Route114_Text_AngelinaPostBattle:
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it's startling!$"

Route115_Text_TimothyIntro:
	.string "Oh ho, thought you could sneak past a\n"
	.string "sleepy old man, did you?$"

Route115_Text_TimothyDefeat:
	.string "Now I really need a nap...$"

Route115_Text_TimothyPostBattle:
	.string "Zzz...\p"
	.string "Huh!?$"

Route115_Text_TimothyRegister:
	.string "You're not too bad...\p"
	.string "Maybe we can battle again between my\n"
	.string "nap times.$"

Route115_Text_TimothyRematchIntro:
	.string "You caught me in between naps, let's go!$"

Route115_Text_TimothyRematchDefeat:
	.string "Zzz...$"

Route115_Text_TimothyPostRematch:
	.string "Zzz...\p"
	.string "Huh!?$"

Route115_Text_KoichiIntro:
	.string "I could stay in this park forever, there\n"
	.string "are so many great BUGS!$"

Route115_Text_KoichiDefeat:
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:
	.string "Must be careful, BUGS are known to\n"
	.string "sting!$"

Route115_Text_NobIntro:
	.string "You caught me!$"

Route115_Text_NobDefeat:
	.string "Couldn't catch a break...$"

Route115_Text_NobPostBattle:
	.string "I was trying to throw you off, but you\n"
	.string "caught me anyway.\p"
	.string "You would make a good bug catcher!$"

Route115_Text_NobRegister:
	.string "You would make a good bug catcher.\p"
	.string "Register me, so you can teach me your\n"
	.string "catching ways.$"

Route115_Text_NobRematchIntro:
	.string "You caught me again!$"

Route115_Text_NobRematchDefeat:
	.string "I still can't catch a break...$"

Route115_Text_NobPostRematch:
	.string "I was trying to throw you off, but you\n"
	.string "caught me anyway.\p"
	.string "You would make a good bug catcher!$"

Route115_Text_CyndyIntro:
	.string "I was throwing coins into the fountain,\n"
	.string "but got bored.\p"
	.string "You! Battle with me!$"

Route115_Text_CyndyDefeat:
	.string "You're tougher than I expected.$"

Route115_Text_CyndyPostBattle:
	.string "Throwing coins into the fountain is fun,\n"
	.string "but my wishes never come true.$"

Route115_Text_CyndyRegister:
	.string "I wish to battle with you again.\p"
	.string "Give me your POKéNAV...$"

Route115_Text_CyndyRematchIntro:
	.string "I made a wish that you would return, and\n"
	.string "here you are!$"

Route115_Text_CyndyRematchDefeat:
	.string "You're still as tough as ever…$"

Route115_Text_CyndyPostRematch:
	.string "Throwing coins into the fountain is fun,\n"
	.string "but my wishes never come true.$"

Route115_Text_HectorIntro:
	.string "Am I bugging you?\p"
	.string "Hey, hey!\p"
	.string "Hey!$"

Route115_Text_HectorDefeat:
	.string "I should have left you alone.$"

Route115_Text_HectorPostBattle:
	.string "Does our copying bug you?$"

Route115_Text_KyraIntro:
	.string "I got you!\p"
	.string "Wait, you're no bug!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp…$"

Route115_Text_KyraPostBattle:
	.string "I've been catching too many bugs,\n"
	.string "they're all I see now.$"

Route115_Text_JaidenIntro:
	.string "Take that!\n"
	.string "Super POKéMON ninja attack!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "Our strategy failed!$"

Route115_Text_JaidenPostBattle:
	.string "But my POKéMON were strong,\n"
	.string "weren't they?$"

Route115_Text_HeleneIntro:
	.string "Do you know what goes best with a\n"
	.string "picnic?\p"
	.string "That's right, a battle!$"

Route115_Text_HeleneDefeat:
	.string "Ok, maybe I was wrong.$"

Route115_Text_HelenePostBattle:
	.string "A battle only goes well with a picnic if\n"
	.string "I win...$"

Route115_Text_AlixIntro:
	.string "Pick up that trash!$"

Route115_Text_AlixDefeat:
	.string "Sorry, I was mistaken...$"

Route115_Text_AlixPostBattle:
	.string "I thought I saw you littering, but I was\n"
	.string "mistaken.\p"
	.string "I almost wrote you a citation.\p"
	.string "...\p"
	.string "Hey, that rhymed!$"

Route115_Text_MarleneIntro:
	.string "The tall grass, or the short grass?\p"
	.string "Which has the better POKéMON?$"

Route115_Text_MarleneDefeat:
	.string "Maybe the same POKéMON are in both\n"
	.string "grass patches?$"

Route115_Text_MarlenePostBattle:
	.string "I still can't figure out if the tall\n"
	.string "grass is any better than the short\l"
	.string "grass...$"

Route116_Text_ClarkIntro:
	.string "You're no match for my super rare\n"
	.string "POKéMON!$"

Route116_Text_ClarkDefeat:
	.string "Perhaps I was wrong about you…$"

Route116_Text_ClarkPostBattle:
	.string "Have you found any rare POKéMON in this\n"
	.string "cave yet?$"

Route116_Text_JoeyIntro:
	.string "Rocky caves like this are great!\p"
	.string "What's not to love?$"

Route116_Text_JoeyDefeat:
	.string "Ouch, I got rocked.$"

Route116_Text_JoeyPostBattle:
	.string "Have you been to the mountains up\n"
	.string "north?\p"
	.string "They have plenty of great caves to\n"
	.string "explore.$"

Route116_Text_JoseIntro:
	.string "My POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_JosePostBattle:
	.string "ROCK and GROUND-type POKéMON are the\n"
	.string "best, wouldn't you agree?$"

Route116_Text_JaniceIntro:
	.string "Don't play with fire unless you're\n"
	.string "prepared to get burned!$"

Route116_Text_JaniceDefeat:
	.string "You're a notch above me…$"

Route116_Text_JanicePostBattle:
	.string "I came into Union Cave to hide from the\n"
	.string "rain on Route 33, it's too wet out there\l"
	.string "for my POKéMON.$"

Route116_Text_JerryIntro:
	.string "A hiker must know when he's reached his\n"
	.string "limit.$"

Route116_Text_JerryDefeat:
	.string "I guess you were above my limit.$"

Route116_Text_JerryPostBattle:
	.string "I'll have to train myself to overcome my\n"
	.string "limits.$"

Route116_Text_JerryRegister1:
	.string "You're not half bad.\p"
	.string "Maybe we can battle again sometime...$"

Route116_Text_JerryRegister2:
	.string "You're not half bad.\p"
	.string "Maybe we can battle again sometime...$"

Route116_Text_JerryRematchIntro:
	.string "I've been in training all this time.\p"
	.string "I've pushed well past my old limits,\n"
	.string "allow me to show you!$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "I trained so hard though.$"

Route116_Text_JerryPostRematch:
	.string "It seems my training is not yet\n"
	.string "complete.$"

Route116_Text_KarenIntro:
	.string "I got lost in this cave, and can't find\n"
	.string "my way out!$"

Route116_Text_KarenDefeat:
	.string "Now I've lost in more ways than one.$"

Route116_Text_KarenPostBattle:
	.string "You know what, it's ok, I'm starting to\n"
	.string "like this cave.$"

Route116_Text_KarenRegister1:
	.string "Hey, is that a POKéNAV?\p"
	.string "Register me, at least then I won't get\n"
	.string "too lonely.$"

Route116_Text_KarenRegister2:
	.string "Hey, is that a POKéNAV?\p"
	.string "Register me, at least then I won't get\n"
	.string "too lonely.$"

Route116_Text_KarenRematchIntro:
	.string "Remember me?\p"
	.string "Yep, I'm still in this same cave.\p"
	.string "It's really not bad once you get used to\n"
	.string "it.\p"
	.string "I'm bored though, let's battle!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch:
	.string "This cave really isn't that bad once you\n"
	.string "get used to it.$"

Route116_Text_SarahIntro:
	.string "Just so you know, I've never once been\n"
	.string "bested by anyone at anything.$"

Route116_Text_SarahDefeat:
	.string "Oh, wow.\n"
	.string "This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "I guess there's a first time for\n"
	.string "everything.\p"
	.string "Even losing.$"

Route116_Text_DawsonIntro:
	.string "Are you here looking for the rare\n"
	.string "POKéMON too?$"

Route116_Text_DawsonDefeat:
	.string "Oh no, say it isn't so!$"

Route116_Text_DawsonPostBattle:
	.string "I heard rumors there's a very rare\n"
	.string "POKéMON here.$"

Route116_Text_DevanIntro:
	.string "Where are the Lapras?\p"
	.string "I heard they were in this cave!$"

Route116_Text_DevanDefeat:
	.string "No contest at all!$"

Route116_Text_DevanPostBattle:
	.string "Maybe that Lapras just isn't meant for\n"
	.string "me.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, so can we battle?$"

Route116_Text_JohnsonDefeat:
	.string "That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "Want to stay here and keep\n"
	.string "me company?$"

Route117_Text_IsaacIntro:
	.string "Have you been to the POKéMON daycare\n"
	.string "up ahead?\p"
	.string "Breeding POKéMON is a good way to get\n"
	.string "good natures and egg moves!$"

Route117_Text_IsaacDefeat:
	.string "You've raised your POKéMON well.$"

Route117_Text_IsaacPostBattle:
	.string "Battling is important, but breeding and\n"
	.string "raising POKéMON should not be\l"
	.string "overlooked.$"

Route117_Text_IsaacRegister:
	.string "Hey, why don't you register me in your\n"
	.string "POKéNAV!\p"
	.string "That way I can make sure you are\n"
	.string "raising your POKéMON well.$"

Route117_Text_IsaacRematchIntro:
	.string "Hey, let's see how well you've raised\n"
	.string "your POKéMON!$"

Route117_Text_IsaacRematchDefeat:
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills…$"

Route117_Text_IsaacPostRematch:
	.string "Battling is important, but breeding and\n"
	.string "raising POKéMON should not be\l"
	.string "overlooked.$"

Route117_Text_LydiaIntro:
	.string "I left my POKéMON in the daycare, but\n"
	.string "couldn't stand not to come check up on\l"
	.string "him!$"

Route117_Text_LydiaDefeat:
	.string "I hope my little Azumarill didn't watch\n"
	.string "me lose!$"

Route117_Text_LydiaPostBattle:
	.string "Hmm, maybe I'll leave another POKéMON in\n"
	.string "the daycare with my Azumarill so he\l"
	.string "doesn't get too lonely...$"

Route117_Text_LydiaRegister:
	.string "You're a rather strong TRAINER, perhaps\n"
	.string "we could have a rematch sometime.$"

Route117_Text_LydiaRematchIntro:
	.string "There you are, {PLAYER}.\p"
	.string "I need a battle to keep my mind off my\n"
	.string "Azumarill.$"

Route117_Text_LydiaRematchDefeat:
	.string "I hope my little Azumarill didn't watch\n"
	.string "me lose!$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I'm training for the Goldenrod\n"
	.string "Marathon, but I suppose I could take a\l"
	.string "quick break and battle!$"

Route117_Text_DylanDefeat:
	.string "You're lucky that I'm still exhausted\n"
	.string "from running.$"

Route117_Text_DylanPostBattle:
	.string "What do you mean you've never heard of\n"
	.string "the Goldenrod Marathon?$"

Route117_Text_DylanRegister:
	.string "If I ever recover my energy, I would\n"
	.string "like to battle with you again...$"

Route117_Text_DylanRematchIntro:
	.string "I'm right in the middle of training, but I\n"
	.string "always have time for a quick battle!$"

Route117_Text_DylanRematchDefeat:
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:
	.string "I didn't do very well in the Goldenrod\n"
	.string "Marathon, I suppose there's always\l"
	.string "next year...$"

Route117_Text_MariaIntro:
	.string "I do my marathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_MariaRegister:
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:
	.string "I want to show these girls my bug\n"
	.string "collection, but I'm too nervous to talk\l"
	.string "to them!$"

Route117_Text_DerekDefeat:
	.string "I lost, now I really can't go talk to\n"
	.string "these girls.$"

Route117_Text_DerekPostBattle:
	.string "Some people just don't have an\n"
	.string "appreciation for bugs...$"

Route117_Text_AnnaIntro:
	.string "LYNN: Oh you look strong, how about a\n"
	.string "double battle!$"

Route117_Text_AnnaDefeat:
	.string "LYNN: I guess your looks were not\n"
	.string "deceiving, you are strong!$"

Route117_Text_AnnaPostBattle:
	.string "LYNN: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "LYNN: You will battle us again, won't\n"
	.string "you?\p"
	.string "We will show you the true power of our\n"
	.string "friendship!$"

Route117_Text_AnnaNotEnoughMons:
	.string "LYNN: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegIntro:
	.string "EVE: We will show you what true\n"
	.string "friendship can accomplish, come on\l"
	.string "LYNN!$"

Route117_Text_MegDefeat:
	.string "EVE: Our friendship wasn't powerful\n"
	.string "enough!$"

Route117_Text_MegPostBattle:
	.string "EVE: Double battles are fun, wouldn't\n"
	.string "you agree?$"

Route117_Text_MegNotEnoughMons:
	.string "EVE: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "LYNN: Are you prepared for a rematch,\n"
	.string "our friendship will crush you this time!$"

Route117_Text_AnnaRematchDefeat:
	.string "LYNN: You're still as strong as ever...$"

Route117_Text_AnnaPostRematch:
	.string "LYNN: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "LYNN: If you want to battle us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegRematchIntro:
	.string "EVE: LYNN and I have been practicing\n"
	.string "double battles, prepare to lose this\l"
	.string "time!$"

Route117_Text_MegRematchDefeat:
	.string "EVE: Too strong!$"

Route117_Text_MegPostRematch:
	.string "EVE: Double battles are fun, wouldn't\n"
	.string "you agree?$"

Route117_Text_MegRematchNotEnoughMons:
	.string "EVE: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Oh, it seems there is a TRAINER in my\n"
	.string "path!$"

Route117_Text_MelinaDefeat:
	.string "Oh, that's quite impressive!$"

Route117_Text_MelinaPostBattle:
	.string "Running always relaxes me after a tough\n"
	.string "battle.$"

Route117_Text_BrandiIntro:
	.string "This creepy guy keeps looking at us.\n"
	.string "Maybe if he sees how tough we are, he\l"
	.string "will leave us alone!$"

Route117_Text_BrandiDefeat:
	.string "Astonishing!$"

Route117_Text_BrandiPostBattle:
	.string "The creepy guy still hasn't left, and\n"
	.string "why is he holding a net?$"

Route117_Text_AishaIntro:
	.string "I want to leave, but don't want to turn\n"
	.string "my back on this creepy guy!$"

Route117_Text_AishaDefeat:
	.string "You're pretty tough, maybe you can run\n"
	.string "off the creepy guy.$"

Route117_Text_AishaPostBattle:
	.string "When will this creepy guy let us leave?$"

Route118_Text_RoseIntro:
	.string "I love the sweet smell of flowers,\n"
	.string "nature really does create the finest\l"
	.string "perfume!$"

Route118_Text_RoseDefeat:
	.string "Oh, what is this foul stench?$"

Route118_Text_RosePostBattle:
	.string "You say you're from Cherrygrove?\p"
	.string "I've heard they have the best flowers.$"

Route118_Text_RoseRegister:
	.string "Sniff… That odor--it's a POKéNAV!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Did you come for a rematch, or to talk\n"
	.string "about the flowers?\p"
	.string "A rematch it is!$"

Route118_Text_RoseRematchDefeat:
	.string "There's that foul stench of defeat\n"
	.string "again...$"

Route118_Text_RosePostRematch:
	.string "You say you're from Cherrygrove?\p"
	.string "I've heard they have the best flowers.$"

Route118_Text_PerryIntro:
	.string "My bird POKéMON always have the high\n"
	.string "ground!\p"
	.string "There's no way I can lose!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "I crashed…$"

Route118_Text_PerryPostBattle:
	.string "I guess having the high ground doesn't\n"
	.string "always guarantee victory.$"

Route118_Text_ChesterIntro:
	.string "Nothing is more freeing than flight!$"

Route118_Text_ChesterDefeat:
	.string "Oof...\n"
	.string "Knocked back down to earth!$"

Route118_Text_ChesterPostBattle:
	.string "If you have the HM02, you can hitch a\n"
	.string "ride on your POKéMON and fly with them!$"

Route118_Text_BarnyIntro:
	.string "Fishing isn't too exciting at the\n"
	.string "moment, maybe you can liven things up\l"
	.string "for me!$"

Route118_Text_BarnyDefeat:
	.string "That's a little too lively for me.$"

Route118_Text_BarnyPostBattle:
	.string "The fish here are not very exciting,\n"
	.string "maybe I'll find a new fishing spot.$"

Route118_Text_WadeIntro:
	.string "Nobody can outfish me!\p"
	.string "I am a master baiter!$"

Route118_Text_WadeDefeat:
	.string "I'll have to try a different bait next\n"
	.string "time...$"

Route118_Text_WadePostBattle:
	.string "Choosing the perfect bait is the key to\n"
	.string "fishing.\p"
	.string "Maybe one day you too can become a\n"
	.string "master baiter like myself.$"

Route118_Text_DaltonIntro:
	.string "I'm amped up and ready for a battle!$"

Route118_Text_DaltonDefeat:
	.string "I've lost my spark!$"

Route118_Text_DaltonPostBattle:
	.string "I need to go recharge now.$"

Route118_Text_DaltonRegister:
	.string "You just rocked my world, maybe next\n"
	.string "time I can rock yours...$"

Route118_Text_DaltonRematchIntro:
	.string "I'm amped up again and ready for\n"
	.string "another battle!$"

Route118_Text_DaltonRematchDefeat:
	.string "I'm all out of juice!$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Sneak attack!$"

Route118_Text_DeandreDefeat:
	.string "You saw me through the fence?\p"
	.string "I guess I wasn't sneaky enough.$"

Route118_Text_DeandrePostBattle:
	.string "I was trying to emulate a ninja that\n"
	.string "jumped out from behind a fake tree and\l"
	.string "battled me.$"

Route119_Text_BrentIntro:
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_BrentDefeat:
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_BrentPostBattle:
	.string "What's so good about mimicry?\p"
	.string "Fufufu…\n"
	.string "You'll never understand…$"

Route119_Text_DonaldIntro:
	.string "Hey! Who let you out of your cell!?$"

Route119_Text_DonaldDefeat:
	.string "With that strength, you must have\n"
	.string "broken out yourself.$"

Route119_Text_DonaldPostBattle:
	.string "No, please, just walk around our base\n"
	.string "like you own the place.\p"
	.string "Psh, kids.$"

Route119_Text_TaylorIntro:
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too…$"

Route119_Text_TaylorDefeat:
	.string "But if you win, I lose…$"

Route119_Text_TaylorPostBattle:
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible…\l"
	.string "It's burning me up…$"

Route119_Text_DougIntro:
	.string "Really? Which GRUNT forgot to take your\n"
	.string "POKéMON away from you?$"

Route119_Text_DougDefeat:
	.string "You're tougher than you look...$"

Route119_Text_DougPostBattle:
	.string "Having trouble with our warp pads?\n"
	.string "Haha!$"

Route119_Text_GregIntro:
	.string "Hey, you get back in your cell!\p"
	.string "I don't want DAMON to yell at me again!$"

Route119_Text_GregDefeat:
	.string "Great, I'll get yelled at for sure now.$"

Route119_Text_GregPostBattle:
	.string "This is a pretty stressful job, you\n"
	.string "know.\p"
	.string "Ah, you wouldn't understand.$"

Route119_Text_KentIntro:
	.string "Really, kid? I'm on my break!$"

Route119_Text_KentDefeat:
	.string "Now I really need a break!$"

Route119_Text_KentPostBattle:
	.string "I should have went with the other\n"
	.string "GRUNTS to the Ecruteak Base.$"

Route119_Text_JacksonIntro:
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:
	.string "I didn't have enough POKéMON\n"
	.string "know-how…$"

Route119_Text_JacksonPostBattle:
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRegister:
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure,\n"
	.string "you're traveling awfully light.$"

Route119_Text_CatherineDefeat:
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherinePostBattle:
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_CatherineRegister:
	.string "Do you have a POKéNAV?\n"
	.string "It's a must-have tool for any TRAINER.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_CatherineRematchIntro:
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:
	.string "I'm still missing something…$"

Route119_Text_CatherinePostRematch:
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_HughIntro:
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_HughDefeat:
	.string "Down and out!$"

Route119_Text_HughPostBattle:
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_PhilIntro:
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_PhilDefeat:
	.string "We lacked potential…$"

Route119_Text_PhilPostBattle:
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "And who might you be?\p"
	.string "An intruder!$"

Route119_Text_YasuDefeat:
	.string "A strong intruder, it seems...$"

Route119_Text_YasuPostBattle:
	.string "How did you discover our secret base?\p"
	.string "...\p"
	.string "Oh, DAMON must have brought you here.\p"
	.string "Crap, he'll be mad when he finds out you\n"
	.string "escaped.\p"
	.string "Could you please go back to your cell\n"
	.string "and wait there?$"

Route119_Text_TakashiIntro:
	.string "They never let me go on any fun\n"
	.string "missions, it's so boring at this base!$"

Route119_Text_TakashiDefeat:
	.string "Well at least that battle wasn't\n"
	.string "boring...$"

Route119_Text_TakashiPostBattle:
	.string "Who are you anyway?$"

Route119_Text_HideoIntro:
	.string "Alright kid, this is as far as you're\n"
	.string "going.\p"
	.string "Back to your cell!$"

Route119_Text_HideoDefeat:
	.string "So that's how you got past the other\n"
	.string "GRUNTS...$"

Route119_Text_HideoPostBattle:
	.string "You defeated me in a POKéMON battle, I\n"
	.string "guess there isn't anything else I can\l"
	.string "do to stop you now...$"

Route119_Text_ChrisIntro:
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_ChrisDefeat:
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_ChrisPostBattle:
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_FabianIntro:
	.string "Hit me with a power chord!\n"
	.string "Victory is mine!\l"
	.string "It's our time to shine, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "You showed me who's the boss!\n"
	.string "We'll have to take the loss, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Hit me with another power chord!\n"
	.string "Leave me alone!\l"
	.string "Your win you have to atone!$"

Route119_Text_DaytonIntro:
	.string "Are you one of the new recruits?\p"
	.string "...\p"
	.string "Hey wait! You're one of the kids they\n"
	.string "captured!$"

Route119_Text_DaytonDefeat:
	.string "Where did you get POKéMON that good?$"

Route119_Text_DaytonPostBattle:
	.string "Maybe you should be one of our new\n"
	.string "recruits, have you ever thought about\l"
	.string "committing to a life of crime?$"

Route119_Text_RachelIntro:
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_RachelDefeat:
	.string "Oh, but…\n"
	.string "That's not fair.$"

Route119_Text_RachelPostBattle:
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than\l"
	.string "I ever carry around.$"

Route120_Text_ColinIntro:
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_ColinDefeat:
	.string "You soared above me!$"

Route120_Text_ColinPostBattle:
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_RobertIntro:
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:
	.string "Your POKéMON were stronger…$"

Route120_Text_RobertPostBattle:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRegister:
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_LorenzoDefeat:
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_LorenzoPostBattle:
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat:
	.string "I'm totally fit, but…$"

Route120_Text_JennaPostBattle:
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "Lost it…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious BUG POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat:
	.string "What a disgraceful setback…$"

Route120_Text_ChipPostBattle:
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks…$"

Route120_Text_ClarissaPostBattle:
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:
	.string "Me, POKéMON, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:
	.string "You've completely ruined my beauty…$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro:
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat:
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_KeigoPostBattle:
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_RileyIntro:
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_RileyDefeat:
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_CallieIntro:
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_CallieDefeat:
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_CalliePostBattle:
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_LeonelIntro:
	.string "Your party POKéMON…\n"
	.string "Do you have different types?$"

Route120_Text_LeonelDefeat:
	.string "I've seen your policy in action!$"

Route120_Text_LeonelPostBattle:
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat:
	.string "I have lost…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_CristinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle:
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro:
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route123_Text_WendyIntro:
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:
	.string "I floundered…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:
	.string "Lost it…$"

Route125_Text_SharonPostBattle:
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was done in?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle:
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:
	.string "It'd be a handful if I hooked\n"
	.string "your tough POKéMON!$"

Route127_Text_RogerIntro:
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanDefeat:
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle:
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great.\n"
	.string "But your RUNNING SHOES are cool, too.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaDefeat:
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_AthenaPostBattle:
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away…$"

Route128_Text_IsaiahDefeat:
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_IsaiahPostBattle:
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "I have to ride a BIKE next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_RubenIntro:
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:
	.string "This can't be!$"

Route128_Text_RubenPostBattle:
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "There are tough TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle:
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat:
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat:
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You have your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat:
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"
