MtPyre_1F_MapScripts::
	.byte 0


MtPyre_1F_EventScript_Sage::
	msgbox MtPyre_1F_EventScript_Sage_Text_0, MSGBOX_NPC
	end


MtPyre_1F_EventScript_OldWoman::
	msgbox MtPyre_1F_EventScript_OldWoman_Text_0, MSGBOX_NPC
	end


MtPyre_1F_EventScript_Hex::
	msgbox MtPyre_1F_EventScript_Hex_Text_0, MSGBOX_NPC
	end


MtPyre_1F_EventScript_Sage_Text_0:
	.string "Feel free to explore the ruins, but\n"
	.string "please be respectful.\p"
	.string "These are sacred grounds.$"

MtPyre_1F_EventScript_OldWoman_Text_0:
	.string "These ruins must be thousands of years\n"
	.string "old.$"

MtPyre_1F_EventScript_Hex_Text_0:
	.string "These ruins are so spooky, I love it\n"
	.string "here!$"
