RustboroCity_CuttersHouse_MapScripts::
	.byte 0


RustboroCity_CuttersHouse_EventScript_Man::
	msgbox RustboroCity_CuttersHouse_EventScript_Man_Text_0, MSGBOX_NPC
	end


RustboroCity_CuttersHouse_EventScript_Girl::
	msgbox RustboroCity_CuttersHouse_EventScript_Girl_Text_0, MSGBOX_NPC
	end


RustboroCity_CuttersHouse_EventScript_Man_Text_0:
	.string "Please, feel free to walk right into my\n"
	.string "house without knocking.\p"
	.string "No really, it's fine. I love when random\n"
	.string "people just barge in.$"

RustboroCity_CuttersHouse_EventScript_Girl_Text_0:
	.string "Just ignore my dad, he can be so\n"
	.string "dramatic. Most people in Johto don't\l"
	.string "mind uninvited guests.$"
