SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Bah! All this hubbub about some rock\n"
	.string "flying through the sky!\p"
	.string "It's not that big of a deal!$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Grandpa really doesn't like big crowds\n"
	.string "of people.\p"
	.string "I'm not sure why he chose to settle\n"
	.string "down in such a large city...$"

