PacifidlogTown_House3_MapScripts::
	.byte 0

PacifidlogTown_House3_EventScript_Trader::
	msgbox PacifidlogTown_House3_Text_ItsSubtlyDifferentThankYou, MSGBOX_NPC
	end

PacifidlogTown_House3_EventScript_Girl::
	msgbox PacifidlogTown_House3_Text_IsThatAPokedex, MSGBOX_NPC
	end

PacifidlogTown_House3_Text_ItsSubtlyDifferentThankYou:
	.string "There's never anything good on TV\n"
	.string "these days.\p"
	.string "I miss the old reality shows...\p"
	.string "Let's see, there was Driftveil Shore...\n"
	.string "Real Housewives of Castelia...$"

PacifidlogTown_House3_Text_IsThatAPokedex:
	.string "We moved to this expensive retirement\n"
	.string "community for the nice view and warm\l"
	.string "weather, but all my husband wants to do\l"
	.string "is watch TV all day.$"

