LilycoveCity_House3_MapScripts::
	.byte 0

LilycoveCity_House3_EventScript_PokefanF::
	msgbox LilycoveCity_House3_Text_OhAreYouSure, MSGBOX_NPC
	end

LilycoveCity_House3_EventScript_Man::
	msgbox LilycoveCity_House3_Text_HappyToHaveQuadruplets, MSGBOX_NPC
	end

LilycoveCity_House3_EventScript_GameBoyKid1::
	msgbox LilycoveCity_House3_Text_GoingToWinMultiBattles, MSGBOX_NPC
	end

LilycoveCity_House3_Text_OhAreYouSure:
	.string "Oh, I wish my son would go outside and\n"
	.string "play instead of spending all of his time\l"
	.string "in front of that game screen.$"

LilycoveCity_House3_Text_HappyToHaveQuadruplets:
	.string "You can't expect kids to play outside\n"
	.string "when it's raining all day and night.\p"
	.string "We should move to a town with better\n"
	.string "weather.$"

LilycoveCity_House3_Text_GoingToWinMultiBattles:
	.string "I'm playing a game called Giratina\n"
	.string "Strikes Back, have you heard of it?\p"
	.string "This one is pretty hard to get.$"

