PacifidlogTown_House4_MapScripts::
	.byte 0

PacifidlogTown_House4_EventScript_LittleGirl::
	msgbox PacifidlogTown_House4_Text_SkyPokemon, MSGBOX_NPC
	end

PacifidlogTown_House4_EventScript_Woman::
	msgbox PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon, MSGBOX_NPC
	end

PacifidlogTown_House4_EventScript_Boy::
	msgbox PacifidlogTown_House4_Text_YesTown, MSGBOX_NPC
	end

PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon:
	.string "Did you get that money I sent you for\n"
	.string "Christmas?\p"
	.string "No?\p"
	.string "Well then, I'll have to send you some\n"
	.string "more in the mail.$"

PacifidlogTown_House4_Text_SkyPokemon:
	.string "I don't mind cleaning up around this\n"
	.string "community.\p"
	.string "I get to help out the elderly, and they\n"
	.string "pay pretty well.$"

PacifidlogTown_House4_Text_YesTown:
	.string "Humph! Politicians!\p"
	.string "You can't trust any of them, I tell you!$"

