RustboroCity_Flat2_3F_MapScripts::
	.byte 0


RustboroCity_Flat2_3F_Man::
	msgbox RustboroCity_Flat2_3F_Man_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_Girl::
	msgbox RustboroCity_Flat2_3F_Girl_Text_0, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_Man_Text_0:
	.string "Have you heard of The Thunderbolts?\n"
	.string "They're my favorite band.\p"
	.string "Their lead singer, CHARLIE, is also the\n"
	.string "Olivine City gym leader.$"

RustboroCity_Flat2_3F_Girl_Text_0:
	.string "My boyfriend is obsessed with The\n"
	.string "Thunderbolts. They're all he ever talks\l"
	.string "about.$"
