NavelRock_Down01_MapScripts::
	.byte 0


NavelRock_Down01_EventScript_Guard::
	msgbox NavelRock_Down01_EventScript_Guard_Text_0, MSGBOX_NPC
	end


NavelRock_Down01_EventScript_Guard_Text_0:
	.string "Well, if it isn't {PLAYER}.\p"
	.string "You sure grew up fast, I remember when\n"
	.string "you were just a baby.\p"
	.string "I see you have your own POKéMON now,\n"
	.string "you can go on through.$"
